### ISSUE TITLE
disable convert to template in GUI / API until works again

### ISSUE THREAD

**Issue by hofkensj** [0-complexity/openvcloud#1006]

**Comment by grimpy** [comment]
Already disabled in API, please remove from g8vdc UI and cdgrid portal

**Comment by ahmedelsayed-93** [comment]
@grimpy  convert to template api still exists in cloudapi 
![image](https://user-images.githubusercontent.com/24386820/33651219-b5f8044e-da6d-11e7-9454-8322a9e1db84.png)

### software version
JumpScale
```
Core: branch: master (09b7fe8) 12/4/2017, 11:11:25 PM
Portal: branch: master (c997bb1) 11/28/2017, 5:32:06 PM
```
OpenvCloud
```
Core: branch: master (6d9c345) 12/5/2017, 4:08:12 PM
G8VDC: branch: master (695c7c0) 12/5/2017, 1:41:03 PM
Selfhealing: branch: master (56e0028) 12/5/2017, 4:05:10 PM
```
OpenvStorage be-g8-3
```
openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.0-1
openvstorage-webapps: 2.9.9-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.9-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.17
openvstorage: 2.9.9-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.1-1
openvstorage-sdm: 1.9.1-1
```

**Comment by grimpy** [comment]
Did you try the API? It gives a not implemented http error. This because it used to exist and it's comming back

**Comment by ahmedelsayed-93** [comment]
@grimpy  check the screenshot above 
it returned ```can only convert a stopped machine``` , 400
