### ISSUE TITLE
Suggestion to remove interrupt from the healtchecks

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1014]
Hi we have in some cases alarms for high interrupt that are bringing the panel in red status. 

The measurements for the high interrupt are not relevant to my opinion on operations as, 

High interrupts can be caused from high IO on ethernet or disk, that are already monitored individually in different checks.

The check it self provides no means of understanding a condition over the system, where the issue is and what actions should be followed. 

In the cases that we have seen as in https://docs.greenitglobe.com/gig/proj_russia_digital_energy/issues/344
https://docs.greenitglobe.com/gig/proj_russia_digital_energy/issues/214
There is nothing to be done, and the alarm is cleared after few minutes. 

Monitoring also the system during the time of the alarm using dstat / itop / top / iostat / bmon showed neither high cpu time, or traffic nor disk io.

**Comment by FastGeert** [comment]
@ashraffouda @alichaddad Talked to Jan about this. He says its impossible to get 30M interrupts in one physical machine. Can you first validate if the health check reading of the number of iops is implemented correctly?

**Comment by alichaddad** [comment]
Interruptions info are gathered from `/proc/stat` which should provide an accurate information about the system.

**Comment by alichaddad** [comment]
See: https://github.com/0-complexity/selfhealing/commit/ffbf54eb56b2701f4696078c6ba6110fccdba455
