### ISSUE TITLE
Cannot create portforwarding when Virtual Machine did not acquire an IP Address.

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1023]
We have several cases where a deployment test fails, or a new created machine fails to acquire an IP address.

Issues related:
https://docs.greenitglobe.com/gig/proj_russia_digital_energy/issues/343
https://docs.greenitglobe.com/gig/proj_gig_uk/issues/62

Eco, 
https://mr4.demo.greenitglobe.com/grid/error%20condition?id=75532513-b9cf-7350-ae15-268d9be7928c

Backtrace
  
------------------------------------------------------------------------------------------
  /tmp/jumpscripts/cloudscalers_deployment_test.py(line 191) (function create_fwd)
  ========== STACKFRAME==========
                        return publicport
                    publicports.append(int(forward['publicPort']))
                if publicport == 0:
                    publicport = 2000 + j.application.whoAmI.nid * 100
                    while publicport in publicports:
                        publicport += 1
                    j.console.echo('Creating portforward', log=True)
                    pcl.actors.cloudapi.portforwarding.create(cloudspace['id'], cloudspace['externalnetworkip'],
-->                                                           publicport, vmachine['id'], 22, 'tcp')
                    messages.append({'message': "Created port forward {}".format(publicport),
                                     'category': category, 'state': "OK"})
                    return publicport
            except Exception as e:
                eco = j.errorconditionhandler.processPythonExceptionObject(e)
                eco.process()
                msg = "Failed to create port forward [eco|/grid/error condition?id={}]".format(eco.guid)
  ============ LOCALS============
    DeployMentTestFailure : <class 'JumpScale.jumpscript_b0e2b385ba2f2cb639d831c05bbec235.DeployMentTestFailure'>
    category : Deployment Test
    cloudspace : {u'networkId': 206, u'status': u'DEPLOYED', u'updateTime': 1506718159, u'externalnetworkip': u'185.203.91.16/24', u'deletionTime': 0, u'descr': u'', u'allowedVMSizes': None, u'name': u'mr4', u'acl': [{u'status': u'CONFIRMED', u'guid': u'', u'right': u'CXDRAU', u'type': u'U', u'userGroupId': u'admin'}], u'creationTime': 1506702841, u'resourceProviderStacks': [], u'_meta': [u'osismodel', u'cloudbroker', u'cloudspace', 1], u'secret': u'f7f24c1c-3eb9-4f9d-b658-6bcc6feec971', u'gid': 2002, u'location': u'mr4', u'externalnetworkId': 2, u'resourceLimits': {u'CU_M': -1.0, u'CU_D': -1, u'CU_NP': -1, u'CU_I': -1, u'CU_C': -1}, u'guid': 6, u'id': 6, u'_ckey': u'', u'accountId': 2}
    e : 404:
 "Cannot create portforwarding when Virtual Machine did not acquire an IP Address."
    externalip : 185.203.91.16
    forward : {u'protocol': u'tcp', u'localPort': u'22', u'machineName': u'Sun Nov 26 22:12:32 2017 on cpu-14.mr4 (192.168.103.178)', u'publicIp': u'185.203.91.16', u'localIp': u'192.168.103.178', u'machineId': 4272, u'publicPort': u'5900', u'id': 20}
    ip : Undefined
    messages : [{'category': 'Deployment Test', 'message': 'Stack is in status ENABLED', 'uid': 'Stack Status', 'state': 'OK'}, {'category': 'Deployment Test', 'message': 'Found image Ubuntu 16.04 x64', 'state': 'OK'}, {'category': 'Deployment Test', 'message': 'Found account test_deployment', 'state': 'OK'}, {'category': 'Deployment Test', 'message': 'Found cloudspace mr4', 'state': 'OK'}, {'category': 'Deployment Test', 'message': 'VM deyployment', 'state': 'OK'}]
    now : 1511730851.73
    pcl : <JumpScale.portal.portal.PortalClient.PortalClient instance at 0x7fdcda1bdf38>
    publicports : [2600, 4100, 5600, 3300, 3900, 4400, 2601, 4200, 3800, 2400, 3700, 3200, 2300, 5700, 5500, 4101, 3600, 4300, 3400, 5800, 5900]
    vmachine : {u'cloudspaceid': 6, u'status': u'RUNNING', u'updateTime': 1511730846, u'disks': [{u'status': u'', u'sizeMax': 10, u'name': u'Boot disk', u'descr': u'Machine disk of type B', u'acl': {}, u'type': u'B', u'id': 8095}, {u'status': u'', u'sizeMax': 10, u'name': u'Disk nr 0', u'descr': u'Machine disk of type D', u'acl': {}, u'type': u'D', u'id': 8096}], u'locked': False, u'name': u'Sun Nov 26 22:12:34 2017 on cpu-05.mr4', u'storage': 20, u'sizeid': 1, u'hostname': u'vm-4280', u'creationTime': 1511730755, u'acl': [{u'status': u'CONFIRMED', u'type': u'U', u'right': u'ACDRUX', u'canBeDeleted': False, u'userGroupId': u'admin'}, {u'status': u'CONFIRMED', u'type': u'U', u'right': u'ACDRUX', u'canBeDeleted': False, u'userGroupId': u'hosnys@itsyouonline'}, {u'status': u'CONFIRMED', u'type': u'U', u'right': u'ACDRUX', u'canBeDeleted': False, u'userGroupId': u'mikhaieb@itsyouonline'}, {u'status': u'CONFIRMED', u'type': u'U', u'right': u'ACDRUX', u'canBeDeleted': False, u'userGroupId': u'mgaber@itsyouonline'}, {u'status': u'CONFIRMED', u'type': u'U', u'right': u'ACDRUX', u'canBeDeleted': False, u'userGroupId': u'shafikd@itsyouonline'}], u'osImage': u'Ubuntu 16.04 x64', u'accounts': [{u'password': u'*********', u'login': u'*******', u'guid': u''}], u'id': 4280, u'imageid': 3, u'interfaces': [{u'networkId': 0, u'deviceName': u'vm-4280-00ce', u'referenceId': u'', u'macAddress': u'52:54:00:00:25:30', u'type': u'bridge', u'status': u'', u'params': u'', u'guid': u'', u'ipAddress': u'Undefined'}], u'description': None}
  
------------------------------------------------------------------------------------------
  /opt/jumpscale7/var/code/actorremote_cloudapi_actor_portforwarding_.py(line 45) (function create)
  ========== STACKFRAME==========
            param:publicIp public ipaddress
            param:publicPort public port
            param:machineId id of the virtual machine
            param:localPort local port
            param:protocol protocol udp or tcp
            
            """
    
-->         resultcode,result=self._appserverclient.wsclient.callWebService("cloudapi","portforwarding","create",cloudspaceId=cloudspaceId,publicIp=publicIp,publicPort=publicPort,machineId=machineId,localPort=localPort,protocol=protocol)
            if resultcode != 0:
                raise RuntimeError("error in calling webservice cloudapi:portforwarding:create:cloudspaceId=cloudspaceId,publicIp=publicIp,publicPort=publicPort,machineId=machineId,localPort=localPort,protocol=protocol" )
            else:
                if j.basetype.dictionary.check(result) and result.has_key("result"):
                    return result["result"]
                else:
                    return result
  ============ LOCALS============
    protocol : tcp
    publicIp : 185.203.91.16/24
  
------------------------------------------------------------------------------------------
  /opt/jumpscale7/lib/JumpScale/portal/portal/PortalClientWS.py(line 73) (function callWebService)
  ========== STACKFRAME==========
                    params[key] = params["params"][key]
                params.pop("params")
            #params["caller"] = j.core.grid.config.whoami
    
            data = j.db.serializers.getSerializerType('j').dumps(params)
    
            headers = {'content-type': 'application/json'}
    
-->         result = self.httpconnection.post(url, headers=headers, data=data)
    
            contentType = result.headers['Content-Type']
            content = result.read()
    
            # j.logger.log("Received result %s" % content, 8)
    
            if contentType == CONTENT_TYPE_JSON:
  ============ LOCALS============
    actorname : portforwarding
    appname : cloudapi
    data : {"cloudspaceId":6,"protocol":"tcp","localPort":22,"machineId":4280,"publicIp":"185.203.91.16\/24","publicPort":5601}
    headers : {'content-type': 'application/json'}
    method : create
    params : {'cloudspaceId': 6, 'protocol': 'tcp', 'localPort': 22, 'machineId': 4280, 'publicIp': u'185.203.91.16/24', 'publicPort': 5601}
    scheme : https
    self : <JumpScale.portal.portal.PortalClientWS.PortalClientWS instance at 0x7fdcda1bdb90>
    url : https://10.220.2.1:443/restmachine/cloudapi/portforwarding/create?authkey=djtXHaPBi6HH
  
------------------------------------------------------------------------------------------
  /opt/jumpscale7/lib/JumpScale/baselib/http_client/HttpClient.py(line 92) (function post)
  ========== STACKFRAME==========
            @data is the raw aata which will be posted, if not params will be converted to json
            @params @question what are the params for?
            @headers e.g. headers={'content-type':'text/plain'}  (this is the default)
            """
            if headers==None:
                headers={'content-type':'text/plain'}               
                
            #print data
-->         response = self._http_request(url, data=data, headers=headers, method='POST',**params)
            return response
        
        def put(self, url, data=None, headers=None, **params):
            response = self._http_request(url, data=data, headers=headers, method='PUT', **params)
            return response
            
        def delete(self, url, data=None, headers=None, **params):
  ============ LOCALS============
    data : {"cloudspaceId":6,"protocol":"tcp","localPort":22,"machineId":4280,"publicIp":"185.203.91.16\/24","publicPort":5601}
    headers : {'content-type': 'application/json'}
    params : {}
    self : <JumpScale.baselib.http_client.HttpClient.Connection object at 0x7fdcda1c4410>
    url : https://10.220.2.1:443/restmachine/cloudapi/portforwarding/create?authkey=djtXHaPBi6HH
  
------------------------------------------------------------------------------------------
  /opt/jumpscale7/lib/JumpScale/baselib/http_client/HttpClient.py(line 177) (function _http_request)
  ========== STACKFRAME==========
                    request.add_header(key, value)
            if not method:
                method = 'POST' if data else 'GET'
            request.get_method = lambda: method
            try:
                resp = urllib2.urlopen(request)
            except Exception as e:
                print(e)
-->             raise HTTPError(e, url)
            
            #if resp.code in STATUS_AUTH_REQ: raise AuthorizationError('Not logged in or token expired')
            if resp.code not in (STATUS_OK):
                raise Exception('unexpected HTTP response status %s: %s'%resp.code, resp)
            return resp
        
    class HttpClient(object):
  ============ LOCALS============
    data : {"cloudspaceId":6,"protocol":"tcp","localPort":22,"machineId":4280,"publicIp":"185.203.91.16\/24","publicPort":5601}
    e : HTTP Error 404: Not Found
    headers : {'content-type': 'application/json'}
    key : content-type
    kwargs : {}
    method : POST
    request : <urllib2.Request instance at 0x7fdcd028c5a8>
    self : <JumpScale.baselib.http_client.HttpClient.Connection object at 0x7fdcda1c4410>
    url : https://10.220.2.1:443/restmachine/cloudapi/portforwarding/create?authkey=djtXHaPBi6HH
    value : application/json

#### Installation information
JumpScale

Core: branch: 7.2.1 (31d7d25) 11/23/2017, 3:40:57 PM
Portal: branch: 7.2.1 (e66ed31) 11/21/2017, 6:03:41 PM
OpenvCloud

Core: branch: 2.2.1 (9a0b00e) 11/25/2017, 12:51:59 PM
G8VDC: branch: 2.2.1 (06d3299) 10/23/2017, 11:02:08 AM
Selfhealing: branch: 2.2.1 (d52f456) 11/23/2017, 6:22:51 PM
OpenvStorage mr4

openvstorage-backend-core: 1.9.1-1
openvstorage-health-check: 3.3.5-1
alba: 1.3.25
openvstorage-webapps: 2.9.5-1
openvstorage-backend-webapps: 1.9.1-1
openvstorage-core: 2.9.5-1
openvstorage-hc: 1.9.1-1
openvstorage: 2.9.5-1
openvstorage-backend: 1.9.1-1
openvstorage-sdm: 1.9.0-1

**Comment by grimpy** [comment]
See https://github.com/0-complexity/openvcloud/pull/1031

**Comment by FastGeert** [comment]
With the Gateway we'll need to do that anyway
