### ISSUE TITLE
Security/privacy issue: you can search usernames in the OVC End User Portal

### ISSUE THREAD

**Issue by yveskerwyn** [0-complexity/openvcloud#1027]
![screen shot 2017-12-01 at 11 15 31](https://user-images.githubusercontent.com/13795109/33478369-5c261736-d689-11e7-95e7-dd6c7000f770.png)

![screen shot 2017-12-01 at 11 15 21](https://user-images.githubusercontent.com/13795109/33478379-6114d480-d689-11e7-965a-e1dfd04a6c0c.png)

**Comment by grimpy** [comment]
feature not a bug

**Comment by dinosn** [comment]
Close it please the user is already admin to reach to that page

**Comment by yveskerwyn** [comment]
Disagree

I just tested this feature, I logged in with user yvesk@itsyouonline, which is a normal user (only member of the user group) with no rights on the account "Account of Yves", only admin right on the cloud space "test-space" and as such I can indeed manage the access rights of this cloud space:

![screen shot 2017-12-03 at 11 19 32](https://user-images.githubusercontent.com/13795109/33524346-fd9b9d96-d81b-11e7-8945-812fd8343cec.png)

This allows me as a regular user to see to search for all user in the database, and I don't think that is a good idea, thoughindeed very convenient.

Even if you are an admin user to the whosystem (admin group membership), or simple as a normal user have admin level control on the level of an account, we should never allow anybody to search for all users. To me this is serious security/privacy issue.

**Comment by dinosn** [comment]
Yves, again I fail to see the issue here. 

   You get a list on the users that have access on the specific portal. 

The same you can see when you go and check all vms on the cloudspace. 

Why this is an issue ? How you can connect this information and what can you further do with this info ?

**Comment by yveskerwyn** [comment]
There is no issue as long as the End User Portal is used by one single customer/organization, but in many cases we are inviting people to use the End User Portal that belong to completely unrelated companies/organizations.

The real issue is that the End User Portal is not designed for multi-tenancy I guess.

**Comment by FastGeert** [comment]
Need to decide if we keep the end user portal.

**Comment by FastGeert** [comment]
Decided with @wvandebroeck . Just remove search, and make the field a normal input field.

**Comment by ahmedelsayed-93** [comment]
verified 

### software version

JumpScale

    Core: branch: master (278c4fb) 2/21/2018, 1:43:54 PM
    Portal: branch: master (29a3df6) 2/21/2018, 3:52:30 PM

OpenvCloud

    Core: branch: master (81debe4) 2/22/2018, 2:27:21 PM
    G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
    Selfhealing: branch: master (ac36bf5) 2/21/2018, 3:09:31 PM

OpenvStorage be-g8-4

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1
