### ISSUE TITLE
Remove drop cache script from healthchecks

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1042]
Hi, 
  This is a request for better improvement on the overall system performance. 

We need to remove the cache_drop.py healtcheck script as it's causing more issues than it resolves.

As we mentioned in numerous times, the memory is used and stay cached because an application requires it. 

Forcing a memory cache drop every now and then is not resolving issues rather than forcing the application that is using that memory to speed up its' operations to reclaim it slowly.

**Comment by FastGeert** [comment]
Just delete the self healing script from the repo.

**Comment by dinosn** [comment]
Detailed description

OVS asked us to execute a cache drop every 2 hours / which was automated in a jumpscript.

However from EE onwards this is not needed anymore.

So we need to make sure that it is not executed on environments that have OVS EE.

**Comment by ashraffouda** [comment]
How can I tell if this env has OVS EE or not?

**Comment by ahmedelsayed-93** [comment]
### software versions
JumpScale

    Core: branch: master (09b7fe8) 12/4/2017, 11:11:25 PM
    Portal: branch: master (c997bb1) 11/28/2017, 5:32:06 PM

OpenvCloud

    Core: branch: master (8721293) 12/6/2017, 10:31:21 AM
    G8VDC: branch: master (695c7c0) 12/5/2017, 1:41:03 PM
    Selfhealing: branch: master (071b18a) 12/6/2017, 9:02:36 AM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1
