### ISSUE TITLE
Remove drop_cache.py from install of OVC if the environment has OVS enterprise edition

### ISSUE THREAD

**Issue by hofkensj** [0-complexity/openvcloud#1045]
#### Detailed description

OVS asked us to execute a cache drop every 2 hours / which was automated in a jumpscript.

However from EE onwards this is not needed anymore.

So we need to make sure that it is not executed on environments that have OVS EE.

**Comment by dinosn** [comment]
Duplicated on https://github.com/0-complexity/openvcloud/issues/1042 , i added the additional comments
