### ISSUE TITLE
Need api to get external network information 

### ISSUE THREAD

**Issue by ahmedelsayed-93** [0-complexity/openvcloud#1048]

**Comment by FastGeert** [comment]
@ahmedelsayed-93 please invest a bit more time in this ticket. Describe which API's you are lacking, and the use case for which you need it.

**Comment by ahmedelsayed-93** [comment]
currently we can add external network and delete it using cloudbroker apis but we can't get some information about a specific external network such as its gatway, start ip, end ip or vlan tag.
we need this api to be able to cover some test scenarios 
for example https://github.com/0-complexity/openvcloud/issues/959
