### ISSUE TITLE
Multiple issues on healthchecks performed under test deployment

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1050]
We have several warnings from the test deployment case where the ROS are prevented to ping outside and generating a warning on the panel. 

Cases are followed from the tickets under 
https://docs.greenitglobe.com/gig/proj_gig_sweden/issues/28 
https://docs.greenitglobe.com/gig/org_support/issues/474

**Comment by FastGeert** [comment]
Probably already solved with the hotfix as implemented by @fastgeert in https://github.com/0-complexity/openvcloud/commit/ca8055b76ae3e0368f22700bc138c5e960a8fe70
