### ISSUE TITLE
Too many healthchecks from the Portal impacts Redis

### ISSUE THREAD

**Issue by abdulgig** [0-complexity/openvcloud#1051]
#### Detailed description

From the monitoring perspective, we have noticed that too many healthchecks performed also are creating an impact on redis.

It starts building up and eventually goes out. This is purely an observation and the moment and we would like you to verify.

#### Steps to reproduce

This happens over time by running the healthchecks constantly from the portal. No other specific steps to reproduce the issue.

#### Relevant stacktraces

| Please make sure to include the stacktrace found under /grid/error conditions in the portal.
Adding a link alone is not sufficient as it might have expired by the time the issue is looked at.

#### Installation information

JumpScale

    Core: branch: production (18aa13f) 11/27/2017, 6:12:12 PM
    Portal: branch: production (c997bb1) 11/28/2017, 7:32:06 PM

OpenvCloud

    Core: branch: production (d27957b) 11/29/2017, 7:28:52 PM
    G8VDC: branch: production (ea6a073) 11/27/2017, 1:11:44 PM
    Selfhealing: branch: production (5c1b4ae) 11/29/2017, 2:59:47 PM

OpenvStorage mr4

    openvstorage-backend-core: 1.9.1-1
    openvstorage-health-check: 3.3.5-1
    alba: 1.3.25
    openvstorage-webapps: 2.9.5-1
    openvstorage-backend-webapps: 1.9.1-1
    openvstorage-core: 2.9.5-1
    openvstorage-hc: 1.9.1-1
    openvstorage: 2.9.5-1
    openvstorage-backend: 1.9.1-1
    openvstorage-sdm: 1.9.0-1

**Comment by FastGeert** [comment]
This bug is resolved in 2.2.3 via #1009
