### ISSUE TITLE
The vms comes back and goes out 

### ISSUE THREAD

**Issue by john-kheir** [0-complexity/openvcloud#1061]
#### Detailed description
This issue happened a lot on be-g8-3 (at least 5 times)
we create machine then from time to time we can't connect to it then suddenly it is back.
Don't have any explanation why it is happening or any ECO

#### Installation information

JumpScale

    Core: branch: master (09b7fe8) 12/4/2017, 11:11:25 PM
    Portal: branch: master (c997bb1) 11/28/2017, 5:32:06 PM

OpenvCloud

    Core: branch: master (6b32334) 12/6/2017, 1:28:48 PM
    G8VDC: branch: master (695c7c0) 12/5/2017, 1:41:03 PM
    Selfhealing: branch: master (7ba180f) 12/6/2017, 12:06:08 PM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1

**Comment by dinosn** [comment]
Hi John can you please share some more info, what do you mean you lose it ? It doesn't respond on ping / connection and it's back after a while ?

**Comment by john-kheir** [comment]
Simply I just can't ssh to it and even when i'm inside it, the VM just hang and i can't execute commands.
and after a min or 2 mins. i can normally ssh to it .. or if i was inside a session, it works suddenly and i can execute commands back.

**Comment by john-kheir** [comment]
Sometimes the vm wasn't reachable from the end user portal console

**Comment by PeterNashaat** [comment]
- The ROS lose the connection, and it gets back after doing ping from the ROS itself
- issue is in openv-switch :- 
  - the flows drop arp requests into the public bridge

**Comment by ashraffouda** [comment]
talked to Jan, he applied the fix for it 
which is 
```
ovs-ofctl add-flow public table=0,priority=9000,arp,actions=normal
```

**Comment by ahmedelsayed-93** [comment]
issue still exist in be-g8-3
https://be-g8-3.demo.greenitglobe.com/CBGrid/Virtual%20Machine?id=1067

**Comment by delandtj** [comment]
should be OK now, verify and close plz
