### ISSUE TITLE
Change Alerta's notification elements.

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1068]
At the moment and based on the initial plan Alerta is sending us all the ECOs. 

 The information provided in the ECO are not descriptive on the issue and they don't provide clear indication of the criticality of each case. 

We would like to change the logic of alerta and create the following:

1. Alerta will not send any ECO.
2. Alerta will send events. Events that are causing a change on the portal status, eg. What cause the portal at this moment to change from Green to Orange , or from Orange to Red or from Green to red.
3. Alerta will provide the same information on the event that caused the change as the info is displayed on the panel, eg WARNING - Orphanage - Deleting disk xxx 
4. There won't be any way to 'mute' an event from coming.
5. Events will not be repeated, a state on the system changes once, notification will be based on that change.

**Comment by ashraffouda** [comment]
discussed with NIcolas and Jo, 
1- we found that if all envs r updated u will only receive ecos from health check only > even if alerta shows all as `Error Condition` type
2- found the heart beat check is done outside selfhealing 

other than that ecos  should be sent  as expected 
solutions 
1- created heartbeat health check to be sent to alerta 
2- removing the type error condition and adding healthcheck cat

**Comment by Dinaamagdy** [comment]
## Software version 
```
JumpScale
Core: branch: master (444fc87) 12/13/2017, 3:08:41 PM
Portal: branch: master (30066b4) 12/13/2017, 10:39:40 PM
OpenvCloud
Core: branch: master (866b24b) 12/14/2017, 2:44:54 PM
G8VDC: branch: master (ea4dc79) 12/14/2017, 9:33:18 AM
Selfhealing: branch: master (fd97c9c) 12/13/2017, 3:08:22 PM
```
