### ISSUE TITLE
The account resources are not correct 

### ISSUE THREAD

**Issue by john-kheir** [0-complexity/openvcloud#1073]
#### Detailed description
1- Create account.
2- Create cloud space cs1_id=408 with 1 vm.
3- Create cloud space cs2_id=409 with 2 vms.
![cs1](https://user-images.githubusercontent.com/15011431/33823833-1978ef06-de65-11e7-982f-90990659d8f5.png)
4- Download the account resources file.

## Actual Result 

- Both cloud spaces in the xls file were having an extra vm each. 
![csresults](https://user-images.githubusercontent.com/15011431/33823879-45cb563e-de65-11e7-915c-a769cde236c8.png)

#### Installation information

JumpScale

    Core: branch: master (887849c) 12/6/2017, 8:43:49 PM
    Portal: branch: master (c997bb1) 11/28/2017, 5:32:06 PM

OpenvCloud

    Core: branch: rosfixes (df06f91) 12/6/2017, 9:25:07 PM
    G8VDC: branch: master (695c7c0) 12/5/2017, 1:41:03 PM
    Selfhealing: branch: master (7ba180f) 12/6/2017, 12:06:08 PM

OpenvStorage du-conv-2

    openvstorage-backend-core: 1.7.10.1-1
    openvstorage-health-check: 3.2.0-fargo.3-1
    alba: 1.3.23
    openvstorage-webapps: 2.7.10.1-1
    openvstorage-backend-webapps: 1.7.10.1-1
    openvstorage-core: 2.7.10.1-1
    openvstorage-hc: 1.7.10.1-1
    openvstorage: 2.7.10.1-1
    openvstorage-backend: 1.7.10.1-1
    openvstorage-sdm: 1.6.10.1-1

**Comment by grimpy** [comment]
If you used our example script to generate this excel sheet you probably wonna have a loo how it counts the amount of machines it includes the routeros as a machine
