### ISSUE TITLE
Change routeros migration script to detect duplicate IPS

### ISSUE THREAD

**Issue by grimpy** [0-complexity/openvcloud#1078]
Our 2.2.3 routeros migration script currently does not complain if a cloudspace has vms with duplicate ips.
We need to make sure the migration script reports this to the operator so he can fix this.

**Comment by Dinaamagdy** [comment]
## Steps 
- ssh to controller 
- then from js ( client =j.clients.osis.getNamespace('cloudbroker'))
-  vm = cl.vmachine.get(vm_id)
- set ip address with same ip address like another vm  in same cloudspace ``` vm.nics[0].ipAddress = '192.168.103.254' ```
- cl.vmachine.set(vm)
 - then from master run migeation script 
jspython /opt/code/github/0-complexity/openvcloud/scripts/updates/upgrader.py -v 2.2.3
## Issue 
-- running the script  should return error that there is duplicate ip , but 
- The Error should be more organized with url of Error condition 
- there is key error Error in the result  error as shown : 
![image](https://user-images.githubusercontent.com/24386802/34078135-c3d681e6-e31c-11e7-9f1b-49e6cf9497e0.png)

## Software version 
```
JumpScale
Core: branch: master (444fc87) 12/13/2017, 3:08:41 PM
Portal: branch: master (30066b4) 12/13/2017, 10:39:40 PM
OpenvCloud
Core: branch: master (4827925) 12/17/2017, 8:34:16 AM
G8VDC: branch: master (ea4dc79) 12/14/2017, 9:33:18 AM
Selfhealing: branch: master (a2b9f7f) 12/14/2017, 7:58:45 PM
```

**Comment by Dinaamagdy** [comment]
- when I run the script again and we still have same ip for two vms , no errors appear now 
## Software Version
```
JumpScale
Core: branch: master (444fc87) 12/13/2017, 3:08:41 PM
Portal: branch: master (30066b4) 12/13/2017, 10:39:40 PM
OpenvCloud
Core: branch: master (ef497bb) 12/17/2017, 2:01:44 PM
G8VDC: branch: master (ea4dc79) 12/14/2017, 9:33:18 AM
Selfhealing: branch: master (d0a4bc5) 12/17/2017, 11:25:08 AM
```

**Comment by grimpy** [comment]
Script has been changed to show error now

**Comment by Dinaamagdy** [comment]
## Software Version 
```
JumpScale
Core: branch: master (a166a21) 12/17/2017, 2:27:29 PM
Portal: branch: master (30066b4) 12/13/2017, 10:39:40 PM
OpenvCloud
Core: branch: master (aa86fa4) 12/18/2017, 8:52:52 AM
G8VDC: branch: master (ea4dc79) 12/14/2017, 9:33:18 AM
Selfhealing: branch: master (d0a4bc5) 12/17/2017, 11:25:08 AM
```
