### ISSUE TITLE
ovs_healthcheck_long.py is not working properly 

### ISSUE THREAD

**Issue by hossnys** [0-complexity/openvcloud#1079]
#### Detailed description
we found that this script ovs_healthcheck_long.py when running it's through an error on portal saying that the log file /var/log//ovs/storagerouterclient.log is larger than 500 MB!  
this may be caused by an error within the script or some miss-arranging in time between this script and log truncate script. 

- environment version: production
- portal verison: production
- ovc version: production

**Comment by FastGeert** [comment]
@hossnys 
1. This is not a support ticket system. Github issues are about bugs and feature requests. So do not mension environment details in this public channel.
2. Please clarify the issue. I cannot understand what is actually going wrong from your explanation.

**Comment by hossnys** [comment]
the error with this healthcheck was discussed with Jo And he got where is the error , it was in the cronjob that made run it wrong way , you can get more details from Jo.

**Comment by FastGeert** [comment]
@grimpy Still don't get it

**Comment by grimpy** [comment]
What me and Samir discussed was related to an issue in the interval (the cron) which caused to the ovs_long_healthcheck to run 4am and 4:30am instead of only at 4am
