### ISSUE TITLE
can't export vm 

### ISSUE THREAD

**Issue by ahmedelsayed-93** [0-complexity/openvcloud#1088]
### steps
- create cloudspcae 
- create vm1 and run owncloud on it  
```
docker run -d --name owncloud -p 80:80 -e OWNCLOUD_ADMIN_USERNAM=admin -e OWNCLOUD_ADMIN_PASSWORD=123456 owncloud
```
- create vm 2
- try to export vm2 using the export ovf api

### result 
no files appeared in owncloud path except the readme.txt file
![image](https://user-images.githubusercontent.com/24386820/34001010-89ec020c-e0f7-11e7-901a-3b2525f6b7b2.png)

used cloudspace 
https://be-g8-3.demo.greenitglobe.com/CBGrid/cloud%20space?id=9

### software versions 
JumpScale

    Core: branch: master (444fc87) 12/13/2017, 3:08:41 PM
    Portal: branch: master (30066b4) 12/13/2017, 10:39:40 PM

OpenvCloud

    Core: branch: master (df5e723) 12/14/2017, 4:49:20 PM
    G8VDC: branch: master (ea4dc79) 12/14/2017, 9:33:18 AM
    Selfhealing: branch: master (fd97c9c) 12/13/2017, 3:08:22 PM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1

**Comment by FastGeert** [comment]
How long did you wait?
Did you get an email that said the export failed.

**Comment by ashraffouda** [comment]
I tested this on be-g8-3 and found out that 
1- this check never success https://github.com/0-complexity/openvcloud/blob/master/libs/agent-scripts/libvirt/clonedisks.py#L44
even if i did it manually 
2- 
```
x = ovscl.post('/vdisks/81eaeff9-834d-47a3-a2b3-bf9f9d9250fc/create_snapshot', params={'name':'dasa', 'timestamp': 1513526658, 'sticky':True})
s, r = ovs.wait_for_task(taskguid)
In [36]: r
Out[36]: u'20c1fa51-b4b9-4ab7-b8d6-f904d47bf379'
 {u'guid': u'20c1fa51-b4b9-4ab7-b8d6-f904d47bf379',
  u'in_backend': True,
  u'is_automatic': False,
  u'is_consistent': False,
  u'is_sticky': True,
  u'label': u'dasa',
  u'stored': 0,
  u'timestamp': u'1513533800'}]
from this the timestamp value is never the same for the same guid which is `weird` 
btw `there always an alba error in error conditions every time i try to export a machine 
anyone has input here?

**Comment by ahmedelsayed-93** [comment]
### software version
JumpScale

    Core: branch: master (0a1fa90) 4/27/2017, 12:57:54 PM
    Portal: branch: master (30066b4) 12/13/2017, 10:39:40 PM

OpenvCloud

    Core: branch: master (63c11d3) 12/18/2017, 2:21:26 PM
    G8VDC: branch: master (ea4dc79) 12/14/2017, 9:33:18 AM
    Selfhealing: branch: master (d0a4bc5) 12/17/2017, 11:25:08 AM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1
