### ISSUE TITLE
don't count on timestamp of snapshots

### ISSUE THREAD

**Issue by ashraffouda** [0-complexity/openvcloud#1115]
#### Detailed description
what we do now is we depend on the timestamp that we pass to ovs `/disks/{disk_guid}/create_snapshot` endpoint which seems it is not a thing that ovs uses anyway because you often will get a different timestamp if u listed the snapshots of this disk
instead we can count on the snapshot `name` or `guid`

**Comment by ahmedelsayed-93** [comment]
### software version
JumpScale

    Core: branch: master (9870155) 12/20/2017, 10:53:52 AM
    Portal: branch: master (9a65ce8) 12/19/2017, 10:56:59 AM

OpenvCloud

    Core: branch: master (17aba11) 12/21/2017, 2:28:40 PM
    G8VDC: branch: master (2f5e95f) 12/19/2017, 8:37:17 AM
    Selfhealing: branch: master (fb6f039) 12/21/2017, 1:33:27 PM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1
