### ISSUE TITLE
Mem value is wrong 

### ISSUE THREAD

**Issue by john-kheir** [0-complexity/openvcloud#1134]
1-" htop" command give a different value from portal health check .. seems health check average memory is always 100%
![err1](https://user-images.githubusercontent.com/15011431/34258241-c387e26a-e665-11e7-8d2d-c323a11b5b6f.png)
![err2](https://user-images.githubusercontent.com/15011431/34258243-c55df318-e665-11e7-8200-68c78ac94700.png)

#### Installation information

JumpScale

    Core: branch: master (9870155) 12/20/2017, 10:53:52 AM
    Portal: branch: master (9a65ce8) 12/19/2017, 10:56:59 AM

OpenvCloud

    Core: branch: master (17aba11) 12/21/2017, 2:28:40 PM
    G8VDC: branch: master (2f5e95f) 12/19/2017, 8:37:17 AM
    Selfhealing: branch: master (fb6f039) 12/21/2017, 1:33:27 PM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1

**Comment by ashraffouda** [comment]
FIxed check comments here https://github.com/0-complexity/openvcloud/issues/842

**Comment by john-kheir** [comment]
https://github.com/0-complexity/selfhealing/commit/ddb3754fcb12b6e0ac396548c4659bfa1e6d07d7
https://github.com/0-complexity/selfhealing/commit/2ee8c28bb1df3deb6870080fd90a1b0aba8e0305

**Comment by ashraffouda** [comment]
@john-kheir  isn't this fixed by the above commits?

**Comment by ashraffouda** [comment]
values seems correct
