### ISSUE TITLE
Hanging of portal page when moving an ROS from portal 

### ISSUE THREAD

**Issue by Pishoy** [0-complexity/openvcloud#1141]
#### Detailed description
we can not do any action on ROS when it's node down also by using the manual moving API can not do that the page give me nginx 504 Gateway Time-out

#### Steps to reproduce
1- stop cpu node that hosted ROS
2- do any action on ROS

**Comment by Pishoy** [comment]
https://docs.greenitglobe.com/gig/proj_russia_digital_energy/issues/394

**Comment by ahmedelsayed-93** [comment]
### software versions 
JumpScale

    Core: branch: master (9870155) 12/20/2017, 10:53:52 AM
    Portal: branch: master (9a65ce8) 12/19/2017, 10:56:59 AM

OpenvCloud

    Core: branch: master (c432ffd) 12/24/2017, 9:37:52 PM
    G8VDC: branch: master (fd49072) 12/24/2017, 7:46:34 PM
    Selfhealing: branch: master (748f20f) 12/24/2017, 9:41:56 AM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1
