### ISSUE TITLE
Add VM name to the email message that is sent when exporting/importing completes.

### ISSUE THREAD

**Issue by Pishoy** [0-complexity/openvcloud#1146]
#### Detailed description

Add VM name to the email message that is sent when exporting/importing completes.
Here is the template path openvcloud/apps/cloudbroker/templates/cloudbroker/email/users/export_completion.html

#### Steps to reproduce

1- export a vm 
2- got message does not have the vm name 

OVC 2.2.3

**Comment by ahmedelsayed-93** [comment]
JumpScale

Core: branch: master (46e17c5) 2/1/2018, 2:18:29 PM
Portal: branch: master (24c3192) 1/31/2018, 8:39:01 AM
OpenvCloud

Core: branch: master (a14a237) 2/4/2018, 9:14:43 AM
G8VDC: branch: master (69544db) 1/31/2018, 11:27:40 AM
Selfhealing: branch: master (ca34b96) 2/1/2018, 12:53:49 PM
OpenvStorage be-g8-4

openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.0-1
openvstorage-webapps: 2.9.9-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.9-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.17
openvstorage: 2.9.9-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.1-1
openvstorage-sdm: 1.9.1-1
