### ISSUE TITLE
Editing port forwards form end user portal is not working properly 

### ISSUE THREAD

**Issue by hossnys** [0-complexity/openvcloud#1149]
#### Detailed description
when editing port forward from end user portal it's supposed to delete the old port forward and create new updated one but both of them old and new one is still there. 

#### Steps to reproduce
create port forward for a vm from end user portal
try to edit port forward you will see both of them still there.

#### Installation information
- portal version :  branch: production (c997bb1) 11/28/2017, 5:32:06 PM
- ovc version : production (d27957b) 11/29/2017, 5:28:52 PM

**Comment by grimpy** [comment]
https://docs.greenitglobe.com/gig/proj_russia_digital_energy/issues/396

**Comment by ahmedelsayed-93** [comment]
verified on be-g8-3
### software versions 
JumpScale

Core: branch: staging (9870155) 12/20/2017, 10:53:52 AM
Portal: branch: staging (9a65ce8) 12/19/2017, 10:56:59 AM
OpenvCloud

Core: branch: staging (df4475e) 12/28/2017, 12:23:14 PM
G8VDC: branch: staging (989668b) 12/27/2017, 4:19:04 PM
Selfhealing: branch: staging (748f20f) 12/24/2017, 9:41:56 AM
OpenvStorage be-g8-3

openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.0-1
openvstorage-webapps: 2.9.9-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.9-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.17
openvstorage: 2.9.9-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.1-1
openvstorage-sdm: 1.9.1-1
