### ISSUE TITLE
Resize with ubuntu 14.04 doesn't work correctly 

### ISSUE THREAD

**Issue by Dinaamagdy** [0-complexity/openvcloud#1151]
## Steps 
- Resize the  vm with 
```
8 vCPUs, 16384 Memory
```
## Issue 
When you check inside vm , you will find there is a big difference in memory, and wrong number of CPUs , almost 5.

## Software Version 
```
JumpScale

Core: branch: master (9870155) 12/20/2017, 10:53:52 AM
Portal: branch: master (9a65ce8) 12/19/2017, 10:56:59 AM
OpenvCloud

Core: branch: master (c432ffd) 12/24/2017, 9:37:52 PM
G8VDC: branch: master (fd49072) 12/24/2017, 7:46:34 PM
Selfhealing: branch: master (748f20f) 12/24/2017, 9:41:56 AM
```

**Comment by FastGeert** [comment]
Need to update drivers (virtio) in image

**Comment by delandtj** [comment]
It all depends... an 14.04 deafults to a 3.X.Y linux kernel, we can envision to upgrade the kernel itself and create a new image from it ?

**Comment by FastGeert** [comment]
Ok, but not an issue for here. Should be in docs.
