### ISSUE TITLE
osisServerStart.py and controller.py eat server ram

### ISSUE THREAD

**Issue by mohamedgalal99** [0-complexity/openvcloud#1152]
#### Detailed description
we installed ovc version 2.2.4 on b17, after while portal keep loading until it fail
we notice that that both of this services are eating ram to quick until nothing else can be served and portal dead

![as](https://user-images.githubusercontent.com/8679870/34360017-9cb2474e-ea65-11e7-97ef-144cdb92d8e6.png)

#### Relevant stacktraces

| Please make sure to include the stacktrace found under /grid/error conditions in the portal.
Adding a link alone is not sufficient as it might have expired by the time the issue is looked at.

#### Installation information

- environment version:
- operating system:
- portal verison
- ovc 2.2.4

**Comment by ahmedelsayed-93** [comment]
need to reinstall an environment to validate this issue

**Comment by ahmedelsayed-93** [comment]
### software version
JumpScale

    Core: branch: staging (70d4588) 1/2/2018, 10:27:09 AM
    Portal: branch: staging (9a65ce8) 12/19/2017, 10:56:59 AM

OpenvCloud

    Core: branch: staging (e52bd87) 12/31/2017, 10:37:08 AM
    G8VDC: branch: staging (989668b) 12/27/2017, 4:19:04 PM
    Selfhealing: branch: staging (748f20f) 12/24/2017, 9:41:56 AM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1
