### ISSUE TITLE
Keep audit records for more than 5 days

### ISSUE THREAD

**Issue by FastGeert** [0-complexity/openvcloud#1159]
Currently audits records older than 5 days get cleared automatically. This is not enough.

Need to think about a good number @wvandebroeck

**Comment by wvandebroeck** [comment]
what capacity is used to keep them and not delete them?

**Comment by wvandebroeck** [comment]
some retention according to regulations:

- The Health Insurance Portability and Accountability Act (HIPAA) - Affects healthcare industry. Logs should be retained up to 6 years.
- Sarbanes Oxley, also provides a base timeline of one year for event retention. Again, though not
technology directed, actors subject to the law are required to provide annual reports, and both
annual and one year appear repeatedly in the law. From one related section of the law,
Sarbanes-Oxley Act of 2002 (H.R. 3763) 107th Congress (2001-2002) SEC. 102.
REGISTRATION WITH THE BOARD. (e) PUBLIC AVAILABILITY. ³R
- more info https://www.sans.org/reading-room/whitepapers/auditing/successful-siem-log-management-strategies-audit-compliance-33528 

as shown 5 days is not enough...

**Comment by FastGeert** [comment]
For now decided with @wvandebroeck, we set it to 30 days.

**Comment by john-kheir** [comment]
https://github.com/jumpscale7/jumpscale_core7/commit/ffcffadb453d573271982d5125614583598f8a86
