### ISSUE TITLE
Need to record audit record when a vm gets shutdown from inside the OS

### ISSUE THREAD

**Issue by FastGeert** [0-complexity/openvcloud#1160]
To be able to see what specific actions were done on a vm, we also need to record a shutdown action from inside the vm.

**Comment by grimpy** [comment]
@FastGeert I suggest that when our libvirtlistener deamon detects such an events it reports an audit trail for it

**Comment by grimpy** [comment]
update-ays didn't restart the libvirtlistener process on the cpu nodes which had the updated code. I've fixed this please run update-ays --self first followed by regular update
