### ISSUE TITLE
Harden XML Parsing inside OVC

### ISSUE THREAD

**Issue by riaandn1** [0-complexity/openvcloud#1162]
#### Detailed description

When an unexpected entry is found during the parsing of the XML file, the OVC API is unable to deal with the VM to stop or start it. Virsh is then required to stop and start the VM.

#### Installation information
- ovc version 2.2.4

**Comment by grimpy** [comment]
our machine 142
```
    <interface type='bridge'>
      <mac address='52:54:00:00:0e:b0'/>
      <source bridge='space_013a'/>
      <virtualport type='openvswitch'>
        <parameters interfaceid='b05d948d-2249-45e9-b0ed-fab1af496e12'/>
      </virtualport>
      <bandwidth>
        <inbound average='134218' peak='134218' burst='134218'/>
        <outbound average='134218' peak='134218' burst='134218'/>
      </bandwidth>
      <target dev='vm-4893-013a'/>
      <model type='virtio'/>
      <alias name='net0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
    </interface>
```
vs any not migrated vm
```
   <interface type='bridge'>
      <mac address='52:54:00:00:29:4a'/>
      <source network='space_00ce' bridge='space_00ce'/>
      <virtualport type='openvswitch'>
        <parameters interfaceid='3746a5f5-7a77-4bd9-b6eb-3280356254fe'/>
      </virtualport>
      <bandwidth>
        <inbound average='134218' peak='134218' burst='134218'/>
        <outbound average='134218' peak='134218' burst='134218'/>
      </bandwidth>
      <target dev='vm-5387-00ce'/>
      <model type='virtio'/>
      <alias name='net0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
    </interface>
```

This causes a crash inside libvirt_driver.py when parsing xml in method `_from_xml_to_node`

**Comment by grimpy** [comment]
```
        for nic in dom.findall('devices/interface'):
            mac = None
            macelement = nic.find('mac')
            source = nic.find('source')
            if macelement is not None:
                mac = macelement.attrib['address']
            target = nic.find('target').attrib['dev']
            bridgename = source.attrib['network']
            if bridgename.startswith(('ext-', 'public')):
                bridgetype = 'PUBLIC'
            else:
                bridgetype = 'bridge'
            ifaces.append(NetworkInterface(mac=mac, target=target, type=bridgetype, bridgename=bridgename))
```

crahs happens with keyerror network

**Comment by ahmedelsayed-93** [comment]
### software version
JumpScale

    Core: branch: staging (70d4588) 1/2/2018, 10:27:09 AM
    Portal: branch: staging (9a65ce8) 12/19/2017, 10:56:59 AM

OpenvCloud

    Core: branch: staging (e52bd87) 12/31/2017, 10:37:08 AM
    G8VDC: branch: staging (989668b) 12/27/2017, 4:19:04 PM
    Selfhealing: branch: staging (748f20f) 12/24/2017, 9:41:56 AM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1
