### ISSUE TITLE
Cloudspace migration between environments

### ISSUE THREAD

**Issue by FastGeert** [0-complexity/openvcloud#1163]
Requirements:
- Two modes:
  - Online: needs low latency high performance network between the two environments (needs to be checked by the source platform to the target platform)
  - Offline: reuses export / import function
- operator action
- creates identical network setup on other side 
  - same public ip (optional)
  - same portforwards
  - same private ip's of vms
  - same mac's of vms
  - ...
- creates identical vm's on other side
  - same amount of mem
  - same amount of cpu's
  - same amount of disks with same size
  - ...
- account on target environment must have enough resources to adopt the entire cloudspace

**Comment by grimpy** [comment]
Spec is optimistic...
Needs further discussion, we can't guarantee same mac address of vm at the other side.
Public IP is highly dependant on how the network is connected.
