### ISSUE TITLE
Feature request: Remove Ubuntu 16.04 x64 image as dependency for internal tasks

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1172]
In some cases, the client might not want to have Ubuntu 16.04 x64 , as image listed in the system, nor as option given to the clients for deployment. 

 It will be best if we do not have a dependency on the ubuntu image and create an internal image, always available for selected functions as the test deployment and other internal tests.

UK removed the image ( disabled it ) as it's not needed for it's client and they don't want to show it as selection, the result was to have multiple errors on the system due to this image unavailability.

**Comment by FastGeert** [comment]
They can just assign the image to the deployment test account only if they want to hide away from other customers.
