### ISSUE TITLE
Restrict access to 0-access group

### ISSUE THREAD

**Issue by riaandn1** [0-complexity/openvcloud#1176]
Please only allow users assigned explicitly in IYO to the group 0-access to access SSH. Please see the [specification](https://docs.google.com/document/d/1ui_sB_t7RnbvLeqAu8e5DWAGp--uLBUM8uUoUPMjwGk/edit#).

**Comment by ahmedelsayed-93** [comment]
i got this errors
![image](https://user-images.githubusercontent.com/24386820/35795691-9e3bdefa-0a62-11e8-9e2b-f9a41040441c.png)

![image](https://user-images.githubusercontent.com/24386820/35795704-aafd44c6-0a62-11e8-89c1-6c4269e2239c.png)

![image](https://user-images.githubusercontent.com/24386820/35795725-bb2e5f2e-0a62-11e8-88b7-fe9a52637d6b.png)

### Software versions 
JumpScale
```
Core: branch: master (46e17c5) 2/1/2018, 2:18:29 PM
Portal: branch: master (24c3192) 1/31/2018, 8:39:01 AM
```
OpenvCloud
```
Core: branch: master (a14a237) 2/4/2018, 9:14:43 AM
G8VDC: branch: master (69544db) 1/31/2018, 11:27:40 AM
Selfhealing: branch: master (ca34b96) 2/1/2018, 12:53:49 PM
```
OpenvStorage be-g8-4
```
openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.0-1
openvstorage-webapps: 2.9.9-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.9-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.17
openvstorage: 2.9.9-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.1-1
openvstorage-sdm: 1.9.1-1
```

**Comment by ahmedelsayed-93** [comment]
issue still exists 

### software version 
JumpScale

    Core: branch: master (278c4fb) 2/21/2018, 1:43:54 PM
    Portal: branch: master (29a3df6) 2/21/2018, 3:52:30 PM

OpenvCloud

    Core: branch: master (81debe4) 2/22/2018, 2:27:21 PM
    G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
    Selfhealing: branch: master (ac36bf5) 2/21/2018, 3:09:31 PM

OpenvStorage be-g8-4

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1

**Comment by ahmedelsayed-93** [comment]
issue still exists

![image](https://user-images.githubusercontent.com/24386820/36846500-93a71720-1d63-11e8-81d9-22cbf469d993.png)

> 0-access page is removed from the menu, but i can access it using this url https://be-g8-3.demo.greenitglobe.com/cbgrid/0-access

**Comment by ahmedelsayed-93** [comment]
https://github.com/0-complexity/openvcloud/issues/1396

### software version
JumpScale

    Core: branch: master (b9da61a) 2/28/2018, 5:23:43 PM
    Portal: branch: master (7f0063f) 3/1/2018, 1:01:22 PM

OpenvCloud

    Core: branch: master (f6ca6c2) 3/1/2018, 1:04:26 PM
    G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
    Selfhealing: branch: master (bdaf210) 2/28/2018, 8:46:33 AM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.12-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.12-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.26
    openvstorage: 2.9.12-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.2-1
    openvstorage-sdm: 1.9.1-1

**Comment by ahmedelsayed-93** [comment]
### steps to reproduce 
- sign in with itsyouonline account that is not a member in 0-access group.
- open 0-access page, and you will see macro errors
