### ISSUE TITLE
Auto push latest versions of OS images to G8's in the field

### ISSUE THREAD

**Issue by wvandebroeck** [0-complexity/openvcloud#1178]
**Motivation** 

Currently we have OS images in the field that are not up to date (updates drivers etc...).

**Terminologies and Concepts** 

Auto push up to date OS images to the G8's in the field.

**Goals** 

Provide OS images with the latest updates and drivers installed in an automated way.  Note that operations is responsible for image versioning and updates.

**Comment by delandtj** [comment]
git lfs anyone ?

**Comment by FastGeert** [comment]
See also https://github.com/0-complexity/openvcloud/issues/1212

**Comment by alichaddad** [comment]
This was achieved as following:
- The url used to import the image is saved in the image model as well as its last modified date
- A jumpscript runs once a day that checks the last modified date for each image on the specified url and if they are not the same it will import the image again
- If the import operation works, the old image will be moved to the recycle bin where it can't be used anymore and when it is no longer used by any machine it will be removed
