### ISSUE TITLE
Imported disks do not appear to have names

### ISSUE THREAD

**Issue by FastGeert** [0-complexity/openvcloud#1179]
#### Detailed description
![image](https://user-images.githubusercontent.com/15246294/34571718-81570ac8-f16f-11e7-8847-28682c9b6ac1.png)

#### Steps to reproduce
Import vm

#### Installation information

- ovc version: 2.2.3

**Comment by ahmedelsayed-93** [comment]
issue still exists 
![image](https://user-images.githubusercontent.com/24386820/36943970-6165f468-1f9b-11e8-8545-0727af1bd524.png)

imported vm in be-g8-3
https://be-g8-3.demo.greenitglobe.com/CBGrid/Virtual%20Machine?id=247

### software version
JumpScale

    Core: branch: master (0fdeaf3) 3/2/2018, 8:41:51 PM
    Portal: branch: master (3df0a29) 3/1/2018, 8:00:47 PM

OpenvCloud

    Core: branch: master (11f0302) 3/4/2018, 9:20:46 AM
    G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
    Selfhealing: branch: master (8f2a952) 3/1/2018, 5:40:22 PM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.12-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.12-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.26
    openvstorage: 2.9.12-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.2-1
    openvstorage-sdm: 1.9.1-1

**Comment by ahmedelsayed-93** [comment]
### software version 

JumpScale

    Core: branch: master (0fdeaf3) 3/2/2018, 8:41:51 PM
    Portal: branch: master (3df0a29) 3/1/2018, 8:00:47 PM

OpenvCloud

    Core: branch: master (11f0302) 3/4/2018, 9:20:46 AM
    G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
    Selfhealing: branch: master (8f2a952) 3/1/2018, 5:40:22 PM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.12-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.12-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.26
    openvstorage: 2.9.12-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.2-1
    openvstorage-sdm: 1.9.1-1

**Comment by ahmedelsayed-93** [comment]
### steps to reproduce
- export vm
- import vm
- open the imported vm page, you will find all its disks without name

**Comment by islamTaha12** [comment]
Related TEST CASE:
https://github.com/0-complexity/G8_testing/issues/356
