### ISSUE TITLE
Do not replace custom customer logo with OVC upgrade

### ISSUE THREAD

**Issue by riaandn1** [0-complexity/openvcloud#1180]
#### Detailed description
GIG UK has mentioned that everytime we upgrade the OVC release that we ovewrite the custom company logo.

We shoudl retain the custom logos during upgrades.

#### Installation information
OVC release 2.2.3

**Comment by grimpy** [comment]
What is the procedure they use to place custom logos?

**Comment by dinosn** [comment]
They replace the contents on here, 
https://uk-ln-vt-1.g8.gigukportal.tech/g8vdc/.files/img/logo-colored.png

**Comment by grimpy** [comment]
Make option to upload custom logo store in db serve from there

**Comment by grimpy** [comment]
Option to upload logo can be found under /system/logo

**Comment by Dinaamagdy** [comment]
## Software Version 
```
JumpScale
Core: branch: master (278c4fb) 2/21/2018, 1:43:54 PM
Portal: branch: master (29a3df6) 2/21/2018, 3:52:30 PM
OpenvCloud
Core: branch: master (81debe4) 2/22/2018, 2:27:21 PM
G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
Selfhealing: branch: master (ac36bf5) 2/21/2018, 3:09:31 PM
```
