### ISSUE TITLE
Could not execute macro processchecks on page status overview

### ISSUE THREAD

**Issue by dimaandg** [0-complexity/openvcloud#1187]
Getting the following at RC when checking into health overview
```ERROR: Could not execute macro processchecks on page status overview```

Redis memory consumption was filling up fast because a lot of workers on cpu nodes

```
gig@uk-lon-dc-2-ctrl-01:~$  for i in {01..16}; do echo cpu-${i}; ssh root@cpu-${i} "ps auxww | grep worker | wc -l"; done
cpu-01
270
cpu-02
268
cpu-03
273
cpu-04
264
cpu-05
266
cpu-06
268
cpu-07
270
cpu-08
280
cpu-09
269
cpu-10
268
cpu-11
268
cpu-12
269
cpu-13
269
cpu-14
268
cpu-15
269
cpu-16
266
```

#### Installation information
JumpScale

    Core: branch: production (bdbb2fd) 12/19/2017, 12:14:55 PM
    Portal: branch: production (9a65ce8) 12/19/2017, 12:56:59 PM

OpenvCloud

    Core: branch: production (38993d9) 12/21/2017, 7:30:26 PM
    G8VDC: branch: production (2f5e95f) 12/19/2017, 10:37:17 AM
    Selfhealing: branch: production (0893c28) 12/19/2017, 1:34:51 PM

**Comment by FastGeert** [comment]
After an update of OVC we now had two times that agent worker processes kept rising on a certain machine.

**Comment by abdulrahmantkhalifa** [comment]
I believe this PR  https://github.com/0-complexity/selfhealing/pull/135 this issue
