### ISSUE TITLE
Add number of disks and vms to HC output

### ISSUE THREAD

**Issue by FastGeert** [0-complexity/openvcloud#1189]
![image](https://user-images.githubusercontent.com/15246294/34791450-4b544866-f645-11e7-8c78-00a35f54e702.png)

**Comment by dinosn** [comment]
This alarm should be properly configured, at the moment is showing up on uk, 

<img width="1440" alt="screen shot 2018-01-10 at 21 40 33" src="https://user-images.githubusercontent.com/3851678/34791954-2e97982c-f64f-11e7-89d5-7077d6ff8dd0.png">

On a system that in total has 27 VMs. 

Also on the /mnt/vmstore we have empty VM folders and orphaned bootdisks.

<img width="829" alt="screen shot 2018-01-10 at 21 38 31" src="https://user-images.githubusercontent.com/3851678/34791998-53c1cb04-f64f-11e7-875b-958f3c0b509a.png">

**Comment by FastGeert** [comment]
Not relevant any more
