### ISSUE TITLE
Need health check that monitors for flooding of ECO's

### ISSUE THREAD

**Issue by FastGeert** [0-complexity/openvcloud#1190]
We need HC that goes into warning if more than 5 ECO's are filed per hour, and into error if more than 10 ECO's are filed per hour.

**Comment by john-kheir** [comment]
The code is implemented .. but it is not there in the HC
![11111](https://user-images.githubusercontent.com/15011431/36848830-12050364-1d6b-11e8-88d0-8a9dc753674d.png)
