### ISSUE TITLE
VMs do not automatically move when Node in Error or Maintenance

### ISSUE THREAD

**Issue by abdulgig** [0-complexity/openvcloud#1195]
#### Detailed description

The VMs and ROS'es should be moved automatically when a Node is in state of Error or Maintenance. Unfortunately, this does not seem to happen. 

#### Steps to reproduce

1. Before the putting the node in maintenance, track the number of VMs and ROS'es on it.
2. Put the node into Maintenance from the portal.
3. The portal will display the message that all the VMs have been moved.
4. Log into the node and verify with "virsh list -all" or from the portal itself to check for running VMs and ROS'es

#### Installation information
This was tested on SE-GEN-1

JumpScale

    Core: branch: production (bdbb2fd) 12/19/2017, 12:14:55 PM
    Portal: branch: production (9a65ce8) 12/19/2017, 12:56:59 PM

OpenvCloud

    Core: branch: production (59df49c) 12/19/2017, 11:40:04 PM
    G8VDC: branch: production (2f5e95f) 12/19/2017, 10:37:17 AM
    Selfhealing: branch: production (0893c28) 12/19/2017, 1:34:51 PM

OpenvStorage se-gen-1

    openvstorage-backend-core: 1.9.1-1
    openvstorage-health-check: 3.3.5-1
    alba: 1.3.25
    openvstorage-test: 3.1.8-1
    openvstorage-webapps: 2.9.5-1
    openvstorage-core: 2.9.5-1
    openvstorage-backend-webapps: 1.9.1-1
    openvstorage-automation-lib: 0.2.6-1
    openvstorage-hc: 1.9.1-1
    openvstorage: 2.9.5-1
    openvstorage-backend: 1.9.1-1
    openvstorage-sdm: 1.9.0-1

**Comment by grimpy** [comment]
Before maintenacne
```
gig@cpu-01:~$ virsh list
 Id    Name                           State
----------------------------------------------------
 1     routeros_00ca                  running
 22    vm-79                          running
```
After maintenance

```
gig@cpu-01:~$ virsh list
 Id    Name                           State
----------------------------------------------------

```

More steps?

**Comment by abdulgig** [comment]
Thanks, we will do some more testing ! Having said that, the issue has been recurring. Please see this ticket,

https://docs.greenitglobe.com/gig/proj_russia_digital_energy/issues/391

Here the CPU was hanging, we put the CPU in maintenance from the portal but the VMs and ROS'es didn't migrate. 

Also, in such a case where the host becomes unresponsive for whatever reason, would the VMs and ROS'es still be able to migrate? In the ticket above, all the ROS'es had to be manually moved.

Thanks,

**Comment by grimpy** [comment]
@abdulgig https://github.com/0-complexity/openvcloud/issues/1141

can you tell me if this is on an environment that already has 2.2.4 or more?


Nicolas told me there also have been issues with maintenance when there are vms in paused on the node

**Comment by riaandn1** [comment]
W.r.t. Russia: https://docs.greenitglobe.com/gig/proj_russia_digital_energy/issues/391 was a hardware problem. MR4 is on OVC 2.2.4.

Standard behaviour whenever we have a CPU failure is to move all VMs and associated ROSs. The ROSs should be moved first before the VMs.

**Comment by john-kheir** [comment]
This should be okay by now
