### ISSUE TITLE
Panel Grid shows VM being on different cpu nodes 

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1204]
As per ticket, https://docs.greenitglobe.com/gig/proj_russia_digital_energy/issues/416

We have the following case, one production system VM shows that is running on a CPU node 26 that is on maintenance.

The actual vm though is running on cpu 23 and it's operating normally.

**Comment by FastGeert** [comment]
HC "Found vm-248 which should be at stack 22" should become selfhealing
- think about stack status
- think about maintenance mode
==> If stack in error / in maintenance we should if possible migrate it away (if possible of course)

**Comment by john-kheir** [comment]
Can't be reproduced
