### ISSUE TITLE
Feature request : need  to be able of Hiding (old) Image/vTemplates Labels when Creating Replacement vTemplates

### ISSUE THREAD

**Issue by hossnys** [0-complexity/openvcloud#1212]
#### Detailed description
Gig-UK are working on offering images with security updates in them, so we want to rebuild the images from time to time and to offer a new version replacing the previous one.

So, given we say Ubuntu V1 , We just rebuilt the ubuntu with latest updates and something else and that would be called: Ubuntu V2.

We got Customers using Ubuntu V1 and We will not force them to replace that image with the latest one, but We would like to hide or mask the label for Ubuntu V1 and SHOW ONLY the Ubuntu V2 if that makes sense to you.

So Old and new customers will be using the ONLY visible image while they can still use their current VMs. (and whenever the OLD images do not longer hold any children VM, we will remove it)

This would help us to make a pretty dynamic offering.
Aiste has also thought on the following potential alternative:

or if they allowed VMs to reboot even when image is disabled..

That would also help. So would be about the same: disable the label bot NOT the image/(or)/vTemplate.

We got a pretty decent Image range in offer at the present and We are going to do a rotation while developing products, so this would be a must for us to have.

**Comment by FastGeert** [comment]
Duplicate of https://github.com/0-complexity/openvcloud/issues/1178
