### ISSUE TITLE
VM with 2 different ids.

### ISSUE THREAD

**Issue by john-kheir** [0-complexity/openvcloud#1219]
**I found a VM with 2 different ids.** 

![errororor](https://user-images.githubusercontent.com/15011431/35095201-4bd7883c-fc50-11e7-912b-27b0d0dc7425.png)

#### Installation information
JumpScale

    Core: branch: staging (70d4588) 1/2/2018, 10:27:09 AM
    Portal: branch: staging (9a65ce8) 12/19/2017, 10:56:59 AM

OpenvCloud

    Core: branch: staging (7cf9376) 1/2/2018, 3:23:47 PM
    G8VDC: branch: staging (989668b) 12/27/2017, 4:19:04 PM
    Selfhealing: branch: staging (748f20f) 12/24/2017, 9:41:56 AM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1

**Comment by FastGeert** [comment]
Not an issue. Is name & id.
@grimpy please confirm

**Comment by grimpy** [comment]
Yes indeed @FastGeert the id shown here is not the openvcloud id which is normally put in the name, but the libvirt id which is an incremental id on the node.

No issue here
