### ISSUE TITLE
VM cannot obtain IP address from DHCP

### ISSUE THREAD

**Issue by dimaandg** [0-complexity/openvcloud#1222]
#### Detailed description
Newly created VM cannot obtain IP address under VDC Cloudspace. ROS is running and accessible

#### Steps to reproduce
Create new VM under VDC

#### Installation information

JumpScale

    Core: branch: production (9870155) 12/20/2017, 12:53:52 PM
    Portal: branch: production (9a65ce8) 12/19/2017, 12:56:59 PM

OpenvCloud

    Core: branch: production (7cf9376) 1/2/2018, 5:23:47 PM
    G8VDC: branch: production (989668b) 12/27/2017, 6:19:04 PM
    Selfhealing: branch: production (748f20f) 12/24/2017, 11:41:56 AM

OpenvStorage mr4

    openvstorage-backend-core: 1.9.1-1
    openvstorage-health-check: 3.3.5-1
    alba: 1.3.25
    openvstorage-webapps: 2.9.5-1
    openvstorage-backend-webapps: 1.9.1-1
    openvstorage-core: 2.9.5-1
    openvstorage-hc: 1.9.1-1
    openvstorage: 2.9.5-1
    openvstorage-backend: 1.9.1-1
    openvstorage-sdm: 1.9.0-1

**Comment by FastGeert** [comment]
Wrong window

**Comment by grimpy** [comment]
was this on mr4-ds1? If so please close

**Comment by FastGeert** [comment]
@riaandn1 this is a ticket, not a bug. So wrong window.
