### ISSUE TITLE
B17: VMs create double snapshots

### ISSUE THREAD

**Issue by dimaandg** [0-complexity/openvcloud#1228]
#### Detailed description
B17, cloud space ID 14(minio), VMs vm-4970 and vm-4971 From CB on the page of VM click on "Create Snapshot" generates 2 snapshots instead 1

![](https://docs.greenitglobe.com/attachments/3185d9ec-6dc2-49fb-8cd0-da1855befd24)

#### Steps to reproduce
 Cannot reproduce this behaviour in another account, cloud space and VM.

#### Installation information
JumpScale

    Core: branch: production (9870155) 12/20/2017, 12:53:52 PM
    Portal: branch: production (9a65ce8) 12/19/2017, 12:56:59 PM

OpenvCloud

    Core: branch: production (7cf9376) 1/2/2018, 5:23:47 PM
    G8VDC: branch: production (989668b) 12/27/2017, 6:19:04 PM
    Selfhealing: branch: production (748f20f) 12/24/2017, 11:41:56 AM

OpenvStorage b17

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1

**Comment by wvandebroeck** [comment]
When a snapshot is created we do it for all disks attached to the VM so 2 disks mean 2 snapshots.  We should provide the relation between the represented snapshots and the disks.  
![image](https://user-images.githubusercontent.com/32832565/35231684-ad5af7be-ff99-11e7-96cb-999ffccd7e6a.png)

**Comment by FastGeert** [comment]
Snapshots are machine snapshots. We should show only 1 value per snapshot & ask user to mark the vdisks  that need to be rollbacked.
