### ISSUE TITLE
OVC should select a second storage router node to host new VM if the primary storage router node failed

### ISSUE THREAD

**Issue by mgaber81** [0-complexity/openvcloud#1229]
#### Detailed description

Since OVS is sending to OVC a list of all available SR regardless if they are up or not ( or even the node is up but the volume driver is down for any reason ).
OVC doesn't select a second SR node if first option ( least occupied node ) Failed to create the VM.

We suggest that if OVC didn't get a successful msg from OVS for creation , it tries to create on another node ( before sending a user message saying that there's no resources ) .
So end user doesn't see / feel this internal issue.

(Probably , to throw error message that the creation failed on node X , so monitoring team can look at it and fix the issue )

**Comment by Dinaamagdy** [comment]
## Software Version
```
JumpScale
Core: branch: 7.2.6 (8a77511) 1/23/2018, 3:15:23 PM
Portal: branch: 7.2.6 (fffe2bf) 1/19/2018, 8:40:36 AM
OpenvCloud
Core: branch: 2.2.6 (68ceb35) 1/24/2018, 8:59:56 AM
G8VDC: branch: 2.2.6 (989668b) 12/27/2017, 4:19:04 PM
Selfhealing: branch: 2.2.6 (896c248) 1/23/2018, 2:48:33 PM
```
