### ISSUE TITLE
Full text search in 0-access doesn't work correctly 

### ISSUE THREAD

**Issue by Dinaamagdy** [0-complexity/openvcloud#1234]
## Steps 
- Search in full-text search box in 0-access page 
## Issue 
it returns some issues which not exist in sessions table then if you  try to get  it, will  redirect you to an internal server error page 

## Software Version 
 on be-g8-4
```
JumpScale
Core: branch: master (98e48f0) 1/18/2018, 3:36:37 AM
Portal: branch: master (cd39831) 1/19/2018, 8:40:36 AM
OpenvCloud
Core: branch: master (135cb69) 1/21/2018, 8:43:26 AM
G8VDC: branch: master (0f14940) 12/27/2017, 9:49:51 PM
Selfhealing: branch: master (aa72d77) 1/18/2018, 1:00:39 AM

```

**Comment by FastGeert** [comment]
This issue is useless like this. Need to add the stacktraces.
