### ISSUE TITLE
Wrong doc string for zeroaccess/getSessionInitTime API

### ISSUE THREAD

**Issue by Dinaamagdy** [0-complexity/openvcloud#1237]
Wrong doc string for zeroaccess/getSessionInitTime API as shown 
![selection_622](https://user-images.githubusercontent.com/24386802/35194445-52a38dc8-febc-11e7-8894-e7707227ba84.png)

## Software Version 
on be-g8-4
```
JumpScale
Core: branch: master (98e48f0) 1/18/2018, 3:36:37 AM
Portal: branch: master (cd39831) 1/19/2018, 8:40:36 AM
OpenvCloud
Core: branch: master (135cb69) 1/21/2018, 8:43:26 AM
G8VDC: branch: master (0f14940) 12/27/2017, 9:49:51 PM
Selfhealing: branch: master (aa72d77) 1/18/2018, 1:00:39 AM
```

**Comment by ahmedelsayed-93** [comment]
verified
JumpScale

    Core: branch: master (278c4fb) 2/21/2018, 1:43:54 PM
    Portal: branch: master (29a3df6) 2/21/2018, 3:52:30 PM

OpenvCloud

    Core: branch: master (81debe4) 2/22/2018, 2:27:21 PM
    G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
    Selfhealing: branch: master (ac36bf5) 2/21/2018, 3:09:31 PM

OpenvStorage be-g8-4

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1
