### ISSUE TITLE
Need to change info in 0-access node player page  to be name of node

### ISSUE THREAD

**Issue by Dinaamagdy** [0-complexity/openvcloud#1238]
Need to change info in 0-access node player page  to be name of node instead of it's Id 
![selection_623](https://user-images.githubusercontent.com/24386802/35194490-f3731098-febc-11e7-9d28-fa259a6e182c.png)

https://be-g8-4.demo.greenitglobe.com/grid/error%20condition?id=9d987440-696f-297b-1824-e6c35371863a
## Software Version 
```
JumpScale
Core: branch: master (98e48f0) 1/18/2018, 3:36:37 AM
Portal: branch: master (cd39831) 1/19/2018, 8:40:36 AM
OpenvCloud
Core: branch: master (135cb69) 1/21/2018, 8:43:26 AM
G8VDC: branch: master (0f14940) 12/27/2017, 9:49:51 PM
Selfhealing: branch: master (aa72d77) 1/18/2018, 1:00:39 AM
```

**Comment by ahmedelsayed-93** [comment]
verified 
JumpScale

    Core: branch: master (278c4fb) 2/21/2018, 1:43:54 PM
    Portal: branch: master (29a3df6) 2/21/2018, 3:52:30 PM

OpenvCloud

    Core: branch: master (81debe4) 2/22/2018, 2:27:21 PM
    G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
    Selfhealing: branch: master (ac36bf5) 2/21/2018, 3:09:31 PM

OpenvStorage be-g8-4

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1
