### ISSUE TITLE
need api to get private network info

### ISSUE THREAD

**Issue by ahmedelsayed-93** [0-complexity/openvcloud#1257]
#### Detailed description
Currently we don't have api to get private networks information for example: 
- status
- cloudspace id
- public ips
- management ip and 
- node id 

and we need this api to be able to test VFW apis ```cloudbroker/cloudspace```

**Comment by FastGeert** [comment]
@ahmedelsayed-93 Can you get your hands dirty and do a pull request? Plz talk to Jo.

**Comment by Dinaamagdy** [comment]
## Software Version 
```
JumpScale
Core: branch: master (278c4fb) 2/21/2018, 1:43:54 PM
Portal: branch: master (29a3df6) 2/21/2018, 3:52:30 PM
OpenvCloud
Core: branch: master (81debe4) 2/22/2018, 2:27:21 PM
G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
Selfhealing: branch: master (ac36bf5) 
```
