### ISSUE TITLE
Allow the ability to change the DHCP IP Address range assigned to VDCs

### ISSUE THREAD

**Issue by riaandn1** [0-complexity/openvcloud#1259]
Currently all VDCs are assigned with a standard internal IP Address range of 192.168.103.0/24. 

There is a potential customer in the UK that wants to extend their infrastructure into the G8s. So they would book some ranges within the VDCs which will be complementary to their own. They would also migrate existing infrastructure to the G8 with the idea of keeping their existing IP ranges.

**Comment by FastGeert** [comment]
This is a 0-GW feature. Is comming in version v2.5

**Comment by FastGeert** [comment]
Closed a bit too soon

**Comment by islamTaha12** [comment]
JumpScale
Core: branch: master (b9da61a) 28/02/2018, 17:23:43
Portal: branch: master (7f0063f) 01/03/2018, 13:01:22
OpenvCloud
Core: branch: master (f6ca6c2) 01/03/2018, 13:04:26
G8VDC: branch: master (d4b49c1) 13/02/2018, 13:56:43
Selfhealing: branch: master (bdaf210) 28/02/2018, 08:46:33
OpenvStorage be-g8-3
openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.0-1
openvstorage-webapps: 2.9.12-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.12-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.26
openvstorage: 2.9.12-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.2-1
openvstorage-sdm: 1.9.1-1
