### ISSUE TITLE
GET /cloudapi/accounts/getConsumption returns empty zip file

### ISSUE THREAD

**Issue by ahmedelsayed-93** [0-complexity/openvcloud#1269]
#### Detailed description
GET /cloudapi/accounts/getConsumption returns empty zip file

#### Steps to reproduce
- trigger jumscript on the controller to collect account's information
- trigger jumscript on the master to collect account's information
- get account consumption using api ```GET /cloudapi/accounts/getConsumption```

#### Installation information

JumpScale

Core: branch: master (87e1515) 1/22/2018, 2:34:15 PM
Portal: branch: master (5082afa) 1/21/2018, 11:59:47 AM
OpenvCloud

Core: branch: master (c25386e) 1/22/2018, 2:49:10 PM
G8VDC: branch: master (0f14940) 12/27/2017, 9:49:51 PM
Selfhealing: branch: master (8cb3425) 1/22/2018, 11:21:19 AM
OpenvStorage be-g8-4

openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.0-1
openvstorage-webapps: 2.9.9-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.9-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.17
openvstorage: 2.9.9-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.1-1
openvstorage-sdm: 1.9.1-1

**Comment by grimpy** [comment]
Files are not properly synced because they have permissions sychting user can't deal with

**Comment by Dinaamagdy** [comment]
## Software Version
```
JumpScale
Core: branch: master (46e17c5) 2/1/2018, 2:18:29 PM
Portal: branch: master (24c3192) 1/31/2018, 8:39:01 AM
OpenvCloud
Core: branch: master (a14a237) 2/4/2018, 9:14:43 AM
G8VDC: branch: master (69544db) 1/31/2018, 11:27:40 AM
Selfhealing: branch: master (ca34b96) 2/1/2018, 12:53:49 PM
```
