### ISSUE TITLE
Fix redischeck when agent is pod

### ISSUE THREAD

**Issue by grimpy** [0-complexity/openvcloud#1275]
root@agentcontroller-6c8fccd888-lwfnt:/opt/jumpscale7/apps/processmanager# jspython jumpscripts/healthchecks/redis_usage_check.py

#########   Operational Critical Error    #################
Redis is not operational (halted or not installed)
###########################################################

[{'category': 'Redis', 'state': 'ERROR', 'uid': 'redis:system:port:9999'}]
[{'category': 'Redis', 'state': 'ERROR', 'uid': 'redis:system:port:9999'}]

We should not do a ays check for redis when agent is a pid (jsagent == pid 1

**Comment by Dinaamagdy** [comment]
## Software Version
```
JumpScale
Core: branch: master (46e17c5) 2/1/2018, 2:18:29 PM
Portal: branch: master (24c3192) 1/31/2018, 8:39:01 AM
OpenvCloud
Core: branch: master (a14a237) 2/4/2018, 9:14:43 AM
G8VDC: branch: master (69544db) 1/31/2018, 11:27:40 AM
Selfhealing: branch: master (ca34b96) 2/1/2018, 12:53:49 PM
```
