### ISSUE TITLE
Secure environment setup

### ISSUE THREAD

**Issue by FastGeert** [0-complexity/openvcloud#1276]
### ssh key handling
- Private ssh key as specified in the system-config.yaml file should only be used during the installation of the controller nodes & the kubernetes cluster.
- During the setup of zero-access pod, we need to generate a new ssh-keypair, and store it in `/var/ovc/.ssh`
- `/var/ovc/.ssh` should be 
  - root:root 0400
  - synced to all controller nodes by the syncting pod
  - mounted into the 0-access pod on `/root/.ssh`
- `/var/ovc/.ssh/id_rsa.pub` should be the only key authorized to all nodes (controller, cpu, storage)
### teleport
Run teleport as a pod on all three nodes as the fallback ssh solution

**Comment by FastGeert** [comment]
@dinosn Can you specify how you would want the teleport setup to be done?

**Comment by dinosn** [comment]
Hi not at the moment i cannot say that teleport is the solution to go. I will need more time to perform some more tests with it.

**Comment by islamTaha12** [comment]
**Verification steps**
1- Using 0-access to access 'management' pod
2- ` cat /opt/cfg/system/system-config.yaml `
3- Get public-key value
4- Access all cpus nodes and make sure that this public-key isn't in /root/.ssh/authorized_keys
