### ISSUE TITLE
typo in 0-access session a

### ISSUE THREAD

**Issue by islamTaha12** [0-complexity/openvcloud#1278]
There is miss "log" in this message.
![image](https://user-images.githubusercontent.com/17981089/35322873-6acaf26c-00f4-11e8-88d3-3385383639f7.png)

**software version**
```
JumpScale
Core: branch: master (87e1515) 1/22/2018, 2:34:15 PM
Portal: branch: master (5082afa) 1/21/2018, 11:59:47 AM
OpenvCloud
Core: branch: master (c25386e) 1/22/2018, 2:49:10 PM
G8VDC: branch: master (0f14940) 12/27/2017, 9:49:51 PM
Selfhealing: branch: master (8cb3425) 1/22/2018, 11:21:19 AM
OpenvStorage be-g8-4
openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.0-1
openvstorage-webapps: 2.9.9-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.9-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.17
openvstorage: 2.9.9-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.1-1
openvstorage-sdm: 1.9.1-1
```

**Comment by FastGeert** [comment]
Need to fix the JWT refreshing.

**Comment by ahmedelsayed-93** [comment]
verified 

### software version
JumpScale

    Core: branch: master (278c4fb) 2/21/2018, 1:43:54 PM
    Portal: branch: master (29a3df6) 2/21/2018, 3:52:30 PM

OpenvCloud

    Core: branch: master (81debe4) 2/22/2018, 2:27:21 PM
    G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
    Selfhealing: branch: master (ac36bf5) 2/21/2018, 3:09:31 PM

OpenvStorage be-g8-4

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1
