### ISSUE TITLE
user api access to OVC

### ISSUE THREAD

**Issue by despiegk** [0-complexity/openvcloud#1281]
its very unclear as enduser how to login into OVC space

when using secret keys
doesn't seem to work

is IYO the only way?

then the entry on eg. https://be-gen-1.demo.greenitglobe.com/g8vdc/#/CloudSpaceSettings
is very confusing

**Comment by despiegk** [comment]
important for our node testing & how we want people to get to test our sw, now they do everything IYO and that is potentially dangerous

**Comment by despiegk** [comment]
it tried client in js93

**Comment by grimpy** [comment]
Currently JWT is the only way to it.

https://be-gen-1.demo.greenitglobe.com/g8vdc/#/ApiDocs
This should probably point to our docs 

Some documentation that could use some updating:
- https://github.com/0-complexity/openvcloud/blob/master/docs/API/GettingStarted.md

https://be-gen-1.demo.greenitglobe.com/g8vdc/#/Docs/getting-started-with-jumpscale
this page is antique and should either be removed or updated, preferably point to a link that will stay updated.

This also made me notice that jumpscale.org website is pretty much outdated.

**Comment by islamTaha12** [comment]
verified
```
JumpScale
Core: branch: master (278c4fb) 21/02/2018, 13:43:54
Portal: branch: master (29a3df6) 21/02/2018, 15:52:30
OpenvCloud
Core: branch: master (81debe4) 22/02/2018, 14:27:21
G8VDC: branch: master (d4b49c1) 13/02/2018, 13:56:43
Selfhealing: branch: master (ac36bf5) 21/02/2018, 15:09:31
OpenvStorage be-g8-4
openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.0-1
openvstorage-webapps: 2.9.9-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.9-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.17
openvstorage: 2.9.9-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.1-1
openvstorage-sdm: 1.9.1-1
```
