### ISSUE TITLE
VM Creation Failure - Make volume with API first and then write data on it

### ISSUE THREAD

**Issue by riaandn1** [0-complexity/openvcloud#1282]
During the creation of a virtual machine on 25/01/2018, 10:47:40 (GMT) the creation of the virtual machine failed and timed out after 1 minute and 2 seconds with reported error:

Exec error procmgr jumpscr:greenitglobe_createmetaiso on node:222_19 AttributeError: 'NoneType' object has no attribute 'guid'

System: CH-GEN-1 Account: Università di Pisa Cloudspace: Maurizio Davini Virtual Machine: vm-254 Image: Unbuntu 16.04 x86 Size: 2GB Memory 2 Cores, 50GB SSD Speed

Relevant log files:

-     https://ch-gen-1.demo.greenitglobe.com/grid/job?id=413761accfe146869c70a651fd79a1bd
-     https://ch-gen-1.demo.greenitglobe.com/grid/error%20condition?id=79ced8e0-454f-f67a-9bb9-b6a6ce3bdc13

As suggested by Jo: make the volume with the API first and then write data to it to avoid this situation accurring.

**Comment by islamTaha12** [comment]
verified
```
JumpScale
Core: branch: master (278c4fb) 21/02/2018, 13:43:54
Portal: branch: master (29a3df6) 21/02/2018, 15:52:30
OpenvCloud
Core: branch: master (81debe4) 22/02/2018, 14:27:21
G8VDC: branch: master (d4b49c1) 13/02/2018, 13:56:43
Selfhealing: branch: master (ac36bf5) 21/02/2018, 15:09:31
OpenvStorage be-g8-4
openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.0-1
openvstorage-webapps: 2.9.9-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.9-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.17
openvstorage: 2.9.9-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.1-1
openvstorage-sdm: 1.9.1-1
```
