### ISSUE TITLE
Arakoon Collapse hitting timeout

### ISSUE THREAD

**Issue by dimaandg** [0-complexity/openvcloud#1283]
#### Detailed description
Arakoon Collapse script hitting timeout we might need to extend it from 1hr to 2hrs or more..
![capture](https://user-images.githubusercontent.com/25789719/35427733-a1537192-0284-11e8-9983-07ec970a4523.PNG)
 and portal was posting this warning
![capture](https://user-images.githubusercontent.com/25789719/35427778-e08aeca0-0284-11e8-9ad7-9a09bf13f59b.PNG)

but when the script was run manually it took:

stor-01:
```
real    2m2.868s
user    0m6.276s
sys     0m38.500s
```

stor-06:
```
real    83m10.794s
user    50m51.120s
sys     18m43.076s
```

on Stor-06 script was run twice as there was one cachebackend that was not processed:
```
[*] Checking collapse on cachebackend02-nsm_04
   [*] Other node is collapsing arakoon
```

on the second run it took processing that one item. All other were skipped.
```
real    140m3.761s
user    83m29.836s
sys     35m28.140s
```

#### Installation information

```
JumpScale

    Core: branch: production (9870155) 12/20/2017, 12:53:52 PM
    Portal: branch: production (9a65ce8) 12/19/2017, 12:56:59 PM

OpenvCloud

    Core: branch: production (7cf9376) 1/2/2018, 5:23:47 PM
    G8VDC: branch: production (989668b) 12/27/2017, 6:19:04 PM
    Selfhealing: branch: production (748f20f) 12/24/2017, 11:41:56 AM

OpenvStorage mr4

    openvstorage-backend-core: 1.9.1-1
    openvstorage-health-check: 3.3.5-1
    alba: 1.3.25
    openvstorage-webapps: 2.9.5-1
    openvstorage-backend-webapps: 1.9.1-1
    openvstorage-core: 2.9.5-1
    openvstorage-hc: 1.9.1-1
    openvstorage: 2.9.5-1
    openvstorage-backend: 1.9.1-1
    openvstorage-sdm: 1.9.0-1
```

**Comment by grimpy** [comment]
@dinosn is this still valid?

**Comment by grimpy** [comment]
Closed untill it happens again
