### ISSUE TITLE
Couldn't start a vm because of that eco and it's irreducable.

### ISSUE THREAD

**Issue by john-kheir** [0-complexity/openvcloud#1286]
This eco happened 53 times.

#### ECO
https://be-g8-3.demo.greenitglobe.com/grid/error%20condition?id=fa990d2e-b27c-1008-adb4-7689afd62c3e
![ecoecoeco1](https://user-images.githubusercontent.com/15011431/35480002-4bff410a-040d-11e8-9cf7-da510d77173a.png)

#### Installation information

JumpScale

    Core: branch: 7.2.6 (8a77511) 1/23/2018, 3:15:23 PM
    Portal: branch: 7.2.6 (fffe2bf) 1/19/2018, 8:40:36 AM

OpenvCloud

    Core: branch: 2.2.6 (44fca5f) 1/24/2018, 1:46:37 PM
    G8VDC: branch: 2.2.6 (989668b) 12/27/2017, 4:19:04 PM
    Selfhealing: branch: 2.2.6 (a463583) 1/24/2018, 7:28:16 PM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1

**Comment by grimpy** [comment]
This error implies the networkId is not set on the cloudspace...
@john-kheir how did you manage to get in this situation? Withouth reproduction steps I can't do anything with this issue

**Comment by ahmedelsayed-93** [comment]
can't reproduce 

### software version
JumpScale

    Core: branch: master (95e24e7) 2/27/2018, 4:26:50 PM
    Portal: branch: master (29a3df6) 2/21/2018, 3:52:30 PM

OpenvCloud

    Core: branch: master (f89698e) 2/27/2018, 10:22:18 PM
    G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
    Selfhealing: branch: master (bdaf210) 2/28/2018, 8:46:33 AM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1
