### ISSUE TITLE
Vfw will always get started when enabling a node.

### ISSUE THREAD

**Issue by john-kheir** [0-complexity/openvcloud#1297]
## Steps to reproduce
1- Stop a vfw on a certain node.
2- Put this node in maintenance.
3- Enable the node back.

#### Actual Result
VFW will start even though it was halted before putting node in maintenance.

#### Expected Result
VFW should stay halted.

## Installation information

JumpScale

    Core: branch: master (d6cb6a8) 1/23/2018, 3:15:23 PM
    Portal: branch: master (5082afa) 1/21/2018, 11:59:47 AM

OpenvCloud

    Core: branch: master (559bad0) 1/30/2018, 12:55:58 PM
    G8VDC: branch: master (6a102ec) 1/28/2018, 10:37:28 AM
    Selfhealing: branch: master (50c88e4) 1/28/2018, 9:49:22 AM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1

**Comment by ahmedelsayed-93** [comment]
verified 

### software version
JumpScale

    Core: branch: master (278c4fb) 2/21/2018, 1:43:54 PM
    Portal: branch: master (29a3df6) 2/21/2018, 3:52:30 PM

OpenvCloud

    Core: branch: master (81debe4) 2/22/2018, 2:27:21 PM
    G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
    Selfhealing: branch: master (ac36bf5) 2/21/2018, 3:09:31 PM

OpenvStorage be-g8-4

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1
