### ISSUE TITLE
Make it possible to migrate to kubernetes

### ISSUE THREAD

**Issue by grimpy** [0-complexity/openvcloud#1302]
create two scripts , one to run on the old envirmoent to upload the backups into a (webdav), and another script to run on the new pod to download and restore the data from the (webdav)

**Comment by Dinaamagdy** [comment]
to test 
https://github.com/0-complexity/openvcloud_installer/blob/master/docs/Migration-script.md#L16
and need two environments  to test

**Comment by ahmedelsayed-93** [comment]
should be verified by ops

**Comment by davshafik** [comment]
migrations from 2.2.6 to 2.4.0 is not valid yet, there are some bugs related to database restoration.
