### ISSUE TITLE
Can't connect to cntrl2&3 with zero-access

### ISSUE THREAD

**Issue by Dinaamagdy** [0-complexity/openvcloud#1306]
## Issue 
try to connect to cntrl2 and cntrl3 with zero access, and it asked for a password so I can't get into them although I can connect to cntrl1

## Software Version 
be-g8-4
```
JumpScale
Core: branch: master (d6cb6a8) 1/23/2018, 3:15:23 PM
Portal: branch: master (5082afa) 1/21/2018, 11:59:47 AM
OpenvCloud
Core: branch: master (02f4271) 1/24/2018, 2:39:14 PM
G8VDC: branch: master (0f14940) 12/27/2017, 9:49:51 PM
Selfhealing: branch: master (d5b630b) 1/24/2018, 2:03:38 PM

```

**Comment by grimpy** [comment]
Needs to be verified after proper reinstall of be-g8-4

**Comment by ahmedelsayed-93** [comment]
verified 
### software version
JumpScale

    Core: branch: master (278c4fb) 2/21/2018, 1:43:54 PM
    Portal: branch: master (29a3df6) 2/21/2018, 3:52:30 PM

OpenvCloud

    Core: branch: master (81debe4) 2/22/2018, 2:27:21 PM
    G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
    Selfhealing: branch: master (ac36bf5) 2/21/2018, 3:09:31 PM

OpenvStorage be-g8-4

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1
