### ISSUE TITLE
import vm doesn't work 

### ISSUE THREAD

**Issue by ahmedelsayed-93** [0-complexity/openvcloud#1325]
#### Detailed description
- The new vm appeared for seconds in the cloudspace.
- I received an email saying that ```your machine was not successfully imported```
-  It's job status was OK.

#### Steps to reproduce
- create vm
- export it 
- import new vm 

#### Relevant stacktraces
the job status was OK.

#### Installation information

JumpScale
```
Core: branch: master (46e17c5) 2/1/2018, 2:18:29 PM
Portal: branch: master (24c3192) 1/31/2018, 8:39:01 AM
```
OpenvCloud
```
Core: branch: master (a14a237) 2/4/2018, 9:14:43 AM
G8VDC: branch: master (69544db) 1/31/2018, 11:27:40 AM
Selfhealing: branch: master (ca34b96) 2/1/2018, 12:53:49 PM
```
OpenvStorage be-g8-4
```
openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.0-1
openvstorage-webapps: 2.9.9-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.9-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.17
openvstorage: 2.9.9-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.1-1
openvstorage-sdm: 1.9.1-1
```

**Comment by FastGeert** [comment]
Hey Ahmed, thank you for your nice bug report, but can you clarify a bit more what exactly does not work.

**Comment by ahmedelsayed-93** [comment]
The new vm appeared for seconds in the cloudspace and then it was deleted automatically (because the import action failed)

**Comment by ramezsaeed** [comment]
Cannot reproduce

JumpScale

    Core: branch: master (3f55ec4) 3/5/2018, 3:34:08 PM
    Portal: branch: master (be124d0) 3/5/2018, 12:31:52 PM

OpenvCloud

    Core: branch: master (f2c3e25) 3/6/2018, 6:12:11 PM
    G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
    Selfhealing: branch: master (4adf360) 3/4/2018, 10:58:12 AM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.12-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.12-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.26
    openvstorage: 2.9.12-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.2-1
    openvstorage-sdm: 1.9.1-1
