### ISSUE TITLE
Issue with maintenance mode, not all vms are moved when vm is imported 

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1327]
As per Jo's comment: 
Jo De Boeck, [Feb 8, 2018 at 7:59:13 AM]:
Seems this was an imported vm and due to a bug (which I beleive was fixed in 2.2.6) the image respresenting imported vms was not made available on any stacks

Jo De Boeck, [Feb 8, 2018 at 7:59:25 AM]:
hence it could not be moved hence you popup for move was empty...

**Comment by Dinaamagdy** [comment]
can't verify due this issue
https://github.com/0-complexity/openvcloud/issues/1411

**Comment by Dinaamagdy** [comment]
## Software Version 
```
JumpScale
Core: branch: master (3f55ec4) 3/5/2018, 3:34:08 PM
Portal: branch: master (be124d0) 3/5/2018, 12:31:52 PM
OpenvCloud
Core: branch: master (45253f8) 3/6/2018, 4:43:02 PM
G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
Selfhealing: branch: master (4adf360) 3/4/2018, 10:58:12 AM
```
