### ISSUE TITLE
Delete size doesn't work once used for a VM, even after destroying the machine

### ISSUE THREAD

**Issue by yveskerwyn** [0-complexity/openvcloud#1328]
#### Detailed description

cloudbroker/iaas/deletesize returns when you

#### Steps to reproduce

Create new size:
![screen shot 2018-02-08 at 11 57 34](https://user-images.githubusercontent.com/13795109/35969491-49fdf424-0cc7-11e8-9228-0b2106976d89.png)

Check that it was created with `id=10`: 
![screen shot 2018-02-08 at 11 58 19](https://user-images.githubusercontent.com/13795109/35969515-64dbe7ec-0cc7-11e8-8c48-ac3562a2872a.png)

Delete the size:
![screen shot 2018-02-08 at 11 59 35](https://user-images.githubusercontent.com/13795109/35969566-905b3670-0cc7-11e8-8d9d-dd53a48e918e.png)

Check that it actually got deleted:
![screen shot 2018-02-08 at 12 00 16](https://user-images.githubusercontent.com/13795109/35969592-a76c3968-0cc7-11e8-98e5-52ff37d1f3d9.png)

Create it again:
![screen shot 2018-02-08 at 12 00 56](https://user-images.githubusercontent.com/13795109/35969619-c08ab9b0-0cc7-11e8-9255-279615d577a9.png)

Check that it got recreated with `id=11` now:
![screen shot 2018-02-08 at 12 01 38](https://user-images.githubusercontent.com/13795109/35969652-e0c15b4e-0cc7-11e8-93aa-1a935f6862c9.png)

Create a machine with this new size:
![screen shot 2018-02-08 at 12 03 36](https://user-images.githubusercontent.com/13795109/35969736-1fa7aa16-0cc8-11e8-8ed0-7a7bcd5ad887.png)

Delete the machine:
![screen shot 2018-02-08 at 12 04 14](https://user-images.githubusercontent.com/13795109/35969763-374ab514-0cc8-11e8-9039-7d51c0d2dce1.png)

Try to delete the size:
![screen shot 2018-02-08 at 12 04 52](https://user-images.githubusercontent.com/13795109/35969787-4d3e6a28-0cc8-11e8-9e3a-c3fa93d50e97.png)

Size is not deleted:
![screen shot 2018-02-08 at 12 05 19](https://user-images.githubusercontent.com/13795109/35969808-5d685076-0cc8-11e8-8ef4-3dd3dfbc484f.png)

#### Installation information

![screen shot 2018-02-08 at 11 55 58](https://user-images.githubusercontent.com/13795109/35969432-11607a24-0cc7-11e8-839b-5a82870f633a.png)

**Comment by FastGeert** [comment]
Instead of fixing this bug, we are going to implement this FR: https://github.com/0-complexity/openvcloud/issues/1329

**Comment by yveskerwyn** [comment]
bugs should be solved

**Comment by yveskerwyn** [comment]
feel free to close again, after discussing with @FastGeert who told me that this problem gets solved once we implement #1329, follow-up needed though
