### ISSUE TITLE
Cannot create port forward for different protocol on the same port number.

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1330]
Hi 
  The case is the following. 

User creates a port forward for TCP port 1234 to vm TCP port 1234.
User tries to create port forward for UDP port 1234 to vm UDP port 1234 and fails 
![image](https://user-images.githubusercontent.com/3851678/36034662-67118368-0dbd-11e8-98c8-b2276280e673.png)

**Comment by ahmedelsayed-93** [comment]
verified
