### ISSUE TITLE
Create rescue mode for all  VMs 

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1344]
Hi 

In some cases we have problems where we need to mount the filesystem of a VM to another system, or boot the VM with a separate ISO in order to execute basic commands like fixing the filesystem and so on. 

 I would like to make a request to have the ability to set a VM in rescue mode where in that mode,

- The system will boot with from different, ISO eg,  http://www.system-rescue-cd.org/ 
- It will take the normal network configuration as per VM booted in that mode
- Will have all the disks present on the VM assigned 
- The rescue mode will be cleared upon restart

**Comment by grimpy** [comment]
We now made it possible for an admin user (operator) to upload ISO images. It is possible for the user to choose to boot from such ISOs
