### ISSUE TITLE
we can update destroyed account name

### ISSUE THREAD

**Issue by Dinaamagdy** [0-complexity/openvcloud#1355]
## Issue
Try to update account name after deleting it , it will be updated 

## Software Version 
```
JumpScale
Core: branch: master (b567059) 2/20/2018, 11:41:37 AM
Portal: branch: master (f0d2b19) 2/19/2018, 1:32:31 PM
OpenvCloud
Core: branch: master (6874edf) 2/19/2018, 9:30:47 AM
G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
Selfhealing: branch: master (0ee4e71) 2/19/2018, 10:48:54 AM
```

**Comment by abdulrahmantkhalifa** [comment]
https://github.com/0-complexity/openvcloud/pull/1461

**Comment by ahmedelsayed-93** [comment]
verified 
JumpScale
Core: branch: master (f316dcf) 3/15/2018, 11:06:22 AM
Portal: branch: master (6012e26) 4/2/2018, 7:40:00 PM
OpenvCloud
Core: branch: master (565678e) 4/10/2018, 8:55:35 AM
G8VDC: branch: master (b085672) 3/16/2018, 5:09:29 PM
Selfhealing: branch: master (7e92f5a) 4/3/2018, 10:33:53 AM
OpenvStorage se-gen-1
openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.8-1
openvstorage-webapps: 2.9.12-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.12-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.26
openvstorage: 2.9.12-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.2-1
openvstorage-sdm: 1.9.1-1
