### ISSUE TITLE
No accounts or cloudspaces display on user page 

### ISSUE THREAD

**Issue by Dinaamagdy** [0-complexity/openvcloud#1357]
## Issue
Check user who has accounts and cloudspaces page,you will find  accounts and cloudspaces table empty as shown 
![selection_641](https://user-images.githubusercontent.com/24386802/36471249-75f3af04-16f6-11e8-934f-f5ef0f428d0c.png)

## Software Version
```
JumpScale
Core: branch: master (b567059) 2/20/2018, 11:41:37 AM
Portal: branch: master (f0d2b19) 2/19/2018, 1:32:31 PM
OpenvCloud
Core: branch: master (6874edf) 2/19/2018, 9:30:47 AM
G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
Selfhealing: branch: master (0ee4e71) 
```

**Comment by ramezsaeed** [comment]
Cannot reproduce

JumpScale

    Core: branch: master (3f55ec4) 3/5/2018, 3:34:08 PM
    Portal: branch: master (be124d0) 3/5/2018, 12:31:52 PM

OpenvCloud

    Core: branch: master (f2c3e25) 3/6/2018, 6:12:11 PM
    G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
    Selfhealing: branch: master (4adf360) 3/4/2018, 10:58:12 AM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.12-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.12-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.26
    openvstorage: 2.9.12-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.2-1
    openvstorage-sdm: 1.9.1-1
