### ISSUE TITLE
need a sufficient portal messages while putting a node in maintenance to report the error 

### ISSUE THREAD

**Issue by Pishoy** [0-complexity/openvcloud#1363]
#### Detailed description

need a sufficient portal messages (have not a valid image on other cpu node)  while putting a node in maintenance when other available nodes have not a valid images to the cpu node that we are putting it on maintenance node  

#### Steps to reproduce

cpu-01 has a list of images x y z 
cpu-02 has images x y and vm1 which is running with image z 
cpu-03 has images x y

1- put cpu-01 in maintenance mode
2-  put cpu-02 in maintenance mode will got error regarding the maintenance without clrear message that  we have not a valid image 
can not put cpu-02 in maintenance mode and no clear message form error that inform me that the VM are running on cpu-02 has not a cpu node is enabled which has its image

#### Installation information

JumpScale
```
Core: branch: production (8a77511) 1/23/2018, 3:15:23 PM
Portal: branch: production (ada4a21) 1/30/2018, 7:44:31 PM
```
OpenvCloud
```
Core: branch: production (a5c4eee) 2/14/2018, 1:32:38 PM
G8VDC: tag: v2.2.5 (989668b) 12/27/2017, 4:19:04 PM
Selfhealing: branch: production (3bc2f9b) 2/7/2018, 1:58:11 PM
```
OpenvStorage ch-gen-1
```
openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.0-1
openvstorage-webapps: 2.9.9-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.9-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.17
openvstorage: 2.9.9-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.1-1
openvstorage-sdm: 1.9.1-1
```

**Comment by grimpy** [comment]
Currently there is some sloppy logic in the getBestStack logic that will give an index error when there are no nodes available for a certain amount of memory/image.
THis should raise a proper 503 with a decent error message instead of a 500
