### ISSUE TITLE
FR: Admin on cloudspace should be able to list/get the cloudspace account

### ISSUE THREAD

**Issue by muhamadazmy** [0-complexity/openvcloud#1365]
#### Detailed description
A user with a full access to a cloudspace, will not be able to get info about the account, or get the account in the account list if he was not added explicitly to that account.
also when giving a user access on a vm he should has read access on cs and account

#### Steps to reproduce
- Add a user to a VDC
- Make sure the user is not added to the account
- Try listing the user accounts via the API
- The account does not show up

**Comment by katia-e** [comment]
Which API call list user's accounts? I only see API calls to get user, which doesn't list accounts. 
I can see list of accounts for each user only in admin portal, however, on `be-g8-3` list of accounts is empty, as well as the list of openvclouds (for users who has accounts and vdc's).
