### ISSUE TITLE
ROS'es do not migrate as per User Selection

### ISSUE THREAD

**Issue by abdulgig** [0-complexity/openvcloud#1369]
#### Detailed description
When the CPU node is put in maintenance mode, OVC moves the ROS'es based upon its internal algorithm. However, when the user selects the CPU node on which he wants to move his ROS'es , still OVC seems to move the them on different nodes and discards the user's selection.

####Expected Result:
The VM or ROS's should move to the CPU node as per User selection.

#### Steps to reproduce

1. Select a VFW/ROS from the drop down and try moving it on a designated node you select. 

#### Relevant stacktraces

There are no errors. The VFWs do move, but they don't move as selected by the user.

#### Installation information

- environment version: b17 (Russia)

JumpScale

    Core: branch: production (8a77511) 1/23/2018, 5:15:23 PM
    Portal: branch: production (ada4a21) 1/30/2018, 9:44:31 PM

OpenvCloud

    Core: branch: production (a5c4eee) 2/14/2018, 3:32:38 PM
    G8VDC: branch: production (989668b) 12/27/2017, 6:19:04 PM
    Selfhealing: branch: production (3bc2f9b) 2/7/2018, 3:58:11 PM

OpenvStorage b17

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1

**Comment by PeterNashaat** [comment]
- when i tried to migrate a Ros to cpu-04 it was migrated to cpu-03 and the same when i migrated to cpu-02 it was migrated to cpu-01.
- it's using the node id not the stack id for the migration of the Ros.

**Comment by grimpy** [comment]
I beleive this is fixed in 2.3.0

**Comment by ahmedelsayed-93** [comment]
https://github.com/0-complexity/openvcloud/issues/1304 duplicated
