### ISSUE TITLE
Zero-os vm

### ISSUE THREAD

**Issue by FastGeert** [0-complexity/openvcloud#1370]
Please document how to boot a zero-os vm

**Comment by grimpy** [comment]
https://github.com/0-complexity/openvcloud_ays/pull/21

**Comment by ahmedelsayed-93** [comment]
markdown typo in all the links 
![image](https://user-images.githubusercontent.com/24386820/36794775-f583688c-1ca9-11e8-9aa3-62b5c366731a.png)

**Comment by grimpy** [comment]
Fixed markdown links https://github.com/0-complexity/openvcloud_ays/tree/master/_images/image_ipxe

**Comment by ahmedelsayed-93** [comment]
verified
