### ISSUE TITLE
delete last user of cloudspace  return true

### ISSUE THREAD

**Issue by Dinaamagdy** [0-complexity/openvcloud#1377]
## Issue 
delete last  user from cloudspace useing https://be-g8-4.demo.greenitglobe.com/system/ActorApi?group=cloudbroker#!/cloudbroker__cloudspace/post_cloudbroker_cloudspace_deleteUser Api , return always True

**Comment by grimpy** [comment]
By design this is to allow people to call a delete withouth having to check if it exists before
