### ISSUE TITLE
Remove orphaned images directly without keeping them for days.

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1378]
Hi, 

  Under the current environment and looking on the maturity of the products, OVC/OVS I would like to request the direct removal of orphaned images without keeping them for days.

Up until now and from my understanding there hasn't been a case in the last year that these orphaned images needed to stay on the environment.

**Comment by FastGeert** [comment]
Will be solved by #1555 and the recycle bin feature.
