### ISSUE TITLE
Generate Billing Records for Individual Accounts

### ISSUE THREAD

**Issue by riaandn1** [0-complexity/openvcloud#1383]
We require a feature on OVC to query the amount if Cloud Units usage per Account as follows:
- Compute Units: The amount of vCPUs and Memory used
- Storage Units: The amount of storage used in TB
- Transaction Units: The amount of IOPS used by the virtual disks
- Network Units: The amount of data transferred in/out of the VDCs under the account in TB
- Windows Server Licenses used: The amount of vCPU used by VMs deployed using Windows Server images

**Comment by grimpy** [comment]
All this information is already in the resource monitoring data for windows licensing one can check the vmachine image name

**Comment by grimpy** [comment]
@wvandebroeck the reason we don't have APIs specificly for these things is because these calls are very database intensive and we do not want to open an API that can easily be abused for ddos (or just a bad implementation from 3rd party that keeps polling this api)

**Comment by wvandebroeck** [comment]
@riaandn1 is this sufficient for you?

**Comment by riaandn1** [comment]
What about other machines not based on Windows. I need a solution to easily query usage of a G8 on an account level.

**Comment by wvandebroeck** [comment]
@grimpy We need to come up with a scalable solution that addresses the needs to meter on the needed paramaters.

**Comment by grimpy** [comment]
https://github.com/0-complexity/openvcloud/blob/master/docs/Monitoring/ResourceTracking/README.md

They already existed :D

**Comment by grimpy** [comment]
@riaandn1 what about them? They will have a diffrent image name? Whoever proceses the capnp can easily do his calculations? Maybe he has some other licensed images? (thinkign about awingu in the potential future) which needs diffrent kind of billing having the name of the image makes sense to me

**Comment by hofkensj** [comment]
why is the capnp file not enough ?

**Comment by riaandn1** [comment]
capnp files should be enough. Will try it myself to see how it works and suggest the same to other CSPs.
