### ISSUE TITLE
RouterOS - configuration rollback

### ISSUE THREAD

**Issue by dimaandg** [0-complexity/openvcloud#1392]
Dear all,

As agreed with Mohannad, I'm creating this ticket to follow-up on our question during the last conf calls concerning some rollbacks on our RouterOS.

Case 1: Cloud Space LCI (ID 3510)

On this ROS, we have several addresses, subnets, PPP secrets and routes configured. There's a dhcp pool configured containing addresses 172.17.0.226-172.17.0.238 and DHCP server is supposed to use this address pool. We have noted several points:

1. When adding a new VM to the Cloud Space, it automatically gains an address in 192.168.103.0/24 network, and not in the range defined in the address pool.
2. When there is a RouterOS reboot (for whichever reason), several routes are missing afterwards (example: the route to 172.25.0.0/16 => 172.17.0.219 is not there anymore), and some networks change (example: the network currently 172.17.0.48/29 goes to 172.17.0.48/30, which is an old configuration for several months ago).

The LCI Cloud Space case is just an example. It happens in all cloud spaces.

Case 2: any new RouterOS

1. Create a new Cloud Space.
2. Deploy new VM. VM has an IP in network 192.168.103.0/24, which is normal as there has been no changes to RouterOS yet.
3. Open WebFig from "Advanced Shield configuration", and modify:
        Networks: change 192.168.103.0/24 to 192.168.2.0/24
        Addresses: change 192.168.103.1 to 192.168.2.1
        Addresses pool: add a new pool called "dhcp" with addresses 192.168.2.100-192.168.2.110
        DHCP server: change to use an "address pool" from "static" to "dhcp".
4. Deploy new VM. It still has an address in 192.168.103.0/24 network.

- environment version:
ma-g8-1.demo.greenitglobe.com

JumpScale

    Core: branch: production (8a77511) 1/23/2018, 5:15:23 PM
    Portal: branch: production (ada4a21) 1/30/2018, 9:44:31 PM

OpenvCloud

    Core: branch: production (a5c4eee) 2/14/2018, 3:32:38 PM
    G8VDC: branch: production (989668b) 12/27/2017, 6:19:04 PM
    Selfhealing: branch: production (3bc2f9b) 2/7/2018, 3:58:11 PM

**Comment by grimpy** [comment]
This seems to indicate restoration from backup is not working as expected or no backup exists.

**Comment by mohamedgalal99** [comment]
As I tested on mauritius, I created new cloudscpace and opened it's Defense Shield, make some updates, waiting more than 10 min, but I didn't see it's backup in ovs.

**Comment by grimpy** [comment]
Seems the problem relates to taking more then 1 backup first time is supposed to work but it never gets updated afterwards.

**Comment by FastGeert** [comment]
The time needed to implement the configuration rollback fix is limited to a couple of hours according to @grimpy.

**Comment by islamTaha12** [comment]
**steps to test:**
1- Create new cloudspace
2- Change Address and Pool config from the Defense shield
3- wait 10 mins
4- stop/start VFW
5- Check the settings of the defense shield

**Expected result**
- Restart VFW reset original settings

**Comment by john-kheir** [comment]
Other Steps:
1- Create a new cloud space
2- Change some Defense Shield Config.
3- Check if a routeros backup has been created under /mnt/vmstor in any store node.

**Comment by Dinaamagdy** [comment]
## Software Version 
```
JumpScale
Core: branch: master (3f55ec4) 3/5/2018, 3:34:08 PM
Portal: branch: master (be124d0) 3/5/2018, 12:31:52 PM
OpenvCloud
Core: branch: master (ab99332) 3/5/2018, 8:29:11 PM
G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
Selfhealing: branch: master (4adf360) 3/4/2018, 10:58:12 AM

```
