### ISSUE TITLE
export vm returns internal server error

### ISSUE THREAD

**Issue by ahmedelsayed-93** [0-complexity/openvcloud#1397]
#### Relevant stacktraces

![image](https://user-images.githubusercontent.com/24386820/36850345-2d5c521c-1d6f-11e8-88a4-e0eb008e828d.png)

and the error condition page is empty 
#### Installation information

JumpScale

    Core: branch: master (b9da61a) 2/28/2018, 5:23:43 PM
    Portal: branch: master (7f0063f) 3/1/2018, 1:01:22 PM

OpenvCloud

    Core: branch: master (f6ca6c2) 3/1/2018, 1:04:26 PM
    G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
    Selfhealing: branch: master (bdaf210) 2/28/2018, 8:46:33 AM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.12-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.12-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.26
    openvstorage: 2.9.12-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.2-1
    openvstorage-sdm: 1.9.1-1

**Comment by grimpy** [comment]
Potentially related to problem with the dns on be-g8-3, can you please test this again now this problem is resolved.

**Comment by grimpy** [comment]
```
path:restmachine/system/contentmanager/checkEvents
***ERROR***:Traceback (most recent call last):
~   File "/opt/jumpscale7/lib/JumpScale/portal/portal/PortalRest.py", line 254, in execute_rest_call
    result = method(ctx=ctx, **ctx.params)
~   File "/opt/jumpscale7/libext/cloudbrokerlib/authenticator.py", line 138, in wrapper
    return func(*args, **kwargs)
~   File "/opt/jumpscale7/apps/portals/main/base/cloudapi__machines/methodclass/cloudapi_machines.py", line 575, in exportOVF
    self._validate_links(link=link, callbackUrl=callbackUrl)
~   File "/opt/jumpscale7/apps/portals/main/base/cloudapi__machines/methodclass/cloudapi_machines.py", line 523, in _validate_links
    parsed = urlparse.urlparse(url)
~   File "/opt/jumpscale7/lib/urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
~   File "/opt/jumpscale7/lib/urlparse.py", line 182, in urlsplit
    i = url.find(':')
~ AttributeError: 'NoneType' object has no attribute 'find'
type/level: UNKNOWN/1
```
