### ISSUE TITLE
extend API audit

### ISSUE THREAD

**Issue by dimaandg** [0-complexity/openvcloud#1404]
need to add API calls arguments and parameters to API audit logs

![image](https://user-images.githubusercontent.com/25789719/36900090-40d3f5a8-1e3b-11e8-838d-fb5e94cbcff9.png)

#### Installation information

- environment version:

JumpScale

    Core: branch: production (8a77511) 1/23/2018, 5:15:23 PM
    Portal: branch: production (ada4a21) 1/30/2018, 9:44:31 PM

OpenvCloud

    Core: branch: production (a5c4eee) 2/14/2018, 3:32:38 PM
    G8VDC: branch: production (989668b) 12/27/2017, 6:19:04 PM
    Selfhealing: branch: production (3bc2f9b) 2/7/2018, 3:58:11 PM

**Comment by grimpy** [comment]
This is just the overview of the audits... When clicking the audit args and kwargs are visible see

![image](https://user-images.githubusercontent.com/143869/36916022-617db774-1e5b-11e8-9370-2565e4506b32.png)
