### ISSUE TITLE
add information regarding any running jobs for all elements (VDC/VM/Stack)

### ISSUE THREAD

**Issue by dimaandg** [0-complexity/openvcloud#1405]
#### Detailed description

For example when you press put into maintenance you will see info about running jobs.
Also at level of VM/VFW you will see status: planned to be migrated due to stack maintenance / migrating / none

<img width="403" alt="31920d34-be75-463b-86fc-d08f0f8eaffa" src="https://user-images.githubusercontent.com/25789719/36900149-8b4e0862-1e3b-11e8-9cbf-9943ff6dad5a.png">

<img width="412" alt="71441d4b-b699-452c-9958-794cfb959012" src="https://user-images.githubusercontent.com/25789719/36900157-91ec3180-1e3b-11e8-9b59-ee58431872a6.png">

<img width="741" alt="7bbba48f-f8d4-4634-b9c2-f47b06e33143" src="https://user-images.githubusercontent.com/25789719/36900160-971e40b2-1e3b-11e8-9b69-e478ee904d64.png">

- environment version:

JumpScale

    Core: branch: production (8a77511) 1/23/2018, 5:15:23 PM
    Portal: branch: production (ada4a21) 1/30/2018, 9:44:31 PM

OpenvCloud

    Core: branch: production (a5c4eee) 2/14/2018, 3:32:38 PM
    G8VDC: branch: production (989668b) 12/27/2017, 6:19:04 PM
    Selfhealing: branch: production (3bc2f9b) 2/7/2018, 3:58:11 PM

**Comment by FastGeert** [comment]
@grimpy please work out a bit more specifications.

**Comment by grimpy** [comment]
The above request was handled a bit differently UI wise.
We've added audits that are registered at the beginning of each call and updated at the end of the call during this process of the call all background jobs related to the request will be visible inside the audit page.

Audits linked to resources vms/cloudspaces/accounts/stacks are visible on the details page of each resource
