### ISSUE TITLE
Deletion portforward rules is hanging

### ISSUE THREAD

**Issue by islamTaha12** [0-complexity/openvcloud#1410]
**steps**
1- Login to the env 
2- Create a vm
3- Create port forward rule
4- Try to delete this portforward rule

**Actual result**
![image](https://user-images.githubusercontent.com/17981089/36944320-56bc4f88-1fa2-11e8-85c3-09ad848cb83d.png)

**OS version**
```
JumpScale
Core: branch: master (0fdeaf3) 02/03/2018, 20:41:51
Portal: branch: master (3df0a29) 01/03/2018, 20:00:47
OpenvCloud
Core: branch: master (11f0302) 04/03/2018, 09:20:46
G8VDC: branch: master (d4b49c1) 13/02/2018, 13:56:43
Selfhealing: branch: master (8f2a952) 01/03/2018, 17:40:22
OpenvStorage be-g8-3
openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.0-1
openvstorage-webapps: 2.9.12-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.12-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.26
openvstorage: 2.9.12-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.2-1
openvstorage-sdm: 1.9.1-1
```

**Comment by ramezsaeed** [comment]
cannot reproduce 
JumpScale

    Core: branch: master (3f55ec4) 3/5/2018, 3:34:08 PM
    Portal: branch: master (be124d0) 3/5/2018, 12:31:52 PM

OpenvCloud

    Core: branch: master (f2c3e25) 3/6/2018, 6:12:11 PM
    G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
    Selfhealing: branch: master (4adf360) 3/4/2018, 10:58:12 AM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.12-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.12-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.26
    openvstorage: 2.9.12-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.2-1
    openvstorage-sdm: 1.9.1-1
