### ISSUE TITLE
Create the possibility to have any size of VM's (CPU/MEM) in a variable way not fixed to a size ID.

### ISSUE THREAD

**Issue by wvandebroeck** [0-complexity/openvcloud#1424]
Altirium customers request the possibility of having any size VM instead of fixed machine ID.  We should enabled them to create any size of vm (CPU/MEM without constrains and compatible with the system limits).

**Comment by abdulrahmantkhalifa** [comment]
To test follow cenarios stated in the picture :

**Comment by abdulrahmantkhalifa** [comment]
![](https://i.imgur.com/OfX2Oj3.jpg)
