### ISSUE TITLE
Disable CS doesn't disable the router OS 

### ISSUE THREAD

**Issue by islamTaha12** [0-complexity/openvcloud#1425]
#### Detailed description
Disable CS doesn't disable the router OS.

#### Steps to reproduce
- Create  a new CS as an admin
- Disable this CS
- Create a new VM in this CS, It is running VM
- Try to access this vm through SSH

**Actual result**
You can access this VM, however, the CS is disabled which is meaning that the RouterOS is still running.

**OS Version**
````
JumpScale
Core: branch: master (0de3a2b) 04/03/2018, 14:06:10
Portal: branch: master (3bb6e8e) 04/03/2018, 18:44:27
OpenvCloud
Core: branch: master (7e570f3) 04/03/2018, 20:49:52
G8VDC: branch: master (d4b49c1) 13/02/2018, 13:56:43
Selfhealing: branch: master (4adf360) 04/03/2018, 10:58:12
OpenvStorage be-g8-3
openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.0-1
openvstorage-webapps: 2.9.12-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.12-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.26
openvstorage: 2.9.12-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.2-1
openvstorage-sdm: 1.9.1-1
```

**Comment by ashraffouda** [comment]
this scenario is not valid, traced it many time on be-scale-2 and be-g8-3 
disabling the cs stopping the router os even u can not create a port forward to the machine if the cs is disabled
and if the machine has a portforward before disabling it u can not do ssh to it
