### ISSUE TITLE
0-access terminates ssh connections in arbitrary time

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1445]
Hello,

 Whilst connecting using 0 access to a system I noticed that when the connection is idle it might be interrupted at any time.

The time doesn't seem to follow a pattern, it can be open for nearly 2 minutes or 4, examples below
```
iceblade:~ krasn$ time ssh 8d3467dbedaf4f6b936ffae46aed9682@ds1.digitalenergy.online -p 7022
~ Asciicast recording started.
~ Hit Ctrl-D or type "exit" to finish.
Warning: Permanently added '10.210.1.62' (ECDSA) to the list of known hosts.
Welcome to Ubuntu 16.04 LTS (GNU/Linux 4.13.0-31-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
Last login: Tue Mar 13 11:49:14 2018 from 10.210.2.1
root@ds1-stor-02:~# ~ Asciicast recording finished.
Connection to ds1.digitalenergy.online closed.

real	1m58.132s
user	0m0.044s
sys	0m0.017s
iceblade:~ krasn$
```
```
iceblade:~ krasn$ time ssh b03bc9a1a031494a8c0c7133c40a8947@ds1.digitalenergy.online -p 7022
~ Asciicast recording started.
~ Hit Ctrl-D or type "exit" to finish.
Warning: Permanently added '10.210.1.62' (ECDSA) to the list of known hosts.
Welcome to Ubuntu 16.04 LTS (GNU/Linux 4.13.0-31-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
Last login: Tue Mar 13 11:17:09 2018 from 10.210.3.1
root@ds1-stor-02:~# date
Tue Mar 13 11:37:01 UTC 2018
root@ds1-stor-02:~# ~ Asciicast recording finished.
Connection to ds1.digitalenergy.online closed.

real	4m43.346s
user	0m0.051s
sys	0m0.021s
```

The problem that comes with this is mainly whilst trying to execute operations that take long time to complete. 

Due to the size of the DS1 environment ovs healthcheck takes about 3.5 minutes.

**Comment by dinosn** [comment]
Please make it last more than 1 hour and if possible not to drop a connection that is not idle.

Eg in some cases we need to work and the tasks take a lot of time. We are getting dropped during operations.

**Comment by grimpy** [comment]
The main issue has been fixed, lets configure it longer then 1 hour I would suggest 8hours (1 working day)

**Comment by ahmedelsayed-93** [comment]
verified 
### software version 
JumpScale
Core: branch: master (f316dcf) 3/15/2018, 11:06:22 AM
Portal: branch: master (37922d2) 3/19/2018, 12:56:12 PM
OpenvCloud
Core: branch: master (386afad) 4/2/2018, 10:56:41 AM
G8VDC: branch: master (b085672) 3/16/2018, 5:09:29 PM
Selfhealing: branch: master (20ee0fa) 3/15/2018, 11:08:04 AM
OpenvStorage be-g8-3
openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.0-1
openvstorage-webapps: 2.9.12-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.12-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.26
openvstorage: 2.9.12-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.2-1
openvstorage-sdm: 1.9.1-1
