### ISSUE TITLE
Got error on Deactive a stor node from portal

### ISSUE THREAD

**Issue by Pishoy** [0-complexity/openvcloud#1446]
#### Detailed description

got error on Deactive a stor node

#### Steps to reproduce

Deactive a stor node from portal 

#### Relevant stacktraces
Your service request could not be fulfilled correctly, please contact support and mention "eco-2001-8b81eb7c-c84e-988f-cf9a-153e93ed9437".

https://OVC2.3.0.../grid/error%20condition?id=8b81eb7c-c84e-988f-cf9a-153e93ed9437

#### Installation information

```


JumpScale

    Core: branch: master (3f55ec4) 3/5/2018, 3:34:08 PM
    Portal: branch: master (be124d0) 3/5/2018, 12:31:52 PM

OpenvCloud

    Core: branch: master (f2c3e25) 3/6/2018, 6:12:11 PM
    G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
    Selfhealing: branch: master (4adf360) 3/4/2018, 10:58:12 AM

OpenvStorage ds1

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.8-1
    openvstorage-webapps: 2.9.12-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.12-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.26
    openvstorage: 2.9.12-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.2-1
    openvstorage-sdm: 1.9.1-1

```

**Comment by Pishoy** [comment]
another note we got a new script from ovs  to include cloud-int disks to be moved as the past was not moved will file it on ticket to review it , was provided by Jeroen Maelbrancke

**Comment by Pishoy** [comment]
[move_disks.gig.txt](https://github.com/0-complexity/openvcloud/files/1806787/move_disks.gig.txt)

**Comment by ashraffouda** [comment]
this link is not a reachable one https://ovc2.3.0.../grid/error%20condition?id=8b81eb7c-c84e-988f-cf9a-153e93ed9437
can u plz provide the stack trace?

**Comment by grimpy** [comment]
This issue was fixed as part of 2.4.0

**Comment by grimpy** [comment]
The custom script should not be used and will not be supported by us as the maintenance procedure handles all disks including cloud-init

**Comment by ahmedelsayed-93** [comment]
verified 
### software versions
```
JumpScale
Core: branch: master (f316dcf) 3/15/2018, 11:06:22 AM
Portal: branch: master (6012e26) 4/2/2018, 7:40:00 PM
OpenvCloud
Core: branch: master (a66bbff) 4/12/2018, 9:54:47 AM
G8VDC: branch: master (b085672) 3/16/2018, 5:09:29 PM
Selfhealing: branch: master (7e92f5a) 4/3/2018, 10:33:53 AM
OpenvStorage se-gen-1
openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.8-1
openvstorage-webapps: 2.9.12-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.12-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.26
openvstorage: 2.9.12-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.2-1
openvstorage-sdm: 1.9.1-1
```
