### ISSUE TITLE
Grid last checked is not being displayed on most nodes

### ISSUE THREAD

**Issue by siddiquagig** [0-complexity/openvcloud#1465]
On most of the nodes and also on the main Status Overview Page, grid last checked time is not being displayed.

This issue is occuring on ds1:

![grd1](https://user-images.githubusercontent.com/25789724/37594334-50a4495a-2b8e-11e8-93b5-e54fedb5ff33.JPG)
![grid2](https://user-images.githubusercontent.com/25789724/37594335-50cf0dac-2b8e-11e8-83da-d84a71f8f2ee.JPG)

#### Installation information

OpenvCloud
Core: branch: master (f2c3e25) 3/6/2018, 8:12:11 PM
G8VDC: branch: master (d4b49c1) 2/13/2018, 3:56:43 PM
Selfhealing: branch: master (4adf360) 3/4/2018, 12:58:12 PM

**Comment by siddiquagig** [comment]
https://docs.greenitglobe.com/gig/proj_russia_digital_energy/issues/556

**Comment by ashraffouda** [comment]
can not reproduce
