### ISSUE TITLE
Failed executing job heartbeat check / Jobs Section shows us nothing

### ISSUE THREAD

**Issue by siddiquagig** [0-complexity/openvcloud#1466]
When clicking on the error  Failed executing job heartbeat check on the ctrl, when we click on its Error link , it takes us to the Jobs page link which shows us nothing in the tables.

![heart1](https://user-images.githubusercontent.com/25789724/37595060-c428c5e8-2b90-11e8-9e13-7a34126fb1f5.JPG)

OpenvCloud
Core: branch: master (f2c3e25) 3/6/2018, 8:12:11 PM
G8VDC: branch: master (d4b49c1) 2/13/2018, 3:56:43 PM
Selfhealing: branch: master (4adf360) 3/4/2018, 12:58:12 PM

**Comment by alichaddad** [comment]
This is still not completely fixed. The healthcheck collects info for each node but we don't have info where the healthcheck itself ran. So clicking on the error will still redirects to an empty table since it will point to the node id that the job ran for this node not the healthcheck job node.
