### ISSUE TITLE
FR: Add Alerta Configuration to the installation script of ovc

### ISSUE THREAD

**Issue by hossnys** [0-complexity/openvcloud#1467]
#### Detailed description
we need to automate adding new environments to Alerta when installing by the new script of ovc 2.3.0 here is the configuration we need to add to this file on Ctrl : /opt/jumpscale7/hrd/system/system.hrd
alerta.api_key                 = '0s5PFkJfGjIZvzR3kdkgS92gjGFOS7m9U8sV0S5B'
alerta.api_url                 = 'http://alerta.aydo.com:8000/api'

**Comment by abdulrahmantkhalifa** [comment]
https://github.com/0-complexity/openvcloud_installer/issues/104 duplicate

**Comment by ahmedelsayed-93** [comment]
verified
