### ISSUE TITLE
in ovc 2.3.0 can't enable image

### ISSUE THREAD

**Issue by hossnys** [0-complexity/openvcloud#1470]
#### Detailed description
here is the warning that appears when trying to enable an image from portal

- ovc version : 2.3.0
![ds1](https://user-images.githubusercontent.com/26298009/37769898-476adf62-2ddb-11e8-977d-5f432c5c7b47.jpg)

**Comment by grimpy** [comment]
The popup does not relate to the action, the action itself works fine.
I'll close the issue if you have more input please make a new ticket

**Comment by ashraffouda** [comment]
can not reproduce
