### ISSUE TITLE
OVC 2.3.0 duplicated packages during migration

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1473]
Whilst migrating to OVC 2.3.0 from an elder 2.2.x release we have the following packages showing up on the environment. 

Duplicate packages:

<img width="1325" alt="screen shot 2018-03-27 at 14 06 36" src="https://user-images.githubusercontent.com/3851678/37963858-3b6c3382-31c8-11e8-9574-2f191b0842d9.png">

**Comment by dinosn** [comment]
Also choosing one package seem to also select one other. Eg 2 GB Memory 2 core will select 4 GB Memory 2 Cores as well as listed below:

<img width="1271" alt="screen shot 2018-03-27 at 14 12 46" src="https://user-images.githubusercontent.com/3851678/37964088-f33f3176-31c8-11e8-9aab-eca3b42be444.png">

**Comment by ahmedelsayed-93** [comment]
verified 

### software version 
JumpScale
Core: branch: master (f316dcf) 3/15/2018, 11:06:22 AM
Portal: branch: master (6012e26) 4/2/2018, 7:40:00 PM
OpenvCloud
Core: branch: master (659271e) 4/2/2018, 7:27:36 PM
G8VDC: branch: master (b085672) 3/16/2018, 5:09:29 PM
Selfhealing: branch: master (20ee0fa) 3/15/2018, 11:08:04 AM
OpenvStorage be-g8-3
openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.0-1
openvstorage-webapps: 2.9.12-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.12-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.26
openvstorage: 2.9.12-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.2-1
openvstorage-sdm: 1.9.1-1
