### ISSUE TITLE
OVC 2.3.0 GRAFANA is not working properly

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1475]
Grafana is not configured properly on the 2.3.0 installation the initial dashboard is the one below attached:
<img width="1440" alt="screen shot 2018-03-27 at 14 10 32" src="https://user-images.githubusercontent.com/3851678/37964037-c647bd8c-31c8-11e8-84e8-a7830599e1a7.png">

**Comment by grimpy** [comment]
Default entry page was always some kind of welcome page not a dashboard

**Comment by FastGeert** [comment]
Lets loose the "HOME" dashboard, and select the "Overal system performance" dashboard by default.
