### ISSUE TITLE
OVC 2.3.0 Machine creation takes long time and boot of the system is stalled

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1476]
As per attached image after the creation of the VM we see on the console only the following message

<img width="1384" alt="screen shot 2018-03-27 at 14 16 24" src="https://user-images.githubusercontent.com/3851678/37964276-97adb19c-31c9-11e8-8081-db2007efc6b1.png">

**Comment by grimpy** [comment]
due to OVS disk/connection being slow
![image](https://user-images.githubusercontent.com/143869/38171220-629c9b24-3595-11e8-8f90-1cba01f32c0a.png)
