### ISSUE TITLE
OVC 2.3.0 Changing port forward returns bogus message about VM

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1477]
On a newly created VM I've added a port forward and went back to change the port to a different one.

The following message was displayed
<img width="1425" alt="screen shot 2018-03-27 at 14 20 12" src="https://user-images.githubusercontent.com/3851678/37964436-26077a68-31ca-11e8-809c-845e80a54c11.png">

**Comment by ahmedelsayed-93** [comment]
verified on be-g8-3

### software version
JumpScale
Core: branch: master (f316dcf) 3/15/2018, 11:06:22 AM
Portal: branch: master (37922d2) 3/19/2018, 12:56:12 PM
OpenvCloud
Core: branch: master (386afad) 4/2/2018, 10:56:41 AM
G8VDC: branch: master (b085672) 3/16/2018, 5:09:29 PM
Selfhealing: branch: master (20ee0fa) 3/15/2018, 11:08:04 AM
OpenvStorage be-g8-3
openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.0-1
openvstorage-webapps: 2.9.12-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.12-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.26
openvstorage: 2.9.12-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.2-1
