### ISSUE TITLE
OVC 2.3.0 Failed to delete port forward error, while delete was successful

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1478]
As whilst trying to delete a port forward the following message appears

![screen shot 2018-03-27 at 10 34 04](https://user-images.githubusercontent.com/3851678/37964667-f930122e-31ca-11e8-968e-b01dc1246be8.png)

The portforward though is deleted

**Comment by ashraffouda** [comment]
can not reproduce

**Comment by ahmedelsayed-93** [comment]
can't reproduce
