### ISSUE TITLE
OVC 2.3.0 Port forward stuck on OK button

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1479]
Whilst adding a portforward on a VM pressing ok will not return you back to the portal but the screen will remain the same even though pressing cancel and refresh will show the portforward normally.
<img width="1430" alt="screen shot 2018-03-27 at 14 28 14" src="https://user-images.githubusercontent.com/3851678/37964780-5780727e-31cb-11e8-8cc9-c2f0a17039cd.png">

**Comment by grimpy** [comment]
Works when ros works.
This needs better UI / api work when ros is down we should return a 503 (service unaivable) with a message indicating something is wrong on the ROS
