### ISSUE TITLE
OVC 2.3.0 VDC stuck in deleting status

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1481]
Whilst trying to delete a VDC we see the following status on it for hours

<img width="1439" alt="screen shot 2018-03-27 at 14 38 25" src="https://user-images.githubusercontent.com/3851678/37965117-9dbdcb78-31cc-11e8-8c66-b200151c926d.png">

**Comment by grimpy** [comment]
Resolved by: https://github.com/0-complexity/openvcloud/pull/1485
