### ISSUE TITLE
ROS crashing under high load

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1482]
We have several cases where a ROS is crashing under high load of traffic/ requests. To mitigate the case the following is suggested as action:

By default, a VM with ROS is created with 1 vcpu, however in the ROS settings the System -> Resources -> Hardware -> "Multi CPU" checkbox is checked If this checkbox is unchecked and then ROS is rebooted, it starts to work stably without interface freezing and with better network performance. 

We need to know how we can uncheck this checkbox by default when creating a VFW.

**Comment by FastGeert** [comment]
Need to configure the ROS correctly at creation.

**Comment by grimpy** [comment]
Please at migration script to set this flag on existing routeros

**Comment by ahmedelsayed-93** [comment]
controller node can't reach ros internal ip 
```
Traceback (most recent call last):
~   File "/opt/jumpscale7/lib/JumpScale/grid/jumpscripts/JumpscriptFactory.py", line 176, in executeInProcess
    return True, self.module.action(*args, **kwargs)
~   File "/tmp/jumpscripts/greenitglobe_migrate_ros_config.py", line 23, in action
    router = j.clients.routeros.get(vfw['host'], vfw['username'], vfw['password'])
~   File "/opt/jumpscale7/lib/JumpScale/lib/routeros/RouterOS.py", line 12, in get
    return RouterOS(host, login, password, timeout)
~   File "/opt/jumpscale7/lib/JumpScale/lib/routeros/RouterOS.py", line 152, in __init__
    self._s.connect((host, 8728 ))
~   File "/opt/jumpscale7/lib/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
~ error: [Errno 113] No route to host
```
