### ISSUE TITLE
disabled image appear in end user portal

### ISSUE THREAD

**Issue by mohamedgalal99** [0-complexity/openvcloud#1498]
#### Detailed description
When we disable image, it's still appear in end user portal, 
user can't create image from it and will erais no available resources to lunch this vm
we need it to disabled from end user too, and he can't see it

#### Relevant stacktraces

| Please make sure to include the stacktrace found under /grid/error conditions in the portal.
Adding a link alone is not sufficient as it might have expired by the time the issue is looked at.

#### Installation information

- environment version:
- operating system:
- portal verison
- ovc version

**Comment by ahmedelsayed-93** [comment]
verified 
### software versions
```
JumpScale
Core: branch: master (f316dcf) 3/15/2018, 11:06:22 AM
Portal: branch: master (6012e26) 4/2/2018, 7:40:00 PM
OpenvCloud
Core: branch: master (a66bbff) 4/12/2018, 9:54:47 AM
G8VDC: branch: master (b085672) 3/16/2018, 5:09:29 PM
Selfhealing: branch: master (7e92f5a) 4/3/2018, 10:33:53 AM
OpenvStorage se-gen-1
openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.8-1
openvstorage-webapps: 2.9.12-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.12-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.26
openvstorage: 2.9.12-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.2-1
openvstorage-sdm: 1.9.1-1
```
