### ISSUE TITLE
images does not removed auto from /opt after creating an images on OVC

### ISSUE THREAD

**Issue by Pishoy** [0-complexity/openvcloud#1504]
#### Detailed description

- when we create an image the images are stored on /opt as below screen shot 
the images are consumes our / as it should remove after successfully creating it and the should exist on stors on  /mnt/vmstor/templates/  after successfully images creation and enabling them available from portal

- we need to remove the images from /opt after successfully images creation and enabling them
- we have faced that before on old ovc versions 

#### Steps to reproduce
1- create images 
2- enable images from portal
3- check the /opt/jumpscale7/var/tmp/templates  and /mnt/vmstor/templates/ 

#### Installation information
```
JumpScale

    Core: branch: master (3f55ec4) 3/5/2018, 3:34:08 PM
    Portal: branch: master (be124d0) 3/5/2018, 12:31:52 PM

OpenvCloud

    Core: branch: master (f2c3e25) 3/6/2018, 6:12:11 PM
    G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
    Selfhealing: branch: master (4adf360) 3/4/2018, 10:58:12 AM

OpenvStorage ds1
    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.8-1
    openvstorage-webapps: 2.9.12-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.12-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.26
    openvstorage: 2.9.12-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.2-1
    openvstorage-sdm: 1.9.1-1

```

**Comment by Pishoy** [comment]
![opt](https://user-images.githubusercontent.com/21987477/38564669-e7576a00-3cdf-11e8-8246-c7d1c56a121c.jpg)

**Comment by Pishoy** [comment]
https://docs.greenitglobe.com/gig/proj_gig_belgium/issues/67

**Comment by ahmedelsayed-93** [comment]
verified
