### ISSUE TITLE
2.4.0 kubernetes setup doesn't include ipmi entries for the controllers

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1510]
Hi , 
  It came to attention that the 2.4.0 setup with the kubernetes does not contain entries for the ipmi interfaces of the controllers. 

Without them we are not able to connect to IPMI interfaces and see possible issues / reboot controllers.

Changing the config file using ' kubectl edit configmap system-config '  and deleting the pxeboot pod had no effect as the new entries were not added.

**Comment by FastGeert** [comment]
Need to discuss with @dinosn and @grimpy how to solve this.

**Comment by FastGeert** [comment]
Use the last significant byte of the controller to count back from the end of subnet to provide the ipmi's with an ip
