### ISSUE TITLE
2.3.0 vm export doesn't work on second attempt

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1511]
When a user is exporting a VM to the webdav server the process cannot be repeated a second time. 

 If the user deletes the files from the webdav and tries to re-export the vm image the only file that will be uploaded on the webdav remote system will be the readme file.

**Comment by ahmedelsayed-93** [comment]
got this error in be-g8-3
owncloud server hosted on owncloud.aydo.com

![image](https://user-images.githubusercontent.com/24386820/39008169-33633ca6-4408-11e8-87b9-02bb3b74e405.png)

```
bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)
```

**Comment by ahmedelsayed-93** [comment]
issue still exists

**Comment by ahmedelsayed-93** [comment]
verified 
```
JumpScale
Core: branch: master (5c89f2c) 4/12/2018, 3:04:38 PM
Portal: branch: master (6012e26) 4/2/2018, 7:40:00 PM
OpenvCloud
Core: branch: master (ed3cc4a) 4/18/2018, 2:31:12 PM
G8VDC: branch: master (b085672) 3/16/2018, 5:09:29 PM
Selfhealing: branch: master (433ac94) 4/17/2018, 12:00:43 PM
```
