### ISSUE TITLE
Deployment_test : Failed to create VM

### ISSUE THREAD

**Issue by PeterNashaat** [0-complexity/openvcloud#1520]
#### Detailed description

- after checking the cloudspace it has 250 vms including the deleted vms (not Destroyed)

#### Relevant stacktraces

<class 'JumpScale.baselib.http_client.HttpClient.HTTPError'>: 400:
 "Can not create more than 250 Virtual Machines per Cloud Space"

#### Installation information

- environment version:master
- operating system:master
- portal verison:master
- ovc version:master

**Comment by FastGeert** [comment]
Deployment test also needs to perform a permanent delete of vms.

**Comment by ahmedelsayed-93** [comment]
needs direct api to permanent delete of vms
blocked on this feature https://github.com/0-complexity/openvcloud/issues/1555
