### ISSUE TITLE
FR : manual specify the storage node on created VMs

### ISSUE THREAD

**Issue by Pishoy** [0-complexity/openvcloud#1526]
#### Detailed description
need to specify the store node which the VM will be created 
actual we can not specify the store node the VM will be created 
i suggest 
- new option, if we deactivated a store nodes without moving the vdisks so if we deactivated all store nodes instead one so we can create the VMs on specific store node ?
- or can we add an option like current specification of cpu node on current solution ?

#### Steps to reproduce
need to create a 50 VMs on a specific store node like stor-02

##### Gitea issue
https://docs.greenitglobe.com/gig/org_support/issues/565

**Comment by FastGeert** [comment]
Won't fix
