### ISSUE TITLE
FR - when deleting VMs, make sure no orphanage is 

### ISSUE THREAD

**Issue by hofkensj** [0-complexity/openvcloud#1535]
#### Detailed description

When deleting a VM, sometimes the disk in OVS is not deleted.  This creates orphanage.  We need to make sure that this does not happen / either by directly deleting all orphan disks with the healthcheck (a bit like garbage collection) or by retrying the delete after a certain amount of time.

**Comment by FastGeert** [comment]
A a status field to the disk object in the mogodb model.
- MODELED
- CREATED
- ASSIGNED
- TOBEDELETED
- DELETED

So when creating a vm, the disks first are inserted in the model with status MODELED. As soon as they exist in OVS they status CREATED or ASSIGNED (CREATED is used when creating disk regardless of a vm. When detaching a disk from a VM, the disk will go back to status created.). When a disk is deleted it first gets the status TOBEDELETED. Then the system tries to delete it. If this succeeds the disk object in the model gets the status DELETED.

The orphanage check only alerts disks as orphanage that fail to be deleted, after it retried deleting the disk.
The orphanage check looks for disks that do need reside in the model. These disks are not deleted by the orphanage check. Only disks that reside in status TOBEDELETED are deleted by the orphanage check.
