### ISSUE TITLE
Migrate the performance scripts from jumpscale 8 to jumpscale 9 

### ISSUE THREAD

**Issue by Pishoy** [0-complexity/openvcloud#1539]
#### Detailed description

need to migrate performance script from  js8 to js9 

the scripts repo located in  https://github.com/0-complexity/G8_testing

the first directory to be migrated is https://github.com/0-complexity/G8_testing/tree/master/performance_testing/scripts

gitea https://docs.greenitglobe.com/gig/org_support/issues/566

**Comment by Pishoy** [comment]
i got error when i run script `cleanup_vms.py` 

pishoy@Bishoy-Home:~/G8_testing/performance_testing/scripts$ sudo python3 cleanup_vms.py --env se-sto-en01-001.gig.tech --user bishoytest --pwd bishoytest --application_id xxxx --secret xxxx
Traceback (most recent call last):
  File "cleanup_vms.py", line 66, in <module>
    help="itsyouonline Application Id")
  File "/usr/lib/python3.5/optparse.py", line 999, in add_option
    option = self.option_class(*args, **kwargs)
  File "/usr/lib/python3.5/optparse.py", line 569, in __init__
    self._set_opt_strings(opts)
  File "/usr/lib/python3.5/optparse.py", line 609, in _set_opt_strings
    self)
optparse.OptionError: invalid long option string '-appid': must start with --, followed by non-dash
[Sun06 17:05] - ErrorHandler.py   :257 :j.core.errorhandler  - ERROR    - invalid long option string '-appid': must start with --, followed by non-dash

**Comment by FastGeert** [comment]
Won't fix
