### ISSUE TITLE
Network Address Validation Prior to Database insertion

### ISSUE THREAD

**Issue by abdulgig** [0-complexity/openvcloud#1542]
#### Detailed description

Reference to Gitea = https://docs.greenitglobe.com/gig/proj_russia_digital_energy/issues/601

Network Addresses need to properly validated before Database insertion.

#### Steps to reproduce
1. Test with adding spaces (front or end) of the IP Addresses

#### Relevant stacktraces

| Please make sure to include the stacktrace found under /grid/error conditions in the portal.
Adding a link alone is not sufficient as it might have expired by the time the issue is looked at.

#### Installation information
DS1 = https://ds1.digitalenergy.online/grid/Status%20Overview

JumpScale

    Core: tag: v7.3.0 (3f55ec4) 3/5/2018, 5:34:08 PM
    Portal: tag: v7.3.0 (be124d0) 3/5/2018, 2:31:52 PM

OpenvCloud

    Core: branch: HEAD (68e727e) 4/15/2018, 5:51:50 PM
    G8VDC: tag: v2.3.0 (d4b49c1) 2/13/2018, 3:56:43 PM
    Selfhealing: tag: v2.3.0 (4adf360) 3/4/2018, 12:58:12 PM

OpenvStorage ds1

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.8-1
    openvstorage-webapps: 2.9.12-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.12-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.26
    openvstorage: 2.9.12-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.2-1
    openvstorage-sdm: 1.9.1-1

**Comment by grimpy** [comment]
Verified on 2.4.3
