### ISSUE TITLE
vdisks are not deleted in OVS after the retention period on OVC 

### ISSUE THREAD

**Issue by Pishoy** [0-complexity/openvcloud#1550]
#### Detailed description

vdisks are not deleted in OVS after the retention period on OVC 

#### Steps to reproduce
1- configure the retention period to 1 hours at least 
2- delete a VM 
3- wait 1 hour 
4- check the ovs disks

#### Installation information
ovc 2.3.0

**Comment by ahmedelsayed-93** [comment]
verified
