### ISSUE TITLE
Add delete option for the CD-Rom images

### ISSUE THREAD

**Issue by PeterNashaat** [0-complexity/openvcloud#1551]
#### Detailed description

there is no delete option for the CD-Rom images after adding them

#### Installation information

- environment version:master
- operating system:master
- portal verison:master
- ovc version:master

**Comment by FastGeert** [comment]
Needs to work with the "Recycle bin".

**Comment by katia-e** [comment]
Currently when I add image I can delete it only if it has not been used. But if I boot a VM from the image I import, deletion of the image produces error. Steps to reproduce:
1. Import new iso
2. boot a VM from this image
3. delete machine (also from recycle bin)
4. delete the image. For me it produces error: `Cannot delete a used disk`
