### ISSUE TITLE
No data in ACL User portal 

### ISSUE THREAD

**Issue by PeterNashaat** [0-complexity/openvcloud#1554]
#### Detailed description
- users don't have ACL shown for accounts or cloudspace  in the portal 

![b17](https://user-images.githubusercontent.com/13523434/39692776-1c344e84-51e2-11e8-8943-b8cdf815e464.png)

#### Installation information

- environment version:2.3.0
- portal verison:2.3.0
- ovc version:2.3.0

**Comment by dinosn** [comment]
Can we have one update on this please ?

**Comment by grimpy** [comment]
Engineering team confirmed this issue looks like escaping issue happened in the portal API and reality are not affected

**Comment by alichaddad** [comment]
Not the case as of 2.4.3
