### ISSUE TITLE
FR: create a new option to delete the VM with its disks immediately without waiting retention period 

### ISSUE THREAD

**Issue by Pishoy** [0-complexity/openvcloud#1555]
#### Detailed description

create a new option to delete the VM with its disks immediately without waiting retention period 

#### Installation information
ovc 2.3.0

**Comment by Pishoy** [comment]
https://docs.greenitglobe.com/gig/proj_gig_belgium/issues/68

**Comment by wvandebroeck** [comment]
I would like to add to this feature that when we want to delete we need to clearly list the following details: VM name / VDC name / Account name in "Confirm Action Delete" window. We need to add this for both delayed delete and immediate delete.

**Comment by FastGeert** [comment]
@Pishoy I would like to understand the reason why you think we need this feature?

**Comment by Pishoy** [comment]
if we are testing vm creation on environment and we create a lot of vms and we need to destroy them without waiting retention period to clean up environment

**Comment by FastGeert** [comment]
We will solve this issue with introding the "Recycle bin".

Deleting a vm / cloudspace, moves the items to the "Recycle bin".
- Once a week trash is collected automatically.
- A manual permanent delete from "Recycle bin" is supported.
- Empty recycle bin is also possible to purge and permanently delete all items present in the "Recycle bin"
