### ISSUE TITLE
FR: make sure redis is listening to localhost and not on 0.0.0.0

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1565]
Hi we notice on new installations that redis is binding on 0.0.0.0 this is causing a security issue. 

Please make sure that all redis instances are bound only on localhost.

Thanks.

**Comment by grimpy** [comment]
Redis is exposed like this because we pull the statistics out from one central please (statscollection pod)

**Comment by dinosn** [comment]
It should be changed as there is severe security impact. https://thehackernews.com/2018/06/redis-server-hacking.html

**Comment by grimpy** [comment]
@dinosn thats very irrelevant actually, all over the place in openvcloud we consider ourself to be in a friendly network those things should not be exposed to the public we don't even have passwords on them.

**Comment by dinosn** [comment]
As mentioned before, on _all_ environments this was open to the public. Let's make sure that the rules are set properly in the installation process and the service is restricted.

**Comment by dinosn** [comment]
This is duplicate of https://github.com/0-complexity/openvcloud/issues/1326
