### ISSUE TITLE
store node shown as in maintenance mode on js shell while it is shown as enabled in portal 

### ISSUE THREAD

**Issue by Pishoy** [0-complexity/openvcloud#1566]
#### Detailed description

from portal the store node is active while in database is in maintenance mode 
may be that 

storage node status in the model is in maintenance as shown in the attached img , so i think someone tried to put it in maintenance and it actually did but did not reflect the status in the portal
here is how to check the model

from any node type js 
```
lcl = j.clients.osis.getNamespace('system')

lcl.node.get('2001_42')   << you can get node id from portal under grid > gridnodes
```

![image](https://user-images.githubusercontent.com/21987477/40969526-68cce46c-68b8-11e8-927e-3bc8627c773b.png)

#### Steps to reproduce
do not know how it produced but you can try to deactivate a store node

#### Installation information

JumpScale
Core: tag: v7.3.0 (3f55ec4) 3/5/2018, 3:34:08 PM
Portal: tag: v7.3.0 (be124d0) 3/5/2018, 12:31:52 PM
OpenvCloud
Core: branch: HEAD (68e727e) 4/15/2018, 3:51:50 PM
G8VDC: tag: v2.3.0 (d4b49c1) 2/13/2018, 1:56:43 PM
Selfhealing: tag: v2.3.0 (4adf360) 3/4/2018, 10:58:12 AM

**Comment by FastGeert** [comment]
Hmmm, @Pishoy did you refresh your page in the portal?

**Comment by FastGeert** [comment]
@dinosn Could you verify this please?

**Comment by dinosn** [comment]
Not valid @FastGeert it's not verified , cannot be reproduced.
