### ISSUE TITLE
FR: Add the option to disable completely deployment tests

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1569]
Hi as it's requested from clients and as well we would like to have an option to disable in the environment the deployment tests. 

When we will need to get performance metrics we will do so from grafana.

**Comment by grimpy** [comment]
Disabling the account of the deployment test does exactly this. Is this not enough?

**Comment by dinosn** [comment]
Yes if it's permanent action its perfectly fine.

**Comment by grimpy** [comment]
Yes thats permanent.
