### ISSUE TITLE
Removing Orphan OVS bridges

### ISSUE THREAD

**Issue by abdulgig** [0-complexity/openvcloud#1570]
#### Detailed description

Reproducible on env DS1 and MR4

#### Steps to reproduce

- When we stop/start an ROS, it moves to another CPU-node. But on previous CPU we see orphan OVS bridge space_xxxx and vxlan vx-xxxx.

-I created test VDC (ID 134) and one VM in this VDC. Initially ROS (00b3) and VM were located on CPU-08. Then I stop/start ROS and it now located on CPU-19, then I move VM to CPU-01. As result we see OVS bridges space_00b3 on CPU-01, on CPU-19 and on CPU-08, but we haven't any VMs/ROS on CPU-08.

On following pictures you can see initial output of ovs-vsctl show | grep 00b3 on all nodes and output after moving ROS and VM.

#### Installation information

JumpScale

    Core: tag: v7.3.0 (3f55ec4) 3/5/2018, 5:34:08 PM
    Portal: tag: v7.3.0 (be124d0) 3/5/2018, 2:31:52 PM

OpenvCloud

    Core: branch: HEAD (68e727e) 4/15/2018, 5:51:50 PM
    G8VDC: tag: v2.3.0 (d4b49c1) 2/13/2018, 3:56:43 PM
    Selfhealing: tag: v2.3.0 (4adf360) 3/4/2018, 12:58:12 PM

OpenvStorage ds1

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.8-1
    openvstorage-webapps: 2.9.12-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.12-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.26
    openvstorage: 2.9.12-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.2-1
    openvstorage-sdm: 1.9.1-1

**Comment by grimpy** [comment]
Note: OVS bridges are not cleaned up during migrations only during stop, this needs to be fixed

**Comment by alichaddad** [comment]
There needs to be tests for this. Currently it is not clear how will that be done and if it is possible. If not possible move back to verification and remove `autotest` label.

**Comment by alichaddad** [comment]
Moving a vfw works as desired: There are no ovs bridges left behind on the old node.
This isn't the case with stopping/starting a vfw, after vfw is started on the new node the following is still there in the old node: 
```
ovs-vsctl show | grep 00d7
    Bridge "space_00d7"
        Port "vx-00d7"
            Interface "vx-00d7"
        Port "space_00d7"
            Interface "space_00d7"

```

Please write test cases for the described two cases above.
