### ISSUE TITLE
 ROSes should be distributed on all enabled cpu nodes

### ISSUE THREAD

**Issue by Pishoy** [0-complexity/openvcloud#1572]
#### Detailed description

- We have ds1-cpu-35 without enabled public (for customer) OS images. As result we haven't too many VMs on this node. But we have too many ROSes on this node also. I think it's not good situation, because in the case of cpu-node unavailability we will loss networking for many clients for a few minutes (until ROS moves to another node and until MAC table is updated).

- I believe that the ROSes should be evenly distributed on all enabled suitable nodes

- number of ROSes may be increased on a specific node due to migration ROSes when putting another node on maintenance mode 
#### Steps to reproduce
1- Disable OS images on specific cpu node. "Normal" (Ubuntu, RHEL...) VMs wouldn't be created on this node.
2- Create some cloudspaces in env.
3- Check number of ROSes per node. ROSes of created in paragraph 2 cloudspaces will be located on this specific cpu-node.
#### Installation information
```
OpenvCloud
Core: branch: HEAD (68e727e) 4/15/2018, 3:51:50 PM
G8VDC: tag: v2.3.0 (d4b49c1) 2/13/2018, 1:56:43 PM
Selfhealing: tag: v2.3.0 (4adf360) 3/4/2018, 10:58:12 AM
```

**Comment by Pishoy** [comment]
reference ticket https://docs.greenitglobe.com/gig/proj_russia_digital_energy/issues/654

**Comment by Pishoy** [comment]
![_363](https://user-images.githubusercontent.com/21987477/41597393-a135d8ac-73cd-11e8-8c16-5c30bead5ddf.png)

**Comment by FastGeert** [comment]
Implement ROS placement as follows:
- Step 1: Lookup all physical machines that have enough free resources for running a ROS
- Step 2: Sort the list of physical machines in step 1 by the amount of ROSes running on it.
- Step 3: Take the machine with the least amount of ROSes to place the ROS

**Comment by katia-e** [comment]
I have impression that in autotest this line might produce error if more than one cpunodes has minimal number of ROS: 
https://github.com/0-complexity/openvcloud/blob/be3d975340b41307f3c58dc3de2183f64cce82ca/tests/ovc_master_hosted/OVC/b_extended/cloudspace_tests.py#L418

**Comment by ahmedelsayed-93** [comment]
@katia-e 
check https://github.com/0-complexity/openvcloud/pull/1651
