### ISSUE TITLE
Support G8 in darksites (OVC and IYO related)

### ISSUE THREAD

**Issue by wvandebroeck** [0-complexity/openvcloud#1574]
**Subject**

Make IYO  able to run in “dark site” installation (no connection to the Internet).

**Use case**

“Dark site” installation of OVC – no connection to the Internet, consequently it is not possible to use IYO in a usual way. Users of the dark site OVC installation are also isolated from the Internet. In any other aspect the user experience should not be different from a typical OVC installation with Internet access.

Users want to use Jumpscale and OVC API to manage virtual resources provisioned from OVC.

Example: a G8/OVC-based appliance installed in restricted network segment of a large organization for test & development purposes. Only trusted users are allowed to access this restricted network segment and use G8/OVC resources.

**Problems to address**

1.     If there is no IYO authorization provider available to the users, Jumpscale 9.3.x configuration manager will not work as designed and connection to OVC will not be established, which means that the users cannot utilize Jumpscale.

2.     “Legacy users” (i.e. users registered at OVC via username:password) are not supported by Jumpscale OVC client.

3.     If IYO instance has no connection to the Internet, sending SMS messages with one time codes for 2-factor authorization model will not be possible.

Potential solutions to explore

1.     LDAP integration for OVC. Much demanded and ideal solution that, however, requires substantial and careful rework of OVC code.
This option cannot provide quick solution we are seeking now and should be included into the strategic roadmap for Q3’2018.

2.     Enhance IYO code to add an option of running it in an isolated environment with reduced level of security of IYO. Target users should accept the associated risks and mitigate them through other technical means that make the environment trusted.
Quick review of the code and logic of IYO (up to the point that is reachable based on the available documentation) shows that this might be a quick solution, as there are some elements originally designed for development/debugging that can be adapted to support “dark site” IYO instances.

**Solution #2: Upgrade of IYO code**

Below are some considerations that may be used when assessing the feasibility of this solution.

From main.go there is apparently a development mode of IYO that is triggered by a certain combination of command line arguments passed to IYO executable that makes IYO to fall back to “development implementation”. Omitting all of the following command line arguments at the same time triggers the development mode:

·       twilio-AccountSID

·       SmsAeroUser

·       SmsAeroPassword

·       smtp-server

In development mode no real SMS are sent (a stub function from communication/devsms.go is used instead of Twilio or Aero providers) and no real emails are sent (a stub function from communication/email.go is used).

Question 1: can the development mode be enhanced to support 1-factor (username:password) user validation and provide JWTs that will be accepted by Jumpscale if Jumpscale configuration manager is redirected to a local URL at which the isolated instance of IYO is running?

The steps that probably need to be taken to adopt IYO for dark site trusted installations are as follows:

1.     Add ability to run IYO with 1-factor authentication (make IYO not to expect one time code from the user, which in usual installation is delivered over SMS channel) or make IYO accept the same pre-shared code for all users (e.g. “314159”) to emulate 2-factor authorization without actually sending SMS.

2.     Remove email confirmation step from the IYO logic, if possible. If not possible or if it requires substantial effort, we will need to review alternatives for letting IYO verify emails in dark site installation.

3.     Verify that IYO does not require access to any Internet resources to be able to run properly. If it does require such access, we will need to review the circumstances and find a solution to let it run without Internet access.

4.     Verify that OVC environment does not require access to IYO to validate JWTs it receives from the users. Alternatively, if it does require such access, understand how to redirect OVC to the local instance of IYO.

5.     Review the usage of the keys (private & public parts of) that are involved into JWT validation between the user, IYO and OVC in dark site installation. We may need to setup IYO & OVC to use custom keys for dark site installation (i.e. not the real keys of the public IYO and not the development keys that are part of the distribution found under “devcert” directory of the IYO repo).

Question 2: Are there any other approaches (Simper? Less resource hungry?) that may be obvious to the IYO developers to implement “dark site” IYO functionality?

**Comment by FastGeert** [comment]
In the meantime, DE has this working.
