### ISSUE TITLE
FR: New alarm level that does not affect panel's state, for lowest importance events.

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1575]
Hi I would like to suggest to introduce a new alarm level, informational, where alarms like the orphaned disks and alike will be moved into. 

There are some alarms that should do not cause a state change of the portal as they are already scheduled for resolution and they follow an already existing procedure.

**Comment by FastGeert** [comment]
@dinosn I would like to do a meeting on this with Jo and Wim
