### ISSUE TITLE
VM migration failed due to host key checking with node itself

### ISSUE THREAD

**Issue by Pishoy** [0-complexity/openvcloud#1576]
#### Detailed description
we got the below error when migrate a vm on ch from cpu-10 t0 cpu-02 
https://ch-lug-dc01-001.gig.tech/grid/job?id=ca86791e6c474b3d9360b8c632663a84

this error due to we need to setup host key checking with node itself while host key checking between two nodes already setup
```
root@cpu-02:~# ip a s backplane1
9: backplane1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether ec:0d:9a:83:1f:26 brd ff:ff:ff:ff:ff:ff
    inet 10.8.1.12/24 brd 10.8.1.255 scope global backplane1
       valid_lft forever preferred_lft forever
    inet6 fe80::70af:deff:feb0:351a/64 scope link 
       valid_lft forever preferred_lft forever

root@cpu-02:~# ssh 10.8.1.12
The authenticity of host '10.8.1.12 (10.8.1.12)' can't be established.
ECDSA key fingerprint is SHA256:NbbUOcPnoET++OmownbW6uJwWyaEI5cocA4leBQ/37Q.
Are you sure you want to continue connecting (yes/no)? 
```

note 10.8.1.12 is node ip of cpu-02

#### Steps to reproduce
1- do not setup key host checking on ssh for cpu-02
2- setup ssh  host key checking between cpu-10 and cpu-02
3- move vm from cpu-10 to cpu-02

#### Installation information
ovc 2.4.0

**Comment by grimpy** [comment]
https://github.com/0-complexity/selfhealing/pull/180
