### ISSUE TITLE
openvcloud_installler: don't use "sender" field of system-config

### ISSUE THREAD

**Issue by Pishoy** [0-complexity/openvcloud#1579]
#### Detailed description

In system-config exists section about mailing setup.
By default:

    mailclient:
        login: support@greenitglobe.com
        passwd: xxxxxxxxx
        port: 587
        sender: support@greenitglobe.com
        server: smtp.mandrillapp.com

I changed this fields, but `sender` doesn't changed in reality.
We can find `support@greenitglobe.com` in following files anyway.
    ./apps/openvcloud__cloudbroker__main/service.hrd
    ./apps/openvcloud__cbportal__main/service.hrd

As result in reality I have following parameters:

        login: something@digitalenergy.online
        sender: support@greenitglobe.com
        server: smtp.office365.com

As result I have problems with sending emails using smtp.office365.com (smtp.outlook365.com rejects emails because `login` and real `sender` from different domains)

#### Installation information

ovc 2.4.0

**Comment by Pishoy** [comment]
https://docs.greenitglobe.com/gig/proj_russia_digital_energy/issues/659

**Comment by FastGeert** [comment]
Can we move this sort of configuration to the mongodb?

**Comment by grimpy** [comment]
@FastGeert someone needs to populate the db and this will cause use to have things configured in two locations.

**Comment by FastGeert** [comment]
Please ignore my suggestion. 

But document the flow of updating configuration.

**Comment by alichaddad** [comment]
Typo in https://github.com/0-complexity/openvcloud/blob/master/docs/Sysadmin/UpdateSMTP/updatesmtp.md, `affective` instead of `effective`.
