### ISSUE TITLE
Cannot remove IP from Free ip addresses list (external network)

### ISSUE THREAD

**Issue by davshafik** [0-complexity/openvcloud#1608]
#### Detailed description

Cannot remove IP from Free ip addresses list (external network)

#### Steps to reproduce

go to cloudbroker portal  > external network > try to delete an ip from the free ip list 

#### Relevant stacktraces

|nothing happened when i press delete from admin portal

#### Installation information

JumpScale
Core: tag: v7.4.1 (d8a1621) 6/3/2018, 11:33:50 AM
Portal: tag: v7.4.1 (ac3419a) 4/18/2018, 2:53:21 PM
OpenvCloud
Core: tag: v2.4.2 (b452c7c) 6/3/2018, 12:37:20 PM
G8VDC: tag: v2.4.0 (b085672) 3/16/2018, 4:09:29 PM
Selfhealing: tag: v2.4.0 (b32cfe8) 4/22/2018, 9:28:24 AM

**Comment by ahmedelsayed-93** [comment]
@davshafik  can't reproduce on be-g8-3 
can you hard resfresh ```(ctrl + 5)``` your web page and try again ?

**Comment by ahmedelsayed-93** [comment]
```
David Micheal, [11.07.18 11:04]
i have update it to 2.4.3

David Micheal, [11.07.18 11:04]
and seems to be working now
```
