### ISSUE TITLE
Console is not loading in all times

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1612]
Hello, 
   We have the following problem on all the environments.

The VM console from the portal is not always working on the first click over it. 

Clicking randomly on action tab, disk etc and back to console will bring the console eventually operational. 

This can be reproduced in any environment especially on Windows based VMs.

**Comment by grimpy** [comment]
See https://docs.greenitglobe.com/gig/proj_gig_switzerland/issues/79
environment specific after migration.
