### ISSUE TITLE
0-access session leakage

### ISSUE THREAD

**Issue by FastGeert** [0-complexity/openvcloud#1615]
![afbeelding](https://user-images.githubusercontent.com/15246294/42568648-233f5e62-850e-

Fastgeert [1:40 PM]
Am i the only one to use 0-access to dive into the installation?

Jo [1:48 PM]
nope

Nicolas Krassas [1:49 PM]
no
but there is a bug
:
:smile:

Jo [1:49 PM]
so for some reason none of my sessions are there

Nicolas Krassas [1:49 PM]
mine as well
they are not logged

Jo [1:51 PM]
Hey Nicolas you are here now @Fastgeert available for call now?
hmm I guess all sesions from before upgrade are gone (aka not synced between controllers)
because very old sessions of Geert (another install when zaccess was on same controller) are still there

**Comment by alichaddad** [comment]
Fixed here https://github.com/0-complexity/0-access/commit/87e8f385c32c12a8c56c3fa75b6559eb2596148c
