### ISSUE TITLE
Define on image level wether a vm supports hot-add cpu/mem

### ISSUE THREAD

**Issue by FastGeert** [0-complexity/openvcloud#1622]
Not all operating systems support hot adding cpu / memory. So on image level we need to define if the os in the image supports this.

When an image does not support hot-adding resources, then changes will only be applied at the next stop-start sequence.

**Comment by grimpy** [comment]
@ashraffouda please make it possible to edit this setting from the portal image page (edit action)

**Comment by alichaddad** [comment]
There should be some sort of notification indicating that the resize won't apply until the machine are restarted in the case that hot resize isn't supported.
