### ISSUE TITLE
When checking disk status through api, status field sometimes returns empty

### ISSUE THREAD

**Issue by hofkensj** [0-complexity/openvcloud#1638]
#### Detailed description

see https://docs.greenitglobe.com/gig/proj_russia_digital_energy/issues/665#issuecomment-21209

#### Steps to reproduce

done with Jo ... he knows now

#### Relevant stacktraces

i'm to stupid to take them

#### Installation information
 see ticket

**Comment by grimpy** [comment]
Will be handled by https://github.com/0-complexity/openvcloud/issues/1817
