### ISSUE TITLE
FR: Add recycle bin for OVC resources

### ISSUE THREAD

**Issue by alichaddad** [0-complexity/openvcloud#1653]
#### Detailed description

For each available resource(account, cloudspace,...):

- Can be deleted permanently 
- Can be deleted and added to the recycle bin, where it will be possible to restore the resource again or to completely delete it
- Depending on the retention period configured, resources in the recycle bin will be flushed out according to that period, this is done by a recurring job that checks the date the resource was deleted and perform the deletion if necessary
- Flushing all resources of a specific type can be done through the recycle bin as well(permanently deleting all accounts for example)
- The described actions above are recursive. Meaning that deleting a virtual machine for example will delete all its disks, same for restoring and permanent delete 

#### Related issues

- https://github.com/0-complexity/openvcloud/issues/1551
- https://github.com/0-complexity/openvcloud/issues/1601
- https://github.com/0-complexity/openvcloud/issues/1555

**Comment by katia-e** [comment]
Currently if a VM is moved to a recycle bin, VM with the same name can be created in the same VDC, as a result if the VM is recovered from the recycle bin, we have two VMs with the same name. Is there a possibility when creating a new VM to check if there is no VM in Recycle Bin with the same name in the same VDC?
