### ISSUE TITLE
Improve error handling whilst upgrading

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1658]
Hi, 

  We notice the following issue during the upgrade procedure. 

If one node is set on maintenance the upgrade procedure will fail. 

The main issue is that the failed process will leave the whole environment in a non functional state as most of the jsagents in all env will be left killed.

We will ask to suggest,
    To implement a fast healthcheck of the env before an upgrade, in the means of checking proper communication with all elements that will take part on the upgrade. 
   Check the condition of the environment after the upgrade and if there is an error status attempt either to revert , or notify correctly for the error case. 
  Improve the way that the upgrade process take place, make it more robust and able to handle elements as, node done, node in maintenance etc.

Thanks

**Comment by grimpy** [comment]
@ahmedelsayed-93 I know you handled the basics of this one but this ticket is way more involved then the simple case you already handled, Ill move this to 2.5.0 for the additional work

**Comment by ashraffouda** [comment]
Starting migration script ...
ERROR:root:Error:
Traceback (most recent call last):
  File "./installer", line 1666, in upgrade_cluster
    raise RuntimeError("%s: \n%s" % (response.content, response.status_code))
RuntimeError: b'Your service request could not be fulfilled correctly, please contact support and mention "eco-107-ff2a1930-2282-ea5a-b92e-648d7d7abc4b".': 
500
Failed to update environment.
