### ISSUE TITLE
Deployment test cannot succeed cause VMs are limited to 2000 iops

### ISSUE THREAD

**Issue by FastGeert** [0-complexity/openvcloud#1696]
While examining CH environment i saw that the write speed was limited to 8.MB/s which translates into 2176 iops. This is about the same value as the default 2000 iops limitation that is put on the KVM hypervisor disks. Doing some more clicking in the OVS portal, i found that the deployment test vms are configured with the default limit.

![afbeelding](https://user-images.githubusercontent.com/15246294/44058298-02feb468-9f4e-11e8-9f4c-7d13d2a14d86.png)

**Comment by grimpy** [comment]
Not sure how you calculated those numbers...
We write with blocks of (8k * 2000 iops) = 15.625MiB/s

**Comment by grimpy** [comment]
Altough my math is solid I talked with @dinosn about this we decided to lower the warning to 5MiB/s to be on the safe side.
