### ISSUE TITLE
Possibility to set up snapshot calendar per disk

### ISSUE THREAD

**Issue by hofkensj** [0-complexity/openvcloud#1721]
#### Detailed description

We used to have the feature through a blueprint - was never integrated into OVC as I understand.

#### Relevant stacktraces

| Please make sure to include the stacktrace found under /grid/error conditions in the portal.
Adding a link alone is not sufficient as it might have expired by the time the issue is looked at.

#### Installation information

- environment version:
- operating system:
- portal verison
- ovc version

**Comment by FastGeert** [comment]
GIG play feature.
Can be implemented using the OVC cloudapi
