### ISSUE TITLE
DS1: VM image is not consistent with time of creation

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1727]
Hello, 

 As we were trying to delete some older VMs we came into the case of 

https://ds1./cbgrid/Virtual%20Machine?id=4891

This vm with vdisk
openvstorage+tcp://10.210.3.64:26244/vm-4891/bootdisk-vm-4891

Was created on 02/06/2018, 16:30:04 .

Whilst trying to delete the specific VM we received the following:

> Can not delete a Virtual Machine which has clones.
> Existing Clones Are:
>   * om-prod-like-app

Checking om-prod-like-app we see though the following

VM creation time was 18/01/2018, 10:31:46

1 Day earlier than the parent.

This image is Centos where the original is Ubuntu.

From OVS portal we can delete normally without issue what is reported as 'parent vm'.

The above action was tested on different VM having the same issue reported.

**Comment by hofkensj** [comment]
is this solved ??? related to migration ???

**Comment by dinosn** [comment]
please check https://gig-tech.atlassian.net/projects/GIG/queues/custom/15/GIG-89
