### ISSUE TITLE
NetworkIDs not release 

### ISSUE THREAD

**Issue by davshafik** [0-complexity/openvcloud#1728]
#### Detailed description
networkids did not get release in case of failed vdc creation  

#### Steps to reproduce

1- check the free network id using the api call 
2- create vdc that will fail 
3- call the get free networkid api once more and you will notice that the free netid is changed to the next free netid 

#### Relevant stacktraces

| Please make sure to include the stacktrace found under /grid/error conditions in the portal.
Adding a link alone is not sufficient as it might have expired by the time the issue is looked at.

#### Installation information

- environment version:  2.4.4
- operating system: 
- portal verison  2.4.4
- ovc version 2.4.4

**Comment by FastGeert** [comment]
@davshafik Where do i find this API?

**Comment by grimpy** [comment]
@davshafik are you sure? In which state was your cloudspace after this failure? And why did it fail in the first place?

If you cloudspace was in virtual state than this is not a bug but instead expected behaviour

**Comment by davshafik** [comment]
Not valid after checking with Jo
