### ISSUE TITLE
FR: Add multiple nic interfaces on a vm

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1729]
Hi we have a request from clients to be able to connect multiple nic interfaces on a vm. 

  These interfaces will be used for intercommunication between the vms of the same VDC, separating traffic based on the application that will be used.

**Comment by hofkensj** [comment]
need to be able to add different external networks to 1 vm directly

**Comment by FastGeert** [comment]
What we actually need to be able to do is to specify the external network to use when adding an external ip to a vm
