### ISSUE TITLE
when adding an external network to OVC you cannot use it if you are creating a cloudspace

### ISSUE THREAD

**Issue by hofkensj** [0-complexity/openvcloud#1732]
#### Detailed description

External network was created
![image](https://user-images.githubusercontent.com/16613288/44508673-6f348280-a6af-11e8-916b-46308528f6d2.png)

When creating cloudspace it cannot be selected
![image](https://user-images.githubusercontent.com/16613288/44508680-76f42700-a6af-11e8-804a-ba8355051078.png)

#### Steps to reproduce

see above

#### Relevant stacktraces

nothing relevant

#### Installation information

- environment version: OVC 2.2.6 - not tried with newer release

**Comment by FastGeert** [comment]
Cannot reproduce on 2.4.4
