### ISSUE TITLE
snapshot rollback doesn't work for data disk

### ISSUE THREAD

**Issue by mohamedgalal99** [0-complexity/openvcloud#1749]
#### Detailed description
in russia env https://ds1.digitalenergy.online
when i make roll back to snapshot it rollback bootdisk but data disk no

#### Steps to reproduce
- I create vm with bootdisk size 20G
- then attach disk to it , size 50G
- take 1st snapshot
- format disk and create partition 40G, and formatted ext4
- mount new partition and start write on it some files 
- take snapshot
- resize partition ext4 on fly to  45G
- write data on dist
- take snapshot
- write data on boot disk 
- take snapshot
- umount data disk
- write data on boot disk
- stop vm
- roll back the snapshot before last one 
- start vm
=> found that bootdisk only rollback
- stop vm
- roll back to 2nd snapshot i took
- start vm
- mount data disk
=> only changes on boot disk roll back
![boot2](https://user-images.githubusercontent.com/8679870/44846579-0ae66580-ac51-11e8-936f-be0e4259cc19.png)
![boot-1](https://user-images.githubusercontent.com/8679870/44846580-0ae66580-ac51-11e8-8d8e-e34ae6b17480.png)
![snap-1](https://user-images.githubusercontent.com/8679870/44846582-0ae66580-ac51-11e8-98b9-40a225ddfcc8.png)
![vol2](https://user-images.githubusercontent.com/8679870/44846583-0b7efc00-ac51-11e8-85c2-de292e25febe.png)
![vol-1](https://user-images.githubusercontent.com/8679870/44846584-0b7efc00-ac51-11e8-9e1f-cfb8f3b44379.png)

#### Relevant stacktraces

| Please make sure to include the stacktrace found under /grid/error conditions in the portal.
Adding a link alone is not sufficient as it might have expired by the time the issue is looked at.

#### Installation information

- environment version:
- operating system:
- portal verison
- ovc version

**Comment by FastGeert** [comment]
The scenario is unpossible.

![afbeelding](https://user-images.githubusercontent.com/15246294/45082549-df082b80-b0f9-11e8-8ab1-e69ac024505a.png)

**Comment by FastGeert** [comment]
Ok, reopening. Apparently the test resizes the partition. Not the disk.

**Comment by FastGeert** [comment]
We confirm the issue. The problem is due differences in timestamps of snapshots in OVS.
