### ISSUE TITLE
fan check and psu check healthchecks failed to execute and mess up the ECO

### ISSUE THREAD

**Issue by hofkensj** [0-complexity/openvcloud#1771]
#### Detailed description

related to the following tickets @jira

https://gig-tech.atlassian.net/projects/GIG/queues/custom/1/GIG-149

https://gig-tech.atlassian.net/projects/GIG/queues/custom/1/GIG-148

a bunch of ECO's on BE-GEN environment related to that ... not going to sum them up ... just go to 
https://uk-ln-vt-1.g8.gigukportal.tech/grid/Error%20Conditions and you will see

**Comment by FastGeert** [comment]
Not much we can do about this one.
The issue is that the gooxi ipmi is crashing.
We need to try and see if updating the gooxi firmware provides a solution.
