### ISSUE TITLE
Add healtcheck to check for duplicate networkid/public ips

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1778]
We have an issue on CH environment were the same external ip address is used in 2 VDCs
Issue tracked on jira under: https://gig-tech.atlassian.net/browse/GIG-153

The case is with the ip address (185.15.201.121) is here
<img width="1440" alt="screen shot 2018-09-10 at 13 19 15" src="https://user-images.githubusercontent.com/3851678/45292016-87543080-b4fc-11e8-8333-64b76d41b726.png">

**Comment by grimpy** [comment]
The above situation was caused by manually database edits we need to create healthcecks to informs us about these kind of things
