### ISSUE TITLE
FR: remove warning for orphanage

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1824]
Hello , please remove the warning for orphanage, 

  We are not taking any actions as no actions are required when there is an orphanage reported on the system . We have simply to wait for the predefined time so the automated cleanup will kick in. 

I don't believe there is a need to report orphaned disks or to generate a warning for them

<img width="1327" alt="screen shot 2018-09-20 at 07 27 15" src="https://user-images.githubusercontent.com/3851678/45795917-dc373a00-bca6-11e8-8fd8-a6a97e03e8b6.png">

**Comment by FastGeert** [comment]
Will be solved by #1822
