### ISSUE TITLE
Incomplete upgrade is causing a loop on Jobs "update_node" - every 30 sec 

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1910]
Hi we have an issue that is on 2.4.5.1 upgrade. On one system the upgrade was performed whilst the cpu/storage nodes were isolated from internet.

The upgrade procedure failed on the nodes but succeeded on the controllers, as per version reported on the system.

The upgrade was executed later again with internet enabled on the nodes, where a member of the team made a manual change to the database on the version number so the upgrade will be executed again in all environment. 

From that time we see that the agents on all nodes are constantly being restarted with update_node job running on them every 30 seconds.

**Comment by grimpy** [comment]
This will be fixed as part of 2.4.5.2
