### ISSUE TITLE
be able to send email messages to support when we have a problem with our environment

### ISSUE THREAD

**Issue by lzonneke** [0-complexity/openvcloud#375]
## Goal

have a system in place which allows the admin to send notifications in case of serious issues

notifications can be
- SNMP traps
- SMTP configuration for emails
- SMS?

The Admin should also be able to set/clear notifications for every type of alarm.
This request is added due to comments made for sberbank. Compute Scenarios/Notifications

**Comment by abdulgig** [comment]
Moved to gogs = https://docs.greenitglobe.com/gig/proj_russia_digital_energy/issues/11
