### ISSUE TITLE
High Availability of Virtual Machines

### ISSUE THREAD

**Issue by hofkensj** [0-complexity/openvcloud#587]
# Feature Description
When a CPU node fails or there is a kernel crash or anything that takes out KVM, all virtual machines currently will fail.
Users would like to make sure that they can create VM's that automatically restart when these events happen.  The restart should be from the latest know good state of the VM (not the snapshot / but the latest good state).
Two options should exist / either with geo-redundancy or without.  
- non geo-redundant: the VM will start up on a CPU node that has a healthy state in the G8 that it was running in before
- geo-redundant: If the full location has no healthy CPU nodes, the VM will start up on a CPU node that is "NOT in the same location AND is in a healthy state".  This to ensure we protect against full datacenter failures.   The networking needs to persevere too (IP@ stay the same)

# Why we need it
to be at par with AWS and Azure / both deliver this service

# Customers / partners asking for it
Sberbank JV
Olmack Green

# Committed dates
None for the moment - need to give date to Sberbank JV

**Comment by abdulgig** [comment]
Moved to gogs = https://docs.greenitglobe.com/gig/proj_russia_digital_energy/issues/3

**Comment by FastGeert** [comment]
the recently hardened maintenance procedure mostly covers this.

**Comment by dinosn** [comment]
This is still critical we have several cases where the VMs are in halted state after a hard / kernel crash

**Comment by grimpy** [comment]
@dinosn can you update this ticket with the status (last 6months)
