### ISSUE TITLE
Move a vDISK from one VM to another

### ISSUE THREAD

**Issue by hofkensj** [0-complexity/openvcloud#602]
# Feature Description
Allow customers to move a vDISK from one instance to another 
(need to see if this can be fully done by cloning)

# Why we need it
to be at par with AWS and Azure / both deliver this service

# Customers / partners asking for it
Sberbank JV

# Committed dates
None for the moment - need to give date to Sberbank JV

**Comment by abdulgig** [comment]
Moved to gogs = https://docs.greenitglobe.com/gig/proj_russia_digital_energy/issues/8
