### ISSUE TITLE
G8 OS : Safekeeper 2.0 : system to safely log into G8's

### ISSUE THREAD

**Issue by hofkensj** [0-complexity/openvcloud#625]
We need to avoid that devops has to log into controllers to maintain / manage G8's.  If they do we need to make sure 
- that authentication is secure (based on itsyou.online)
- that what they do is logged centrally and their actions can be **easily** checked and reused for the purpose of creating self-healing scripts.

To that end - we need to make a G8 OS Safekeeper 2.0

# what is G8 OS Safekeeper 2.0 ?
- browser based app / that allows admins to get into the G8 environments and launch commands
- does authentication and access authorization based on itsyou.online
- records all terminal activity, so it becomes easily searchable by time / G8 / operator / ...
- allows export of activity for the sake of creating self-healing scripts or reporting activity into tickets towards customers

# minimal requirements
- devops user can log into Safekeeper through itsyou.online / can easily browse the different environments he/she is allowed to access to
- ssh terminal emulation into browser
- recording of all activity / make it searchable
- controller gets a new PAM module that temporary gives sudo rights to user based on JWT token - then SSH session from application server to controller set up (WE NEED TO MAKE SURE THAT ONE CANNOT GET INTO ALL ENVIRONMENTS BY HACKING THE APP SERVER - still to be looked at)

- sessions can be easily exported (maybe even sections of that session can be linkeable) so that parts of the session can be easily shared with co-workers / customers (through adding link to ticket).
- application servers sets up ssh session to controller of the required environment (but first re-checks authorisation of user with itsyou.online) and proxies it to the SSH terminal emulator in the user's browser)

**Comment by FastGeert** [comment]
Implemented through 0-access
