### ISSUE TITLE
Remove the "finance" Group

### ISSUE THREAD

**Issue by yveskerwyn** [0-complexity/openvcloud#648]
Members of the "finance" group used to have access to the "Consumption" page in the "End User Portal", but since the "Consumption" page doesn't exist anymore, let's delete this group.

Also remove the "description" and "domain" columns from the Group table, since they are not really used: 

![screen shot 2017-01-02 at 10 18 28](https://cloud.githubusercontent.com/assets/13795109/21586760/d5ee1b10-d0d4-11e6-9acc-ac296ec554ba.png)

We will also (might) need to adapt the below dialogs:

Wondering:
- Given ItsYou.online integration, we might even need to provide integration here too
- Why wold we want to create a new Group?
- What is domains about anyway?

![screen shot 2017-01-02 at 10 23 08](https://cloud.githubusercontent.com/assets/13795109/21586837/b2702e52-d0d5-11e6-9931-94bc189c0468.png)

![screen shot 2017-01-02 at 10 23 33](https://cloud.githubusercontent.com/assets/13795109/21586840/b63e688c-d0d5-11e6-9572-720bede5e584.png)

**Comment by grimpy** [comment]
https://github.com/0-complexity/openvcloud/pull/1071
https://github.com/0-complexity/openvcloud_ays/pull/16

**Comment by ahmedelsayed-93** [comment]
group finance still exist
![image](https://user-images.githubusercontent.com/24386820/33992193-5384bb40-e0da-11e7-8aa1-1fa5d6c134f5.png)

columns "description" and "domain" still in groups table
![image](https://user-images.githubusercontent.com/24386820/33992218-67ff8b7c-e0da-11e7-862d-72c5b430e11e.png)

tested on be-g8-3
### software version
JumpScale

    Core: branch: master (444fc87) 12/13/2017, 3:08:41 PM
    Portal: branch: master (30066b4) 12/13/2017, 10:39:40 PM

OpenvCloud

    Core: branch: master (596e0d5) 12/14/2017, 1:35:11 PM
    G8VDC: branch: master (ea4dc79) 12/14/2017, 9:33:18 AM
    Selfhealing: branch: master (fd97c9c) 12/13/2017, 3:08:22 PM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1

**Comment by grimpy** [comment]
Upgrade script didnt run
```
root@ovcmaster:/# jspython /opt/code/github/0-complexity/openvcloud/scripts/updates/upgrader.py -v 2.2.3
[*] Executing fixgwmgmtrules on cpunode
[*] Executing rosupdatepool on cpunode
[*] Executing migrate_graphana_dashborad_2.2.3 on master
[*] Executing migrate_models_2.2.3 on master
[*] Executing migratexmls on master
[*] Executing updatevmips on master
```

Please verify after running the upgrader.py with correct version nr

**Comment by ahmedelsayed-93** [comment]
verified 
### software version 
JumpScale

Core: branch: master (444fc87) 12/13/2017, 3:08:41 PM
Portal: branch: master (30066b4) 12/13/2017, 10:39:40 PM
OpenvCloud

Core: branch: master (4827925) 12/17/2017, 8:34:16 AM
G8VDC: branch: master (ea4dc79) 12/14/2017, 9:33:18 AM
Selfhealing: branch: master (a2b9f7f) 12/14/2017, 7:58:45 PM
OpenvStorage be-g8-3

openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.0-1
openvstorage-webapps: 2.9.9-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.9-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.17
openvstorage: 2.9.9-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.1-1
openvstorage-sdm: 1.9.1-1
