### ISSUE TITLE
API for converting + importing hyper-v and VMware images

### ISSUE THREAD

**Issue by yveskerwyn** [0-complexity/openvcloud#712]
As discussed first with @grimpy 

We need an API that allows to covert hyper-v and VMware images and make them available (import) in OpenvCloud, on the **Images** page

This API could then be used in an Actor Template, allowing for send blueprints to a Cockpit with the request to do the conversion + import to G8 environment specified in the blueprint

**Comment by FastGeert** [comment]
We support OVF format for importing virtual machines.
