### ISSUE TITLE
Grafana create dashboard for controller-jsagent8 with empty graphs

### ISSUE THREAD

**Issue by Dinaamagdy** [0-complexity/openvcloud#717]
## Steps : 
Open controller-jsagent8 node from grid then grid nodes 
Open grafana  from statistics 

## Issue : 
From dashboard , you will find controller-jsagent8 and has empty Graphs 

![selection_081](https://cloud.githubusercontent.com/assets/24386802/22792940/05059082-eef7-11e6-9e58-a303fcdb2fa3.png)

## Environment : 
du-conv-2
## Software Version : 

JumpScale
```
Core: branch: 7.1.6 (682e94c) 12/28/2016, 10:07:15 PM
Portal: branch: 7.1.6 (e0ec790) 12/28/2016, 1:13:52 PM
```
OpenvCloud
```
Core: branch: 2.1.6 (122735b) 1/19/2017, 11:55:32 AM
G8VDC: branch: 2.1.6 (9a53d52) 11/27/2016, 11:03:39 AM
Selfhealing: branch: 2.1.6 (6b04cc6) 1/20/2017, 11:06:23 AM
```
OpenvStorage:
```
openvstorage-backend-core: 1.7.9.1-1
openvstorage-health-check: 3.1.5-fargo.1-1
alba: 1.3.3
openvstorage-webapps: 2.7.9.2-1
openvstorage-backend-webapps: 1.7.9.1-1
openvstorage-core: 2.7.9.2-1
openvstorage-hc: 1.7.9.1-1
openvstorage: 2.7.9.2-1
openvstorage-backend: 1.7.9.1-1
openvstorage-sdm: 1.6.9.1-1


```

**Comment by grimpy** [comment]
jsagent8 is no more, but this is still true for master container. @alichaddad I remember you started some work related to this during version 2.1.8. Feeel like picking this up again?

**Comment by Dinaamagdy** [comment]
can't verify due to docker image deleted so no grafana avaialble on be-g8-3

**Comment by grimpy** [comment]
Pumper was installer on envirionment as should can be validated now

**Comment by Dinaamagdy** [comment]
## Software Version 
```
JumpScale
Core: branch: master (a166a21) 12/17/2017, 2:27:29 PM
Portal: branch: master (30066b4) 12/13/2017, 10:39:40 PM
OpenvCloud
Core: branch: master (aa86fa4) 12/18/2017, 8:52:52 AM
G8VDC: branch: master (ea4dc79) 12/14/2017, 9:33:18 AM
Selfhealing: branch: master (d0a4bc5) 12/17/2017, 11:25:08 AM
```
