### ISSUE TITLE
Include UEFI bios from tianocore for enhanced windows 10/2012/2016 UEFI support 

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#806]
Hello, 
  
   After testing we notice that the bios for the UEFI windows installations behave better with the tianocore rom.

With the default bios windows systems under EFI might not boot giving the error 'No bootable device found...' 

Reference, https://github.com/0-complexity/openvcloud/issues/802

For the current setup I could recommend to install it via
```
apt-get install ovmf 
```

Thanks,
Nicolas

**Comment by delandtj** [comment]
you want me to install it in the installer ?

**Comment by grimpy** [comment]
@delandtj libvirt/qemu and related packages are installed in a 2nd phase (does not need to be part of the base os)
