### ISSUE TITLE
/cloudapi/account/delete produce 500 error as a status code

### ISSUE THREAD

**Issue by islamTaha12** [0-complexity/openvcloud#844]
**Steps**
Try to delete any account by /cloudapi/account/delete API

**Traceback**
```python
Traceback (most recent call last):
~   File "/opt/jumpscale7/lib/JumpScale/portal/portal/PortalRest.py", line 254, in execute_rest_call
    result = method(ctx=ctx, **ctx.params)
~   File "/opt/jumpscale7/libext/cloudbrokerlib/authenticator.py", line 138, in wrapper
    return func(*args, **kwargs)
~   File "/opt/jumpscale7/apps/portals/main/base/cloudapi__accounts/methodclass/cloudapi_accounts.py", line 124, in delete
    raise NotImplementedError("Not implemented method delete")
~ NotImplementedError: Not implemented method delete
```

**Version**
JumpScale

    Core: branch: 7.1.7 (bcd7bbd) 2/28/2017, 3:45:14 PM
    Portal: branch: 7.1.7 (6ebf51c) 3/9/2017, 12:09:27 PM

OpenvCloud

    Core: branch: 2.1.7 (72fea5d) 3/15/2017, 8:18:55 AM
    G8VDC: branch: 2.1.7 (d4cbd30) 3/9/2017, 11:57:35 AM
    Selfhealing: branch: 2.1.7 (5e50508) 3/14/2017, 9:15:49 AM

**Comment by FastGeert** [comment]
Please validate if this issue still exists

**Comment by john-kheir** [comment]
This issue is still there.
eco: https://be-g8-3.demo.greenitglobe.com/grid/error%20condition?id=7d038bad-b0dc-dd6e-5361-b163b647cd00
![ecoooo](https://user-images.githubusercontent.com/15011431/35267133-fa12ef3c-002d-11e8-94b7-d50b5aa17389.png)

### Software Version
JumpScale

    Core: branch: 7.2.6 (39bfc82) 1/22/2018, 3:50:58 PM
    Portal: branch: 7.2.6 (fffe2bf) 1/19/2018, 8:40:36 AM

OpenvCloud

    Core: branch: 2.2.6 (b6182f8) 1/22/2018, 2:30:42 PM
    G8VDC: branch: 2.2.6 (989668b) 12/27/2017, 4:19:04 PM
    Selfhealing: branch: 2.2.6 (3a47ecb) 1/22/2018, 11:21:19 AM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1

**Comment by islamTaha12** [comment]
not fixed
![image](https://user-images.githubusercontent.com/17981089/35275526-c16cc7a0-0048-11e8-8e1a-4631397c4025.png)

JumpScale
Core: branch: master (87e1515) 1/22/2018, 2:34:15 PM
Portal: branch: master (5082afa) 1/21/2018, 11:59:47 AM
OpenvCloud
Core: branch: master (c25386e) 1/22/2018, 2:49:10 PM
G8VDC: branch: master (0f14940) 12/27/2017, 9:49:51 PM
Selfhealing: branch: master (8cb3425) 1/22/2018, 11:21:19 AM
OpenvStorage be-g8-4
openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.0-1
openvstorage-webapps: 2.9.9-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.9-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.17
openvstorage: 2.9.9-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.1-1
openvstorage-sdm: 1.9.1-1
