### ISSUE TITLE
Script bug on volumedriver_check.py on be-gen-1

### ISSUE THREAD

**Issue by Pishoy** [0-complexity/openvcloud#849]
#### the local test is running correctly but the end of the results contains the [ ] which i think that give me an error on portal 

root@stor-02:~# jspython /tmp/jumpscripts/jumpscale_volumedriver_check.py
volumedriver vmstor is active: running health checks ...
checking driver /mnt/vmstor
checking if disk ac6156ae-a2ae-4287-982a-62b18ec1d373 is actually in use by ovc
checking if disk 8ac10828-2779-4691-8d60-e1b12aca64f8 is actually in use by ovc
checking if disk abe73643-2d6e-4eb2-8709-fd12fb26cb64 is actually in use by ovc
checking if disk 8fb1ff15-a6fb-4c28-b5c0-040978aa4fcc is actually in use by ovc
disk 8fb1ff15-a6fb-4c28-b5c0-040978aa4fcc is not in use in ovc
checking if disk 8ec9e57c-c1ad-423d-b67a-c90abeef4703 is actually in use by ovc
disk 8ec9e57c-c1ad-423d-b67a-c90abeef4703 is not in use in ovc
checking if disk dc130627-105c-4086-94f7-ae990c6a2c82 is actually in use by ovc
disk dc130627-105c-4086-94f7-ae990c6a2c82 is not in use in ovc
checking if disk 54ecccdd-c107-4e77-b5a1-aa74483577e3 is actually in use by ovc
qemu-img info openvstorage+tcp:10.1.3.22:26203/vm-137/bootdisk-vm-137
qemu-img info openvstorage+tcp:10.1.3.22:26203/vm-461/bootdisk-vm-461
qemu-img info openvstorage+tcp:10.1.3.22:26203/vm-275/bootdisk-vm-275
qemu-img info openvstorage+tcp:10.1.3.22:26203/vm-142/bootdisk-vm-142
volumedriver data02 is active: running health checks ...
checking driver /mnt/data02
checking if disk 7b6e1cbf-2c0f-4d65-9fb4-c6e916a77f21 is actually in use by ovc
qemu-img info openvstorage+tcp:10.1.3.22:26209/volumes/volume_693
volumedriver data03 is active: running health checks ...
checking driver /mnt/data03
checking if disk 8af40818-0c2d-4870-b18a-b4462044b766 is actually in use by ovc
qemu-img info openvstorage+tcp:10.1.3.22:26215/volumes/volume_350
volumedriver data01 is active: running health checks ...
checking driver /mnt/data01
checking if disk d409d2b3-d516-4db1-83b3-8ff1d9ebf07b is actually in use by ovc
qemu-img info openvstorage+tcp:10.1.3.22:26221/volumes/volume_244
[]

#### but on portal give me error as attached image
![volume](https://cloud.githubusercontent.com/assets/21987477/25860241/4535e2bc-34e1-11e7-8968-3b517d143259.png)

#### repo version is 
root@stor-02:~# cd /opt/code/github/jumpscale7/ays_jumpscale7/
root@stor-02:/opt/code/github/jumpscale7/ays_jumpscale7# git status
On branch 7.1.7
Your branch is up-to-date with 'origin/7.1.7'.
nothing to commit, working directory clean
root@stor-02:/opt/code/github/jumpscale7/ays_jumpscale7# cd ..
root@stor-02:/opt/code/github/jumpscale7# cd jumpscale_core7/
root@stor-02:/opt/code/github/jumpscale7/jumpscale_core7# git status
On branch 7.1.7
Your branch is up-to-date with 'origin/7.1.7'.
nothing to commit, working directory clean

**Comment by FastGeert** [comment]
Please validate if this problem still exists
