### ISSUE TITLE
Add POST /cloudapi/users/create

### ISSUE THREAD

**Issue by yveskerwyn** [0-complexity/openvcloud#853]
Currently we only have POST /**cloudbroker**/user/create, requiring admin group membership

We need the equivalent of this **Cloud Broker** API in the **Cloud API** so users with just user group membership can be created without requiring an admin user to create new users

For creating users with admin group membership (full admin users) the existing /**cloudbroker**/user/create should be used, for creating "regular" users the new API can be used

Once this new API got created we should update the [uservdc AYS template](https://github.com/Jumpscale/ays_jumpscale8/blob/8.2.0/templates/ovc/uservdc/actions.py).

**Comment by FastGeert** [comment]
Only level1 is required

**Comment by Dinaamagdy** [comment]
##Software Version 
```
JumpScale
Core: branch: 7.2.6 (8a77511) 1/23/2018, 3:15:23 PM
Portal: branch: 7.2.6 (fffe2bf) 1/19/2018, 8:40:36 AM
OpenvCloud
Core: branch: 2.2.6 (44fca5f) 1/24/2018, 1:46:37 PM
G8VDC: branch: 2.2.6 (989668b) 12/27/2017, 4:19:04 PM
Selfhealing: branch: 2.2.6 (896c248) 1/23/2018, 2:48:33 PM
```
