### ISSUE TITLE
internal server error on logout in VDC

### ISSUE THREAD

**Issue by dimaandg** [0-complexity/openvcloud#855]
when pressing logout in VDC control, you get internal server error
<img width="179" alt="screen shot 2017-05-23 at 14 33 16" src="https://cloud.githubusercontent.com/assets/25789719/26354489/bf5103ac-3fd5-11e7-9800-47eba76a9441.png">
<img width="1085" alt="screen shot 2017-05-23 at 14 33 55" src="https://cloud.githubusercontent.com/assets/25789719/26354490/bf51be3c-3fd5-11e7-8b7f-0858cacf6f16.png">

**Comment by FastGeert** [comment]
Please validate if this problem still exists
