### ISSUE TITLE
rollbackSnapshot en deleteSnapshot always return true...

### ISSUE THREAD

**Issue by yveskerwyn** [0-complexity/openvcloud#869]
Even if snapshot doesn't exist

![snapshot](https://user-images.githubusercontent.com/13795109/29772287-60bab36e-8bf8-11e7-9bbe-7ce2236563cc.jpg)

**Comment by abdulrahmantkhalifa** [comment]
for delete snapshot , they are desined to be omnipotent , the result is it doesn't exist in both cases no change in result we do this for cloudspace/accoutns aswell now

**Comment by ahmedelsayed-93** [comment]
now it returns internal server error
```
TypeError: not enough arguments for format string
Execute method POST_cloudapi_machines_rollbackSnapshot failed.
method was:/restmachine/cloudapi/machines/rollbackSnapshot
```
https://github.com/0-complexity/openvcloud/pull/1525/files#diff-de6bcf7057d6f13eb8ca330cc9fa6283R922

**Comment by ahmedelsayed-93** [comment]
verified

**Comment by ahmedelsayed-93** [comment]
now rollback snapshot returns internal server error 
```
KeyError: timestamp
Execute method POST_cloudapi_machines_rollbackSnapshot failed.
method was:/restmachine/cloudapi/machines/rollbackSnapshot
```

**Comment by ahmedelsayed-93** [comment]
returns ```No snapshots found with params: name None , epoch <epoch>``` when passing a valid epoch

**Comment by ahmedelsayed-93** [comment]
verified
