### ISSUE TITLE
API for making images private

### ISSUE THREAD

**Issue by yveskerwyn** [0-complexity/openvcloud#888]
Making images private is currently supported through manual intervention as documented here:
https://github.com/0-complexity/openvcloud/blob/2.1.7/docs/Sysadmin/Images/private_images.md

Feature request is to make this available through the Cloud API

And also leverage the FR https://github.com/0-complexity/openvcloud/issues/887 so that one can easily make images with specific tags private with one command.

**Comment by abdulrahmantkhalifa** [comment]
Duplicate already closed https://github.com/0-complexity/openvcloud/issues/1243 at https://github.com/0-complexity/openvcloud/commit/47b51f8a8c8405794951b3ea80d324f3219d5392
