### ISSUE TITLE
cloudinit images are not removed upon vm deletion

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#911]
On dc-1.demo.greenitglobe.com, we notice the following.

There are at the moment roughly 7000 vdisks on the system, where the total amount of VMs existing is below 30.

The following issue is observed, upon vm deletion, vms that are used by the deployment test process, the cloud-init-vm-xxx.raw image is not deleted.

VM directories existing on a storage node:
<img width="1295" alt="screen shot 2017-11-11 at 08 24 32" src="https://user-images.githubusercontent.com/3851678/32686980-4b7b3cec-c6ba-11e7-8511-0999e4ec89c4.png">

random sample content of these directories:
<img width="694" alt="screen shot 2017-11-11 at 08 28 49" src="https://user-images.githubusercontent.com/3851678/32686988-664383c2-c6ba-11e7-9e05-5cc9969fe557.png">

**Comment by dinosn** [comment]
Hi the issue still persists, more info are given by the Russia team at  , https://docs.greenitglobe.com/gig/proj_russia_digital_energy/issues/280#issuecomment-9455

**Comment by dinosn** [comment]
Is there any further info on this as we still see them around ?

**Comment by grimpy** [comment]
Putting in verfification as lots of things have changed regarding cloud-init on 2.3.x series

**Comment by Dinaamagdy** [comment]
## steps
- I changed retention period of vm to 60 sec only as steps there https://github.com/0-complexity/openvcloud/blob/master/docs/Sysadmin/AdvancedConfiguration/AdvancedConfiguration.md
- then delete vm 
## Issue 
after checking storage , i found cloud-init of this vm still exist

**Comment by Dinaamagdy** [comment]
## Software Version
``` 
JumpScale
Core: branch: master (0fdeaf3) 3/2/2018, 8:41:51 PM
Portal: branch: master (3df0a29) 3/1/2018, 8:00:47 PM
OpenvCloud
Core: branch: master (11f0302) 3/4/2018, 9:20:46 AM
G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
Selfhealing: branch: master (8f2a952) 3/1/2018, 5:40:22 PM
```

**Comment by Dinaamagdy** [comment]
## Verification steps 
- Ceate VM and check that it exists on vmstor at storage portal .
- Change virtual machines retention period from 7 days to 1 hour  as steps here at any node  : 
https://github.com/0-complexity/openvcloud/blob/master/docs/Sysadmin/AdvancedConfiguration/AdvancedConfiguration.md
- Delete the  VM and wait for 1 hour then check that vm deleted from the storage
