### ISSUE TITLE
Change Google PING HC to be more verbose and accurate

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#916]
We have in some systems, as in Be-gen-1 constant alarms for 'Couldn't ping 8.8.8.8 from ... ' 

On the ROS itself we can verify that the problem is not existing 
<img width="746" alt="screen shot 2017-11-14 at 21 11 47" src="https://user-images.githubusercontent.com/3851678/32799442-72d2c260-c980-11e7-87dc-009a21fa145f.png">

But on the panel we still have multiple alarms. 
<img width="1247" alt="screen shot 2017-11-14 at 21 04 36" src="https://user-images.githubusercontent.com/3851678/32799421-63a38630-c980-11e7-9ebc-01884f212f3e.png">

Is it a case where the tests are performed parallel and icmp is getting possibly throttled ? 

also make sure that if extnernal network = private the healthcheck does not throw an ERROR.

**Comment by FastGeert** [comment]
@dinosn do not agree. The goal of this health check is to validate the route ability of the RouterOs 's upstream network. 

When an external network is created, add ['8.8.8.8'] as the default value for the list of ip's to check.

**Comment by dinosn** [comment]
Geert is pretty normal for a VDC to be isolated from the internet.  There is a client requirement and we will have more on the future. 

To be honest even for our own environments I would prefer that to be the case and the traffic to be handled by one proxy.

Not all cases are internet applicable, consider also the possibility that in the future one client might consider having a whole G8 out of the internet entirely.

**Comment by FastGeert** [comment]
I am aware of that. This is why we make it possible to specify the ips on which the ip-check on a per external network range level.

If the list of ip's that should be checked is empty, then the check will succeed.

**Comment by dinosn** [comment]
Agreed !
