### ISSUE TITLE
make it possible to resize VM online (without shutting it down)

### ISSUE THREAD

**Issue by dimaandg** [0-complexity/openvcloud#924]
add CPU/MEM online
delete - check that it possible, if yes - resize / if now - return "need to shutdown".

https://docs.greenitglobe.com/gig/proj_russia_digital_energy/issues/287

**Comment by FastGeert** [comment]
@grimpy I don't think it is wise to have this implemented while you are absent, right?

**Comment by grimpy** [comment]
@FastGeert correct please see https://github.com/0-complexity/openvcloud/tree/resizevm for work in progress. Altough I'm not sure this approach is gonna workout

**Comment by grimpy** [comment]
Development work completed
