### ISSUE TITLE
Create HC that checks if OVS configured correctly

### ISSUE THREAD

**Issue by hofkensj** [0-complexity/openvcloud#927]
We need to validate if OVS is installed correctly
- need to calculate if write cache size corresponds correctly with size / nr SSD configure with WRITE role
- need to check if components are installed on the correct hardware block device
  - DTL on nvme
  - WRITE (write cache) on ssd (1 or more)

1 / day

@fastgeert Apply all reference OVS architecture

**Comment by FastGeert** [comment]
Is now part of automated install.

**Comment by FastGeert** [comment]
Less of importance due to automated OVS installation
