### ISSUE TITLE
Convert to template

### ISSUE THREAD

**Issue by hofkensj** [0-complexity/openvcloud#930]
When converting a machine into a template we should add the possibility for the user to specify for whom this template will be available:
- cloudspace
- account (only when the use has access to the account)

Add documentation on "How to import a custom image"

**Comment by grimpy** [comment]
Does this issue imply we should first reitroduce conver to template?
In the original implementation a machine that was converted to template was automaticly only available for the account it belonged to.

Shall we rename it back to create template? As the actually original VM will be able to stay in its original state unlike before.

**Comment by grimpy** [comment]
Let's just reimplement using qemu-img convert
Doesnt need to be convert to template anymore back like it used to create templaet (existing vm stays)

**Comment by Dinaamagdy** [comment]
## Software Version
```
JumpScale
Core: branch: master (278c4fb) 2/21/2018, 1:43:54 PM
Portal: branch: master (29a3df6) 2/21/2018, 3:52:30 PM
OpenvCloud
Core: branch: master (81debe4) 2/22/2018, 2:27:21 PM
G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
Selfhealing: branch: master (ac36bf5) 
```
