### ISSUE TITLE
Need selfhealing script that scrubs disks if their stored size grows bigger than 3x the vdisk size

### ISSUE THREAD

**Issue by FastGeert** [0-complexity/openvcloud#932]
Needs to run 1x / day during the night.

**Comment by dinosn** [comment]
This is on OVS not here, http://support.openvstorage.com/servicedesk/customer/portal/1/OVSSUP-322

There is actually a bug on the OVS scrubbing process that should be fixed on the next release.

**Comment by alichaddad** [comment]
Is this still needed? Or is it an OVS issue? @dinosn

**Comment by grimpy** [comment]
We will implemented as suggested but we need to make sure scrubbing isnt already running
