### ISSUE TITLE
delete allowed size returns internal server error

### ISSUE THREAD

**Issue by ahmedelsayed-93** [0-complexity/openvcloud#943]
### API
```
 /cloudapi/cloudspaces/removeAllowedSize
```
### request & response
![image](https://user-images.githubusercontent.com/24386820/32989902-b92c42ea-cd27-11e7-84e7-835d90ed2fb4.png)

### log
![image](https://user-images.githubusercontent.com/24386820/32989886-841c2da4-cd27-11e7-981d-3d2e3f568cf7.png)

**Comment by john-kheir** [comment]
if size is not found, should return 404 not 400

**Comment by grimpy** [comment]
@FastGeert the main object here is the cloudspace so only if cloudspace doesn't exist we should give 404 if size passed is wrong then we should give 400

**Comment by FastGeert** [comment]
Ok, I agree. Thanks for making it more clear @grimpy
