### ISSUE TITLE
Password copy/paste does not work within the Terminal Window of Ubuntu 16.04 Desktop Edition

### ISSUE THREAD

**Issue by hofkensj** [0-complexity/openvcloud#948]

**Comment by ashraffouda** [comment]
@siddiquagig  https://docs.greenitglobe.com/gig/proj_gig_uk/issues/45
I don't have access to this gives 404

**Comment by ahmedelsayed-93** [comment]
### software version
JumpScale

    Core: branch: master (9870155) 12/20/2017, 10:53:52 AM
    Portal: branch: master (9a65ce8) 12/19/2017, 10:56:59 AM

OpenvCloud

    Core: branch: master (c432ffd) 12/24/2017, 9:37:52 PM
    G8VDC: branch: master (fd49072) 12/24/2017, 7:46:34 PM
    Selfhealing: branch: master (748f20f) 12/24/2017, 9:41:56 AM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1
