### ISSUE TITLE
Automate the change of URL-name for the cloud broker portal 

### ISSUE THREAD

**Issue by hofkensj** [0-complexity/openvcloud#949]
The problem that this request tries to resolve is that when the domain name is changed for the cloudbroker portal, the link to open the openvstorage dashboard stops working.

**Comment by grimpy** [comment]
With kubernets this requires one to update the system-config and redeploy portal/nginx pods and all should be done. Do we need more automation or docs?

**Comment by grimpy** [comment]
Needs to be documented how to do this

**Comment by grimpy** [comment]
https://github.com/0-complexity/openvcloud_installer/tree/master/docs
