### ISSUE TITLE
ResetPasswordLink doesn't work correctly 

### ISSUE THREAD

**Issue by Dinaamagdy** [0-complexity/openvcloud#955]
## Steps 
Use POST /cloudapi/users/sendResetPasswordLink to send resetpassword token to given user email.

## Issue 
- click in the received link  in Email, will redirect you to a wrong page as shown 
![selection_583](https://user-images.githubusercontent.com/24386802/33026018-2d285c60-ce18-11e7-89bb-e20fc349f064.png)
- use the token to check validation of resetpasswordlink using Api
``` POST /cloudapi/users/getResetPasswordInformation```
always return Invalid or expired validation token
## Software Version 
```
JumpScale

Core: branch: 7.1.7 (49ee520) 10/22/2017, 2:35:09 PM
Portal: branch: 7.1.7 (87ef628) 11/9/2017, 10:58:39 AM
OpenvCloud

Core: branch: 2.2.0 (ab38409) 11/14/2017, 10:07:38 AM
G8VDC: branch: 2.2.0 (d294b76) 11/2/2017, 9:13:07 PM
Selfhealing: branch: 2.2.0 (1c411b7) 11/16/2017, 11:14:19 AM
```

**Comment by FastGeert** [comment]
This is still used from AYS. Cannot drop it yet.

**Comment by grimpy** [comment]
lets remove from openvcloud

**Comment by ahmedelsayed-93** [comment]
verified 
### software version 
JumpScale

    Core: branch: master (278c4fb) 2/21/2018, 1:43:54 PM
    Portal: branch: master (29a3df6) 2/21/2018, 3:52:30 PM

OpenvCloud

    Core: branch: master (81debe4) 2/22/2018, 2:27:21 PM
    G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
    Selfhealing: branch: master (ac36bf5) 2/21/2018, 3:09:31 PM

OpenvStorage be-g8-4

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1
