### ISSUE TITLE
shouldn't be able to detach the boot disk from a running vm

### ISSUE THREAD

**Issue by ahmedelsayed-93** [0-complexity/openvcloud#969]

**Comment by wvandebroeck** [comment]
@FastGeert i had a chat with Dmitry on this, the end goal is VM mobility between VDC.  Detaching a bootdisk of a VM should never be possible.

**Comment by wvandebroeck** [comment]
VM migration between VDC's. #1059

**Comment by grimpy** [comment]
I beleive we already covered this @ashraffouda can you confirm?

**Comment by FastGeert** [comment]
@grimpy  Are you talking about moving vm's from cs1 to cs2 ?

**Comment by grimpy** [comment]
No I mean detaching boot disk.
