### ISSUE TITLE
Automatic upgrade procedure

### ISSUE THREAD

**Issue by FastGeert** [0-complexity/openvcloud#976]
Sometimes when updating to a new version something more needs to happen than only updating the software. Things like:
- Database migrations
- Configuration upgrades
- 3rd party software packages that need to added / upgraded on the physical machines

We need to do the following:
- Store the version of the product in software
- Store the version of the product in the database
- It is possible to upgrade the version using the portal. The upgrade will sequentially run all the upgrade scripts that upgrade the system going from version x to version x + y.

Upgrade scripts can use the whole framework to execute things that need to be executed away from the OVC master.

**Comment by ahmedelsayed-93** [comment]
### software version 
JumpScale

    Core: branch: master (3f55ec4) 3/5/2018, 3:34:08 PM
    Portal: branch: master (be124d0) 3/5/2018, 12:31:52 PM

OpenvCloud

    Core: branch: master (ab99332) 3/5/2018, 8:29:11 PM
    G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
    Selfhealing: branch: master (4adf360) 3/4/2018, 10:58:12 AM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.12-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.12-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.26
    openvstorage: 2.9.12-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.2-1
    openvstorage-sdm: 1.9.1-1
