### ISSUE TITLE
unable to input vm name or description when creating vm right after using VNC

### ISSUE THREAD

**Issue by mgaber81** [0-complexity/openvcloud#978]
https://docs.greenitglobe.com/gig/proj_russia_digital_energy/issues/94

Currently customer make reload and they expect it to be fixed in whatever upcoming release

**Comment by ahmedelsayed-93** [comment]
verified on be-g8-3
JumpScale

    Core: branch: master (444fc87) 12/13/2017, 3:08:41 PM
    Portal: branch: master (30066b4) 12/13/2017, 10:39:40 PM

OpenvCloud

    Core: branch: master (596e0d5) 12/14/2017, 1:35:11 PM
    G8VDC: branch: master (ea4dc79) 12/14/2017, 9:33:18 AM
    Selfhealing: branch: master (fd97c9c) 12/13/2017, 3:08:22 PM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1
