### ISSUE TITLE
Configure JS agent in systemd

### ISSUE THREAD

**Issue by FastGeert** [0-complexity/openvcloud#984]
Having the js agent running at all times. If the js agent for some reason dies, there is no system in OVC to start it up again.

Solution: configure the js agent as a service in systemd to get it automatically restarted if it would die.

**Comment by ahmedelsayed-93** [comment]
i updated cpu-02 node of be-g8-3 using this command from ovcgit container 
```
jspython  /opt/code/github/0-complexity/openvcloud/scripts/updates/update-ays.py  --node=cpu-02.be-g8-3 --branch-js=master --branch-ovc=master
```
then i executed this command ``` systemctl status jsagent_main```
and that was the response
```
root@cpu-02:~#  systemctl status jsagent_main
jsagent_main.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
```
jsagent_main still running in tmux not as systemd service

**Comment by ramezsaeed** [comment]
need to be tested on fresh installation at least 2.2.3

**Comment by ahmedelsayed-93** [comment]
verified on be-g8-3
